package report

// PDF face for the executive summary. A bounded, one-page document
// rendered with the pure-Go go-pdf/fpdf core fonts (no font files, no
// headless browser - airgap-safe). The page count is O(1): a fixed
// posture block + coverage caveat + the small top-failing list, never
// O(hosts x rules) - that bulk lives in the data faces (CSV/OSCAL),
// per the reports design (the PDF is the bounded human narrative).

import (
	"bytes"
	"fmt"
	"time"

	"github.com/go-pdf/fpdf"
)

// renderExecutivePDF renders the executive summary report as a one-page
// A4 PDF: a header (title, scope, data-as-of, actor), the posture block,
// the coverage caveat (only when some host is stale/unreachable), the
// top-failing-rules list, and a footer carrying the content address.
func renderExecutivePDF(rep Report, c ExecutiveContent) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(rep.Title, true)
	pdf.SetMargins(18, 18, 18)
	pdf.SetAutoPageBreak(true, 18)
	pdf.AddPage()
	// Core fonts are cp1252-encoded; translate UTF-8 (the middle-dot
	// separator, the ellipsis) so it renders instead of mojibake.
	tr := pdf.UnicodeTranslatorFromDescriptor("")

	const (
		ink  = 0x1a
		mut  = 0x6a
		crit = 0xc0
		line = 0xcc
	)

	// Header.
	pdf.SetTextColor(ink, ink, ink)
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(0, 9, rep.Title, "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(mut, mut, mut)
	meta := fmt.Sprintf("OpenWatch   ·   Data as of %s   ·   Scope: %s   ·   Generated by %s",
		rep.DataAsOf.Format("2006-01-02 15:04 MST"), rep.ScopeLabel, rep.GeneratedBy)
	pdf.CellFormat(0, 6, tr(meta), "", 1, "L", false, 0, "")
	pdf.Ln(2)
	pdf.SetDrawColor(line, line, line)
	y := pdf.GetY()
	pdf.Line(18, y, 192, y)
	pdf.Ln(4)

	// Posture block.
	sectionHead(pdf, "Posture snapshot")
	pct := "n/a"
	if c.CompliancePct != nil {
		pct = fmt.Sprintf("%d%%", *c.CompliancePct)
	}
	stat(pdf, "Fleet compliance", pct)
	stat(pdf, "Hosts", fmt.Sprintf("%d", c.HostCount))
	stat(pdf, "Passing rules", fmt.Sprintf("%d", c.PassingRules))
	stat(pdf, "Failing rules", fmt.Sprintf("%d", c.FailingRules))
	stat(pdf, "Critical issues", fmt.Sprintf("%d", c.CriticalIssues))
	pdf.Ln(4)

	// Coverage caveat - only when the report does not reflect the whole
	// in-scope fleet (the staleness honesty the design calls for).
	cov := c.Coverage
	if cov.HostsStale > 0 || cov.HostsUnreachable > 0 {
		parts := ""
		if cov.HostsStale > 0 {
			parts += fmt.Sprintf("%d of %d hosts have compliance data older than 24 hours (or no scan yet)",
				cov.HostsStale, cov.HostsTotal)
		}
		if cov.HostsUnreachable > 0 {
			if parts != "" {
				parts += ". "
			}
			parts += fmt.Sprintf("%d host(s) currently unreachable", cov.HostsUnreachable)
		}
		pdf.SetTextColor(crit, 0x80, 0x10)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.MultiCell(0, 5, "Coverage: figures reflect the last successful scan per host, not current state.", "", "L", false)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(mut, mut, mut)
		pdf.MultiCell(0, 5, parts+". Posture for stale or unreachable hosts may have changed since.", "", "L", false)
		pdf.Ln(4)
	}

	// Top failing rules.
	sectionHead(pdf, "Top failing rules")
	if len(c.TopFailingRules) == 0 {
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(mut, mut, mut)
		pdf.CellFormat(0, 6, "No failing rules in scope.", "", 1, "L", false, 0, "")
	} else {
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(mut, mut, mut)
		pdf.CellFormat(120, 6, "RULE", "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 6, "FAILING HOSTS", "", 1, "R", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(ink, ink, ink)
		for _, t := range c.TopFailingRules {
			pdf.CellFormat(120, 6, t.RuleID, "", 0, "L", false, 0, "")
			pdf.CellFormat(0, 6, fmt.Sprintf("%d", t.FailingHostCount), "", 1, "R", false, 0, "")
		}
	}

	// Footer. Disable auto page-break first so positioning the footer near
	// the bottom margin does not spill an empty trailing page.
	pdf.SetAutoPageBreak(false, 0)
	pdf.SetY(-20)
	pdf.SetDrawColor(line, line, line)
	yf := pdf.GetY()
	pdf.Line(18, yf, 192, yf)
	pdf.Ln(2)
	pdf.SetFont("Helvetica", "", 7)
	pdf.SetTextColor(mut, mut, mut)
	short := rep.ContentSHA256
	if len(short) > 16 {
		short = short[:16]
	}
	signed := "not signed"
	if len(rep.Signature) > 0 {
		signed = "signed " + rep.SigningKeyID
	}
	foot := fmt.Sprintf("OpenWatch executive report   ·   content %s…   ·   %s   ·   %s",
		short, signed, time.Now().UTC().Format("2006-01-02"))
	pdf.CellFormat(0, 5, tr(foot), "", 0, "L", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("report: render pdf: %w", err)
	}
	return buf.Bytes(), nil
}

func sectionHead(pdf *fpdf.Fpdf, s string) {
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetTextColor(0x6a, 0x6a, 0x6a)
	pdf.CellFormat(0, 6, upper(s), "", 1, "L", false, 0, "")
}

func stat(pdf *fpdf.Fpdf, label, value string) {
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(0x6a, 0x6a, 0x6a)
	pdf.CellFormat(50, 6, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(0x1a, 0x1a, 0x1a)
	pdf.CellFormat(0, 6, value, "", 1, "L", false, 0, "")
}

// upper uppercases an ASCII section label without importing strings for
// one call site elsewhere; section labels are ASCII.
func upper(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'a' && c <= 'z' {
			b[i] = c - 32
		}
	}
	return string(b)
}
