// Code generated by scripts/gen-audit-events.go from app/audit/events.yaml.
// DO NOT EDIT. Re-run via: make generate-audit
//
// Source-of-truth registry: app/audit/events.yaml
// Behavioral contract:      app/specs/system/audit-emission.spec.yaml AC-1..AC-3

package audit

// Code is a stable, dotted-hierarchy audit event identifier.
// e.g., auth.login.success, host.created.
type Code string

// Severity grades the operational importance of an event.
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityWarning  Severity = "warning"
	SeverityError    Severity = "error"
	SeverityCritical Severity = "critical"
)

// Event constants. Hand-typed event-string literals are forbidden by lint;
// use these constants.
const (
	// User authenticated successfully
	AuthLoginSuccess Code = "auth.login.success"
	// Authentication attempt failed
	AuthLoginFailure Code = "auth.login.failure"
	// User explicitly logged out
	AuthLogout Code = "auth.logout"
	// Access or refresh token issued
	AuthTokenIssued Code = "auth.token.issued"
	// Refresh token used to issue new access token
	AuthTokenRefreshed Code = "auth.token.refreshed"
	// Token added to revocation blacklist
	AuthTokenRevoked Code = "auth.token.revoked"
	// User completed MFA enrollment
	AuthMfaEnrolled Code = "auth.mfa.enrolled"
	// MFA challenge passed during login
	AuthMfaValidated Code = "auth.mfa.validated"
	// MFA challenge failed
	AuthMfaFailed Code = "auth.mfa.failed"
	// User disabled MFA on their account
	AuthMfaDisabled Code = "auth.mfa.disabled"
	// New session opened
	AuthSessionCreated Code = "auth.session.created"
	// Session timed out (idle or absolute)
	AuthSessionExpired Code = "auth.session.expired"
	// Session revoked (explicit logout or admin action)
	AuthSessionRevoked Code = "auth.session.revoked"
	// User's password was successfully updated
	AuthPasswordChanged Code = "auth.password.changed"
	// Password change rejected by the NIST 800-63B policy validator
	AuthPasswordPolicyFailed Code = "auth.password.policy_failed"
	// API key issued
	AuthApiKeyCreated Code = "auth.api_key.created"
	// API key invalidated
	AuthApiKeyRevoked Code = "auth.api_key.revoked"
	// RBAC denied an authenticated request
	AuthzPermissionDenied Code = "authz.permission.denied"
	// Role assigned to user
	AuthzRoleAssigned Code = "authz.role.assigned"
	// Role removed from user
	AuthzRoleRemoved Code = "authz.role.removed"
	//
	HostCreated Code = "host.created"
	//
	HostUpdated Code = "host.updated"
	//
	HostDeleted Code = "host.deleted"
	//
	HostConnectivityChecked Code = "host.connectivity.checked"
	//
	HostPlatformDetected Code = "host.platform.detected"
	//
	HostIntelligenceRefreshed Code = "host.intelligence.refreshed"
	//
	HostBulkImported Code = "host.bulk_imported"
	//
	CredentialCreated Code = "credential.created"
	//
	CredentialDeleted Code = "credential.deleted"
	//
	ScanQueued Code = "scan.queued"
	//
	ScanStarted Code = "scan.started"
	//
	ScanCompleted Code = "scan.completed"
	//
	ScanFailed Code = "scan.failed"
	//
	ScanCancelled Code = "scan.cancelled"
	//
	ScanSessionCreated Code = "scan.session.created"
	//
	ScanSessionCancelled Code = "scan.session.cancelled"
	//
	ScanTemplateCreated Code = "scan.template.created"
	//
	ScanTemplateUpdated Code = "scan.template.updated"
	//
	ScanTemplateDeleted Code = "scan.template.deleted"
	// Rule state transition (write-on-change pattern)
	ComplianceStateChanged Code = "compliance.state.changed"
	// A single rule finding was persisted to the transaction log (one per transactions row insert). Spec system-transaction-log-writer AC-09.
	FindingPersisted Code = "finding.persisted"
	// writer.Apply rolled back the entire batch due to a DB error (FK violation, deadlock, oversize evidence). Spec system-transaction-log-writer AC-15.
	WriterApplyFailed Code = "writer.apply.failed"
	//
	ComplianceExceptionRequested Code = "compliance.exception.requested"
	//
	ComplianceExceptionApproved Code = "compliance.exception.approved"
	//
	ComplianceExceptionRejected Code = "compliance.exception.rejected"
	//
	ComplianceExceptionRevoked Code = "compliance.exception.revoked"
	//
	ComplianceExceptionExpired Code = "compliance.exception.expired"
	//
	ComplianceBaselineEstablished Code = "compliance.baseline.established"
	//
	ComplianceBaselineCleared Code = "compliance.baseline.cleared"
	//
	ComplianceDriftDetected Code = "compliance.drift.detected"
	//
	ComplianceSnapshotCreated Code = "compliance.snapshot.created"
	//
	AlertCreated Code = "alert.created"
	//
	AlertAcknowledged Code = "alert.acknowledged"
	//
	AlertResolved Code = "alert.resolved"
	//
	AlertThresholdChanged Code = "alert.threshold.changed"
	//
	NotificationDispatched Code = "notification.dispatched"
	//
	NotificationDeliveryFailed Code = "notification.delivery.failed"
	//
	NotificationDeliverySucceeded Code = "notification.delivery.succeeded"
	//
	NotificationChannelCreated Code = "notification.channel.created"
	//
	NotificationChannelUpdated Code = "notification.channel.updated"
	//
	NotificationChannelDeleted Code = "notification.channel.deleted"
	//
	LicenseInstalled Code = "license.installed"
	//
	LicenseInvalid Code = "license.invalid"
	//
	LicenseExpiringSoon Code = "license.expiring_soon"
	//
	LicenseExpired Code = "license.expired"
	//
	LicenseFeatureCheckDenied Code = "license.feature_check_denied"
	//
	LicenseQuotaExceeded Code = "license.quota_exceeded"
	//
	LicenseClockRollbackDetected Code = "license.clock_rollback_detected"
	//
	LicenseTampered Code = "license.tampered"
	//
	PolicyLoaded Code = "policy.loaded"
	//
	PolicyInvalid Code = "policy.invalid"
	// Operation evaluated against a versioned policy
	PolicyApplied Code = "policy.applied"
	//
	RemediationRequested Code = "remediation.requested"
	//
	RemediationApproved Code = "remediation.approved"
	//
	RemediationExecuted Code = "remediation.executed"
	//
	RemediationRolledBack Code = "remediation.rolled_back"
	//
	IntegrationWebhookDelivered Code = "integration.webhook.delivered"
	//
	IntegrationWebhookFailed Code = "integration.webhook.failed"
	// External subscriber registered for event delivery
	IntegrationWebhookSubscribed Code = "integration.webhook.subscribed"
	// Webhook subscription deleted; no further deliveries
	IntegrationWebhookUnsubscribed Code = "integration.webhook.unsubscribed"
	//
	IntegrationPluginInstalled Code = "integration.plugin.installed"
	//
	IntegrationPluginExecuted Code = "integration.plugin.executed"
	// Service has booted and is accepting requests
	SystemStartup Code = "system.startup"
	//
	SystemShutdown Code = "system.shutdown"
	//
	SystemConfigChanged Code = "system.config.changed"
	//
	SystemMigrationApplied Code = "system.migration.applied"
	//
	SystemHealthDegraded Code = "system.health.degraded"
	//
	SystemHealthRecovered Code = "system.health.recovered"
	// Scheduler refused to start because the schedules policy was missing or failed Ed25519 verification
	SchedulerStartupFailed Code = "scheduler.startup.failed"
	// A row in host_compliance_schedule was updated (next_scheduled_scan, maintenance_mode, or manual override)
	SchedulerScheduleUpdated Code = "scheduler.schedule.updated"
	// Runtime policy reload was rejected; the previous valid policy remains active
	SchedulerPolicyReloadRejected Code = "scheduler.policy.reload.rejected"
	// A tier interval in the schedules policy was clamped to the safety floor (5 min) or ceiling (48 h)
	SchedulerPolicyClamped Code = "scheduler.policy.clamped"
	// A schedules policy was signed by a previously-rotated (revoked) signing key and rejected even though the Ed25519 signature was mathematically valid
	SchedulerPolicyRevokedKeyRejected Code = "scheduler.policy.revoked_key.rejected"
	// A dequeued scan job failed HMAC verification; the job payload was tampered after enqueue
	SchedulerJobHmacRejected Code = "scheduler.job.hmac_rejected"
	// Scheduler tick dispatched zero or more scan jobs to the queue
	SchedulerTickDispatched Code = "scheduler.tick.dispatched"
	// Periodic heartbeat from openwatch worker — at 55..65s intervals (60s nominal with jitter)
	WorkerLoopTick Code = "worker.loop.tick"
	//
	AdminUserCreated Code = "admin.user.created"
	//
	AdminUserUpdated Code = "admin.user.updated"
	//
	AdminUserDeleted Code = "admin.user.deleted"
	//
	AdminRoleChanged Code = "admin.role.changed"
	//
	AdminSystemSettingChanged Code = "admin.system_setting.changed"
	//
	AdminRetentionPolicyChanged Code = "admin.retention_policy.changed"
	//
	AdminSsoProviderCreated Code = "admin.sso_provider.created"
	// SSO provider config changed (enable/disable, secret rotation, metadata refresh)
	AdminSsoProviderUpdated Code = "admin.sso_provider.updated"
	//
	AdminSsoProviderDeleted Code = "admin.sso_provider.deleted"
	// Worker drained a diagnostics.test_job and emitted this completion event
	DiagnosticsTestJobCompleted Code = "diagnostics.test_job_completed"
)

// EventMeta is the per-event metadata derived from events.yaml.
type EventMeta struct {
	Code        Code
	Category    string
	Severity    Severity
	Description string
	ActorTypes  []string
}

// Metadata maps every active event code to its registry entry.
var Metadata = map[Code]EventMeta{
	AuthLoginSuccess: {
		Code:        AuthLoginSuccess,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `User authenticated successfully`,
		ActorTypes:  []string{"user"},
	},
	AuthLoginFailure: {
		Code:        AuthLoginFailure,
		Category:    "auth",
		Severity:    SeverityWarning,
		Description: `Authentication attempt failed`,
		ActorTypes:  []string{"user"},
	},
	AuthLogout: {
		Code:        AuthLogout,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `User explicitly logged out`,
		ActorTypes:  []string{"user"},
	},
	AuthTokenIssued: {
		Code:        AuthTokenIssued,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `Access or refresh token issued`,
		ActorTypes:  nil,
	},
	AuthTokenRefreshed: {
		Code:        AuthTokenRefreshed,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `Refresh token used to issue new access token`,
		ActorTypes:  []string{"api_key", "user"},
	},
	AuthTokenRevoked: {
		Code:        AuthTokenRevoked,
		Category:    "auth",
		Severity:    SeverityWarning,
		Description: `Token added to revocation blacklist`,
		ActorTypes:  []string{"system", "user"},
	},
	AuthMfaEnrolled: {
		Code:        AuthMfaEnrolled,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `User completed MFA enrollment`,
		ActorTypes:  nil,
	},
	AuthMfaValidated: {
		Code:        AuthMfaValidated,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `MFA challenge passed during login`,
		ActorTypes:  nil,
	},
	AuthMfaFailed: {
		Code:        AuthMfaFailed,
		Category:    "auth",
		Severity:    SeverityWarning,
		Description: `MFA challenge failed`,
		ActorTypes:  nil,
	},
	AuthMfaDisabled: {
		Code:        AuthMfaDisabled,
		Category:    "auth",
		Severity:    SeverityWarning,
		Description: `User disabled MFA on their account`,
		ActorTypes:  nil,
	},
	AuthSessionCreated: {
		Code:        AuthSessionCreated,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `New session opened`,
		ActorTypes:  nil,
	},
	AuthSessionExpired: {
		Code:        AuthSessionExpired,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `Session timed out (idle or absolute)`,
		ActorTypes:  nil,
	},
	AuthSessionRevoked: {
		Code:        AuthSessionRevoked,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `Session revoked (explicit logout or admin action)`,
		ActorTypes:  nil,
	},
	AuthPasswordChanged: {
		Code:        AuthPasswordChanged,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `User's password was successfully updated`,
		ActorTypes:  nil,
	},
	AuthPasswordPolicyFailed: {
		Code:        AuthPasswordPolicyFailed,
		Category:    "auth",
		Severity:    SeverityWarning,
		Description: `Password change rejected by the NIST 800-63B policy validator`,
		ActorTypes:  nil,
	},
	AuthApiKeyCreated: {
		Code:        AuthApiKeyCreated,
		Category:    "auth",
		Severity:    SeverityInfo,
		Description: `API key issued`,
		ActorTypes:  nil,
	},
	AuthApiKeyRevoked: {
		Code:        AuthApiKeyRevoked,
		Category:    "auth",
		Severity:    SeverityWarning,
		Description: `API key invalidated`,
		ActorTypes:  nil,
	},
	AuthzPermissionDenied: {
		Code:        AuthzPermissionDenied,
		Category:    "authz",
		Severity:    SeverityWarning,
		Description: `RBAC denied an authenticated request`,
		ActorTypes:  nil,
	},
	AuthzRoleAssigned: {
		Code:        AuthzRoleAssigned,
		Category:    "authz",
		Severity:    SeverityWarning,
		Description: `Role assigned to user`,
		ActorTypes:  nil,
	},
	AuthzRoleRemoved: {
		Code:        AuthzRoleRemoved,
		Category:    "authz",
		Severity:    SeverityWarning,
		Description: `Role removed from user`,
		ActorTypes:  nil,
	},
	HostCreated: {
		Code:        HostCreated,
		Category:    "host",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	HostUpdated: {
		Code:        HostUpdated,
		Category:    "host",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	HostDeleted: {
		Code:        HostDeleted,
		Category:    "host",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	HostConnectivityChecked: {
		Code:        HostConnectivityChecked,
		Category:    "host",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	HostPlatformDetected: {
		Code:        HostPlatformDetected,
		Category:    "host",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	HostIntelligenceRefreshed: {
		Code:        HostIntelligenceRefreshed,
		Category:    "host",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	HostBulkImported: {
		Code:        HostBulkImported,
		Category:    "host",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	CredentialCreated: {
		Code:        CredentialCreated,
		Category:    "credential",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	CredentialDeleted: {
		Code:        CredentialDeleted,
		Category:    "credential",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanQueued: {
		Code:        ScanQueued,
		Category:    "scan",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanStarted: {
		Code:        ScanStarted,
		Category:    "scan",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanCompleted: {
		Code:        ScanCompleted,
		Category:    "scan",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanFailed: {
		Code:        ScanFailed,
		Category:    "scan",
		Severity:    SeverityError,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanCancelled: {
		Code:        ScanCancelled,
		Category:    "scan",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanSessionCreated: {
		Code:        ScanSessionCreated,
		Category:    "scan",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanSessionCancelled: {
		Code:        ScanSessionCancelled,
		Category:    "scan",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanTemplateCreated: {
		Code:        ScanTemplateCreated,
		Category:    "scan",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanTemplateUpdated: {
		Code:        ScanTemplateUpdated,
		Category:    "scan",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ScanTemplateDeleted: {
		Code:        ScanTemplateDeleted,
		Category:    "scan",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceStateChanged: {
		Code:        ComplianceStateChanged,
		Category:    "compliance",
		Severity:    SeverityInfo,
		Description: `Rule state transition (write-on-change pattern)`,
		ActorTypes:  nil,
	},
	FindingPersisted: {
		Code:        FindingPersisted,
		Category:    "finding",
		Severity:    SeverityInfo,
		Description: `A single rule finding was persisted to the transaction log (one per transactions row insert). Spec system-transaction-log-writer AC-09.`,
		ActorTypes:  []string{"system"},
	},
	WriterApplyFailed: {
		Code:        WriterApplyFailed,
		Category:    "writer",
		Severity:    SeverityError,
		Description: `writer.Apply rolled back the entire batch due to a DB error (FK violation, deadlock, oversize evidence). Spec system-transaction-log-writer AC-15.`,
		ActorTypes:  []string{"system"},
	},
	ComplianceExceptionRequested: {
		Code:        ComplianceExceptionRequested,
		Category:    "compliance",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceExceptionApproved: {
		Code:        ComplianceExceptionApproved,
		Category:    "compliance",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceExceptionRejected: {
		Code:        ComplianceExceptionRejected,
		Category:    "compliance",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceExceptionRevoked: {
		Code:        ComplianceExceptionRevoked,
		Category:    "compliance",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceExceptionExpired: {
		Code:        ComplianceExceptionExpired,
		Category:    "compliance",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceBaselineEstablished: {
		Code:        ComplianceBaselineEstablished,
		Category:    "compliance",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceBaselineCleared: {
		Code:        ComplianceBaselineCleared,
		Category:    "compliance",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceDriftDetected: {
		Code:        ComplianceDriftDetected,
		Category:    "compliance",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	ComplianceSnapshotCreated: {
		Code:        ComplianceSnapshotCreated,
		Category:    "compliance",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	AlertCreated: {
		Code:        AlertCreated,
		Category:    "alert",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	AlertAcknowledged: {
		Code:        AlertAcknowledged,
		Category:    "alert",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	AlertResolved: {
		Code:        AlertResolved,
		Category:    "alert",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	AlertThresholdChanged: {
		Code:        AlertThresholdChanged,
		Category:    "alert",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	NotificationDispatched: {
		Code:        NotificationDispatched,
		Category:    "notification",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	NotificationDeliveryFailed: {
		Code:        NotificationDeliveryFailed,
		Category:    "notification",
		Severity:    SeverityError,
		Description: ``,
		ActorTypes:  nil,
	},
	NotificationDeliverySucceeded: {
		Code:        NotificationDeliverySucceeded,
		Category:    "notification",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	NotificationChannelCreated: {
		Code:        NotificationChannelCreated,
		Category:    "notification",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	NotificationChannelUpdated: {
		Code:        NotificationChannelUpdated,
		Category:    "notification",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	NotificationChannelDeleted: {
		Code:        NotificationChannelDeleted,
		Category:    "notification",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseInstalled: {
		Code:        LicenseInstalled,
		Category:    "license",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseInvalid: {
		Code:        LicenseInvalid,
		Category:    "license",
		Severity:    SeverityError,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseExpiringSoon: {
		Code:        LicenseExpiringSoon,
		Category:    "license",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseExpired: {
		Code:        LicenseExpired,
		Category:    "license",
		Severity:    SeverityError,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseFeatureCheckDenied: {
		Code:        LicenseFeatureCheckDenied,
		Category:    "license",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseQuotaExceeded: {
		Code:        LicenseQuotaExceeded,
		Category:    "license",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseClockRollbackDetected: {
		Code:        LicenseClockRollbackDetected,
		Category:    "license",
		Severity:    SeverityCritical,
		Description: ``,
		ActorTypes:  nil,
	},
	LicenseTampered: {
		Code:        LicenseTampered,
		Category:    "license",
		Severity:    SeverityCritical,
		Description: ``,
		ActorTypes:  nil,
	},
	PolicyLoaded: {
		Code:        PolicyLoaded,
		Category:    "policy",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	PolicyInvalid: {
		Code:        PolicyInvalid,
		Category:    "policy",
		Severity:    SeverityError,
		Description: ``,
		ActorTypes:  nil,
	},
	PolicyApplied: {
		Code:        PolicyApplied,
		Category:    "policy",
		Severity:    SeverityInfo,
		Description: `Operation evaluated against a versioned policy`,
		ActorTypes:  nil,
	},
	RemediationRequested: {
		Code:        RemediationRequested,
		Category:    "remediation",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	RemediationApproved: {
		Code:        RemediationApproved,
		Category:    "remediation",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	RemediationExecuted: {
		Code:        RemediationExecuted,
		Category:    "remediation",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	RemediationRolledBack: {
		Code:        RemediationRolledBack,
		Category:    "remediation",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	IntegrationWebhookDelivered: {
		Code:        IntegrationWebhookDelivered,
		Category:    "integration",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	IntegrationWebhookFailed: {
		Code:        IntegrationWebhookFailed,
		Category:    "integration",
		Severity:    SeverityError,
		Description: ``,
		ActorTypes:  nil,
	},
	IntegrationWebhookSubscribed: {
		Code:        IntegrationWebhookSubscribed,
		Category:    "integration",
		Severity:    SeverityInfo,
		Description: `External subscriber registered for event delivery`,
		ActorTypes:  nil,
	},
	IntegrationWebhookUnsubscribed: {
		Code:        IntegrationWebhookUnsubscribed,
		Category:    "integration",
		Severity:    SeverityWarning,
		Description: `Webhook subscription deleted; no further deliveries`,
		ActorTypes:  nil,
	},
	IntegrationPluginInstalled: {
		Code:        IntegrationPluginInstalled,
		Category:    "integration",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	IntegrationPluginExecuted: {
		Code:        IntegrationPluginExecuted,
		Category:    "integration",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	SystemStartup: {
		Code:        SystemStartup,
		Category:    "system",
		Severity:    SeverityInfo,
		Description: `Service has booted and is accepting requests`,
		ActorTypes:  []string{"system"},
	},
	SystemShutdown: {
		Code:        SystemShutdown,
		Category:    "system",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  []string{"system"},
	},
	SystemConfigChanged: {
		Code:        SystemConfigChanged,
		Category:    "system",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	SystemMigrationApplied: {
		Code:        SystemMigrationApplied,
		Category:    "system",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	SystemHealthDegraded: {
		Code:        SystemHealthDegraded,
		Category:    "system",
		Severity:    SeverityError,
		Description: ``,
		ActorTypes:  nil,
	},
	SystemHealthRecovered: {
		Code:        SystemHealthRecovered,
		Category:    "system",
		Severity:    SeverityInfo,
		Description: ``,
		ActorTypes:  nil,
	},
	SchedulerStartupFailed: {
		Code:        SchedulerStartupFailed,
		Category:    "scheduler",
		Severity:    SeverityError,
		Description: `Scheduler refused to start because the schedules policy was missing or failed Ed25519 verification`,
		ActorTypes:  []string{"system"},
	},
	SchedulerScheduleUpdated: {
		Code:        SchedulerScheduleUpdated,
		Category:    "scheduler",
		Severity:    SeverityInfo,
		Description: `A row in host_compliance_schedule was updated (next_scheduled_scan, maintenance_mode, or manual override)`,
		ActorTypes:  []string{"system", "user"},
	},
	SchedulerPolicyReloadRejected: {
		Code:        SchedulerPolicyReloadRejected,
		Category:    "scheduler",
		Severity:    SeverityError,
		Description: `Runtime policy reload was rejected; the previous valid policy remains active`,
		ActorTypes:  []string{"system"},
	},
	SchedulerPolicyClamped: {
		Code:        SchedulerPolicyClamped,
		Category:    "scheduler",
		Severity:    SeverityWarning,
		Description: `A tier interval in the schedules policy was clamped to the safety floor (5 min) or ceiling (48 h)`,
		ActorTypes:  []string{"system"},
	},
	SchedulerPolicyRevokedKeyRejected: {
		Code:        SchedulerPolicyRevokedKeyRejected,
		Category:    "scheduler",
		Severity:    SeverityError,
		Description: `A schedules policy was signed by a previously-rotated (revoked) signing key and rejected even though the Ed25519 signature was mathematically valid`,
		ActorTypes:  []string{"system"},
	},
	SchedulerJobHmacRejected: {
		Code:        SchedulerJobHmacRejected,
		Category:    "scheduler",
		Severity:    SeverityError,
		Description: `A dequeued scan job failed HMAC verification; the job payload was tampered after enqueue`,
		ActorTypes:  []string{"system"},
	},
	SchedulerTickDispatched: {
		Code:        SchedulerTickDispatched,
		Category:    "scheduler",
		Severity:    SeverityInfo,
		Description: `Scheduler tick dispatched zero or more scan jobs to the queue`,
		ActorTypes:  []string{"system"},
	},
	WorkerLoopTick: {
		Code:        WorkerLoopTick,
		Category:    "worker",
		Severity:    SeverityInfo,
		Description: `Periodic heartbeat from openwatch worker — at 55..65s intervals (60s nominal with jitter)`,
		ActorTypes:  []string{"system"},
	},
	AdminUserCreated: {
		Code:        AdminUserCreated,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	AdminUserUpdated: {
		Code:        AdminUserUpdated,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	AdminUserDeleted: {
		Code:        AdminUserDeleted,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	AdminRoleChanged: {
		Code:        AdminRoleChanged,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	AdminSystemSettingChanged: {
		Code:        AdminSystemSettingChanged,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	AdminRetentionPolicyChanged: {
		Code:        AdminRetentionPolicyChanged,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	AdminSsoProviderCreated: {
		Code:        AdminSsoProviderCreated,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	AdminSsoProviderUpdated: {
		Code:        AdminSsoProviderUpdated,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: `SSO provider config changed (enable/disable, secret rotation, metadata refresh)`,
		ActorTypes:  nil,
	},
	AdminSsoProviderDeleted: {
		Code:        AdminSsoProviderDeleted,
		Category:    "admin",
		Severity:    SeverityWarning,
		Description: ``,
		ActorTypes:  nil,
	},
	DiagnosticsTestJobCompleted: {
		Code:        DiagnosticsTestJobCompleted,
		Category:    "diagnostics",
		Severity:    SeverityInfo,
		Description: `Worker drained a diagnostics.test_job and emitted this completion event`,
		ActorTypes:  []string{"system"},
	},
}

// AllCodes returns every active event code in declaration order.
func AllCodes() []Code {
	out := make([]Code, 0, len(codeOrder))
	out = append(out, codeOrder...)
	return out
}

var codeOrder = []Code{
	AuthLoginSuccess,
	AuthLoginFailure,
	AuthLogout,
	AuthTokenIssued,
	AuthTokenRefreshed,
	AuthTokenRevoked,
	AuthMfaEnrolled,
	AuthMfaValidated,
	AuthMfaFailed,
	AuthMfaDisabled,
	AuthSessionCreated,
	AuthSessionExpired,
	AuthSessionRevoked,
	AuthPasswordChanged,
	AuthPasswordPolicyFailed,
	AuthApiKeyCreated,
	AuthApiKeyRevoked,
	AuthzPermissionDenied,
	AuthzRoleAssigned,
	AuthzRoleRemoved,
	HostCreated,
	HostUpdated,
	HostDeleted,
	HostConnectivityChecked,
	HostPlatformDetected,
	HostIntelligenceRefreshed,
	HostBulkImported,
	CredentialCreated,
	CredentialDeleted,
	ScanQueued,
	ScanStarted,
	ScanCompleted,
	ScanFailed,
	ScanCancelled,
	ScanSessionCreated,
	ScanSessionCancelled,
	ScanTemplateCreated,
	ScanTemplateUpdated,
	ScanTemplateDeleted,
	ComplianceStateChanged,
	FindingPersisted,
	WriterApplyFailed,
	ComplianceExceptionRequested,
	ComplianceExceptionApproved,
	ComplianceExceptionRejected,
	ComplianceExceptionRevoked,
	ComplianceExceptionExpired,
	ComplianceBaselineEstablished,
	ComplianceBaselineCleared,
	ComplianceDriftDetected,
	ComplianceSnapshotCreated,
	AlertCreated,
	AlertAcknowledged,
	AlertResolved,
	AlertThresholdChanged,
	NotificationDispatched,
	NotificationDeliveryFailed,
	NotificationDeliverySucceeded,
	NotificationChannelCreated,
	NotificationChannelUpdated,
	NotificationChannelDeleted,
	LicenseInstalled,
	LicenseInvalid,
	LicenseExpiringSoon,
	LicenseExpired,
	LicenseFeatureCheckDenied,
	LicenseQuotaExceeded,
	LicenseClockRollbackDetected,
	LicenseTampered,
	PolicyLoaded,
	PolicyInvalid,
	PolicyApplied,
	RemediationRequested,
	RemediationApproved,
	RemediationExecuted,
	RemediationRolledBack,
	IntegrationWebhookDelivered,
	IntegrationWebhookFailed,
	IntegrationWebhookSubscribed,
	IntegrationWebhookUnsubscribed,
	IntegrationPluginInstalled,
	IntegrationPluginExecuted,
	SystemStartup,
	SystemShutdown,
	SystemConfigChanged,
	SystemMigrationApplied,
	SystemHealthDegraded,
	SystemHealthRecovered,
	SchedulerStartupFailed,
	SchedulerScheduleUpdated,
	SchedulerPolicyReloadRejected,
	SchedulerPolicyClamped,
	SchedulerPolicyRevokedKeyRejected,
	SchedulerJobHmacRejected,
	SchedulerTickDispatched,
	WorkerLoopTick,
	AdminUserCreated,
	AdminUserUpdated,
	AdminUserDeleted,
	AdminRoleChanged,
	AdminSystemSettingChanged,
	AdminRetentionPolicyChanged,
	AdminSsoProviderCreated,
	AdminSsoProviderUpdated,
	AdminSsoProviderDeleted,
	DiagnosticsTestJobCompleted,
}
