name: 🔒 Security Vulnerability
description: Report a security vulnerability (Use GitHub Security Advisories for private reporting)
title: "[Security]: "
labels: ["security", "critical"]
assignees: ["security-team"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: For sensitive security issues, please use [GitHub Security Advisories](https://github.com/Hanalyx/OpenWatch/security/advisories) 
        to report vulnerabilities privately. Only use this template for non-sensitive security improvements.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Security Disclosure Agreement
      options:
        - label: I understand this is a public issue and will not disclose sensitive details
          required: true
        - label: I have not disclosed this vulnerability publicly elsewhere
          required: true
        - label: I will wait for a fix before public disclosure (responsible disclosure)
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication Bypass
        - Authorization Issue
        - Injection (SQL, Command, etc.)
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Insecure Direct Object Reference
        - Information Disclosure
        - Cryptographic Issue
        - Configuration Issue
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: Your assessment of the vulnerability severity
      options:
        - Critical (Immediate action required)
        - High (Significant risk)
        - Medium (Moderate risk)
        - Low (Minor risk)
        - Informational (No immediate risk)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: High-level description of the vulnerability (avoid sensitive details)
      placeholder: |
        Provide a brief, non-sensitive description of the security issue.
        Do not include exploits, sensitive URLs, or detailed attack vectors.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially achieve?
      placeholder: |
        Describe the potential impact if this vulnerability were exploited.
        What data or systems could be affected?
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of OpenWatch are affected?
      placeholder: |
        - Version X.X.X
        - All versions since X.X.X
        - Latest version
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions for fixing this issue
      placeholder: |
        Any recommendations for addressing this vulnerability?
        Please avoid detailed exploit information.

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
      placeholder: |
        Any additional context that might help understand or address this issue?
        Please keep sensitive details private.