// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CredentialCreateRequestAuthMethod.
const (
	CredentialCreateRequestAuthMethodBoth     CredentialCreateRequestAuthMethod = "both"
	CredentialCreateRequestAuthMethodPassword CredentialCreateRequestAuthMethod = "password"
	CredentialCreateRequestAuthMethodSshKey   CredentialCreateRequestAuthMethod = "ssh_key"
)

// Valid indicates whether the value is a known member of the CredentialCreateRequestAuthMethod enum.
func (e CredentialCreateRequestAuthMethod) Valid() bool {
	switch e {
	case CredentialCreateRequestAuthMethodBoth:
		return true
	case CredentialCreateRequestAuthMethodPassword:
		return true
	case CredentialCreateRequestAuthMethodSshKey:
		return true
	default:
		return false
	}
}

// Defines values for CredentialCreateRequestScope.
const (
	CredentialCreateRequestScopeHost   CredentialCreateRequestScope = "host"
	CredentialCreateRequestScopeSystem CredentialCreateRequestScope = "system"
)

// Valid indicates whether the value is a known member of the CredentialCreateRequestScope enum.
func (e CredentialCreateRequestScope) Valid() bool {
	switch e {
	case CredentialCreateRequestScopeHost:
		return true
	case CredentialCreateRequestScopeSystem:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResponseAuthMethod.
const (
	CredentialResponseAuthMethodBoth     CredentialResponseAuthMethod = "both"
	CredentialResponseAuthMethodPassword CredentialResponseAuthMethod = "password"
	CredentialResponseAuthMethodSshKey   CredentialResponseAuthMethod = "ssh_key"
)

// Valid indicates whether the value is a known member of the CredentialResponseAuthMethod enum.
func (e CredentialResponseAuthMethod) Valid() bool {
	switch e {
	case CredentialResponseAuthMethodBoth:
		return true
	case CredentialResponseAuthMethodPassword:
		return true
	case CredentialResponseAuthMethodSshKey:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResponseScope.
const (
	CredentialResponseScopeHost   CredentialResponseScope = "host"
	CredentialResponseScopeSystem CredentialResponseScope = "system"
)

// Valid indicates whether the value is a known member of the CredentialResponseScope enum.
func (e CredentialResponseScope) Valid() bool {
	switch e {
	case CredentialResponseScopeHost:
		return true
	case CredentialResponseScopeSystem:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeErrorFault.
const (
	Client   ErrorEnvelopeErrorFault = "client"
	External ErrorEnvelopeErrorFault = "external"
	Policy   ErrorEnvelopeErrorFault = "policy"
	Server   ErrorEnvelopeErrorFault = "server"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorFault enum.
func (e ErrorEnvelopeErrorFault) Valid() bool {
	switch e {
	case Client:
		return true
	case External:
		return true
	case Policy:
		return true
	case Server:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Healthy  HealthResponseStatus = "healthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Healthy:
		return true
	default:
		return false
	}
}

// Defines values for LicenseStateResponseStatus.
const (
	Active    LicenseStateResponseStatus = "active"
	Expired   LicenseStateResponseStatus = "expired"
	Grace     LicenseStateResponseStatus = "grace"
	Invalid   LicenseStateResponseStatus = "invalid"
	NoLicense LicenseStateResponseStatus = "no_license"
)

// Valid indicates whether the value is a known member of the LicenseStateResponseStatus enum.
func (e LicenseStateResponseStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Expired:
		return true
	case Grace:
		return true
	case Invalid:
		return true
	case NoLicense:
		return true
	default:
		return false
	}
}

// Defines values for LicenseStateResponseTier.
const (
	Enterprise    LicenseStateResponseTier = "enterprise"
	Free          LicenseStateResponseTier = "free"
	OpenwatchPlus LicenseStateResponseTier = "openwatch_plus"
)

// Valid indicates whether the value is a known member of the LicenseStateResponseTier enum.
func (e LicenseStateResponseTier) Valid() bool {
	switch e {
	case Enterprise:
		return true
	case Free:
		return true
	case OpenwatchPlus:
		return true
	default:
		return false
	}
}

// AdminRolesResponse defines model for AdminRolesResponse.
type AdminRolesResponse struct {
	Roles []RoleEntry `json:"roles"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action        string                  `json:"action"`
	ActorId       *string                 `json:"actor_id,omitempty"`
	ActorType     string                  `json:"actor_type"`
	CorrelationId string                  `json:"correlation_id"`
	Detail        *map[string]interface{} `json:"detail,omitempty"`
	Id            openapi_types.UUID      `json:"id"`
	OccurredAt    time.Time               `json:"occurred_at"`
	RecordedAt    *time.Time              `json:"recorded_at,omitempty"`
	Redactions    *[]string               `json:"redactions,omitempty"`
	ResourceId    *string                 `json:"resource_id,omitempty"`
	ResourceType  *string                 `json:"resource_type,omitempty"`
	Severity      *string                 `json:"severity,omitempty"`
}

// AuditEventsPage defines model for AuditEventsPage.
type AuditEventsPage struct {
	Items []AuditEvent `json:"items"`

	// NextCursor Opaque cursor; pass as ?cursor= to fetch the next page
	NextCursor *string `json:"next_cursor"`
}

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Otp      *string `json:"otp,omitempty"`
	Password string  `json:"password"`
	Username string  `json:"username"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	User         AuthMeResponse `json:"user"`
}

// AuthMFAEnrollResponse defines model for AuthMFAEnrollResponse.
type AuthMFAEnrollResponse struct {
	ProvisioningUri string `json:"provisioning_uri"`
}

// AuthMFAVerifyRequest defines model for AuthMFAVerifyRequest.
type AuthMFAVerifyRequest struct {
	Otp string `json:"otp"`
}

// AuthMePermissionsResponse defines model for AuthMePermissionsResponse.
type AuthMePermissionsResponse struct {
	Identity struct {
		Id          string `json:"id"`
		IsAnonymous bool   `json:"is_anonymous"`
		Role        string `json:"role"`
	} `json:"identity"`
	Permissions []string `json:"permissions"`
}

// AuthMeResponse defines model for AuthMeResponse.
type AuthMeResponse struct {
	Email    string             `json:"email"`
	Id       openapi_types.UUID `json:"id"`
	Role     string             `json:"role"`
	Username string             `json:"username"`
}

// AuthPasswordChangeRequest defines model for AuthPasswordChangeRequest.
type AuthPasswordChangeRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// CategoryEntry defines model for CategoryEntry.
type CategoryEntry struct {
	Description string `json:"description"`
	Id          string `json:"id"`
}

// CredentialCreateRequest defines model for CredentialCreateRequest.
type CredentialCreateRequest struct {
	AuthMethod           CredentialCreateRequestAuthMethod `json:"auth_method"`
	Description          *string                           `json:"description,omitempty"`
	IsDefault            *bool                             `json:"is_default,omitempty"`
	Name                 string                            `json:"name"`
	Password             *string                           `json:"password,omitempty"`
	PrivateKey           *string                           `json:"private_key,omitempty"`
	PrivateKeyPassphrase *string                           `json:"private_key_passphrase,omitempty"`
	Scope                CredentialCreateRequestScope      `json:"scope"`
	ScopeId              *openapi_types.UUID               `json:"scope_id,omitempty"`
	Username             string                            `json:"username"`
}

// CredentialCreateRequestAuthMethod defines model for CredentialCreateRequest.AuthMethod.
type CredentialCreateRequestAuthMethod string

// CredentialCreateRequestScope defines model for CredentialCreateRequest.Scope.
type CredentialCreateRequestScope string

// CredentialListResponse defines model for CredentialListResponse.
type CredentialListResponse struct {
	Credentials []CredentialResponse `json:"credentials"`
}

// CredentialResponse defines model for CredentialResponse.
type CredentialResponse struct {
	AuthMethod        CredentialResponseAuthMethod `json:"auth_method"`
	CreatedAt         *time.Time                   `json:"created_at,omitempty"`
	CreatedBy         *openapi_types.UUID          `json:"created_by,omitempty"`
	Description       *string                      `json:"description,omitempty"`
	Id                openapi_types.UUID           `json:"id"`
	IsActive          bool                         `json:"is_active"`
	IsDefault         bool                         `json:"is_default"`
	Name              string                       `json:"name"`
	Scope             CredentialResponseScope      `json:"scope"`
	ScopeId           *openapi_types.UUID          `json:"scope_id,omitempty"`
	SshKeyBits        *int                         `json:"ssh_key_bits,omitempty"`
	SshKeyComment     *string                      `json:"ssh_key_comment,omitempty"`
	SshKeyFingerprint *string                      `json:"ssh_key_fingerprint,omitempty"`
	SshKeyType        *string                      `json:"ssh_key_type,omitempty"`
	UpdatedAt         *time.Time                   `json:"updated_at,omitempty"`
	Username          string                       `json:"username"`
}

// CredentialResponseAuthMethod defines model for CredentialResponse.AuthMethod.
type CredentialResponseAuthMethod string

// CredentialResponseScope defines model for CredentialResponse.Scope.
type CredentialResponseScope string

// CustomRoleCreateRequest defines model for CustomRoleCreateRequest.
type CustomRoleCreateRequest struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	Permissions []string `json:"permissions"`
}

// CustomRoleResponse defines model for CustomRoleResponse.
type CustomRoleResponse struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	IsBuiltIn   bool     `json:"is_built_in"`
	Permissions []string `json:"permissions"`
}

// EchoRequest defines model for EchoRequest.
type EchoRequest struct {
	Message string `json:"message"`
}

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	AuditEventId  *openapi_types.UUID `json:"audit_event_id,omitempty"`
	CorrelationId string              `json:"correlation_id"`
	Echoed        string              `json:"echoed"`
}

// EnqueueTestJobResponse defines model for EnqueueTestJobResponse.
type EnqueueTestJobResponse struct {
	CorrelationId string             `json:"correlation_id"`
	JobId         openapi_types.UUID `json:"job_id"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code          string                  `json:"code"`
		CorrelationId *string                 `json:"correlation_id,omitempty"`
		Detail        *map[string]interface{} `json:"detail,omitempty"`
		Fault         ErrorEnvelopeErrorFault `json:"fault"`
		HumanMessage  string                  `json:"human_message"`
		Retryable     bool                    `json:"retryable"`
	} `json:"error"`
}

// ErrorEnvelopeErrorFault defines model for ErrorEnvelope.Error.Fault.
type ErrorEnvelopeErrorFault string

// EvaluateAlertRequest defines model for EvaluateAlertRequest.
type EvaluateAlertRequest struct {
	Score int `json:"score"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	DbConnected bool                 `json:"db_connected"`
	Status      HealthResponseStatus `json:"status"`
	Version     string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HostCreateRequest defines model for HostCreateRequest.
type HostCreateRequest struct {
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment *string             `json:"environment,omitempty"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	Hostname    string              `json:"hostname"`
	IpAddress   string              `json:"ip_address"`
	Port        *int                `json:"port,omitempty"`
	Tags        *[]string           `json:"tags,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// HostListResponse defines model for HostListResponse.
type HostListResponse struct {
	Hosts []HostResponse `json:"hosts"`
}

// HostResponse defines model for HostResponse.
type HostResponse struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	CreatedBy   *openapi_types.UUID `json:"created_by,omitempty"`
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment string              `json:"environment"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	Hostname    string              `json:"hostname"`
	Id          openapi_types.UUID  `json:"id"`
	IpAddress   string              `json:"ip_address"`
	Port        int                 `json:"port"`
	Tags        *[]string           `json:"tags,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// HostUpdateRequest defines model for HostUpdateRequest.
type HostUpdateRequest struct {
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment *string             `json:"environment,omitempty"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	IpAddress   *string             `json:"ip_address,omitempty"`
	Port        *int                `json:"port,omitempty"`
	Tags        *[]string           `json:"tags,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// LicenseStateResponse defines model for LicenseStateResponse.
type LicenseStateResponse struct {
	CustomerId    *string                    `json:"customer_id,omitempty"`
	ExpiresAt     *time.Time                 `json:"expires_at,omitempty"`
	Features      []string                   `json:"features"`
	InGracePeriod *bool                      `json:"in_grace_period,omitempty"`
	Status        LicenseStateResponseStatus `json:"status"`
	Tier          LicenseStateResponseTier   `json:"tier"`
	UsingPrevKey  *bool                      `json:"using_prev_key,omitempty"`
}

// LicenseStateResponseStatus defines model for LicenseStateResponse.Status.
type LicenseStateResponseStatus string

// LicenseStateResponseTier defines model for LicenseStateResponse.Tier.
type LicenseStateResponseTier string

// LicenseVerifyRequest defines model for LicenseVerifyRequest.
type LicenseVerifyRequest struct {
	LicenseJwt string `json:"license_jwt"`
}

// LicenseVerifyResponse defines model for LicenseVerifyResponse.
type LicenseVerifyResponse struct {
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	Features     *[]string  `json:"features,omitempty"`
	IsValid      bool       `json:"is_valid"`
	Tier         *string    `json:"tier,omitempty"`
	VerifyResult string     `json:"verify_result"`
	Warnings     *[]string  `json:"warnings,omitempty"`
}

// PermissionEntry defines model for PermissionEntry.
type PermissionEntry struct {
	Category     string  `json:"category"`
	Dangerous    bool    `json:"dangerous"`
	Description  string  `json:"description"`
	Id           string  `json:"id"`
	LicenseGated *string `json:"license_gated,omitempty"`
}

// PermissionsRegistryResponse defines model for PermissionsRegistryResponse.
type PermissionsRegistryResponse struct {
	Categories  []CategoryEntry   `json:"categories"`
	Permissions []PermissionEntry `json:"permissions"`
	Roles       []RoleEntry       `json:"roles"`
}

// PoliciesReloadResponse defines model for PoliciesReloadResponse.
type PoliciesReloadResponse struct {
	Outcomes map[string]string `json:"outcomes"`
}

// PolicyDecisionResponse defines model for PolicyDecisionResponse.
type PolicyDecisionResponse struct {
	Detail        *map[string]interface{} `json:"detail,omitempty"`
	HumanMessage  *string                 `json:"human_message,omitempty"`
	Outcome       string                  `json:"outcome"`
	PolicyType    string                  `json:"policy_type"`
	PolicyVersion string                  `json:"policy_version"`
	Reason        string                  `json:"reason"`
}

// RoleEntry defines model for RoleEntry.
type RoleEntry struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	IsBuiltIn   bool     `json:"is_built_in"`
	Permissions []string `json:"permissions"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt            *time.Time         `json:"created_at,omitempty"`
	Email                string             `json:"email"`
	Id                   openapi_types.UUID `json:"id"`
	LastPasswordChangeAt *time.Time         `json:"last_password_change_at,omitempty"`
	UpdatedAt            *time.Time         `json:"updated_at,omitempty"`
	Username             string             `json:"username"`
}

// UserRoleAssignRequest defines model for UserRoleAssignRequest.
type UserRoleAssignRequest struct {
	RoleId string `json:"role_id"`
}

// UsersListResponse defines model for UsersListResponse.
type UsersListResponse struct {
	Users []UserResponse `json:"users"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorEnvelope

// GetAuditEventsParams defines parameters for GetAuditEvents.
type GetAuditEventsParams struct {
	Action        *string    `form:"action,omitempty" json:"action,omitempty"`
	CorrelationId *string    `form:"correlation_id,omitempty" json:"correlation_id,omitempty"`
	ActorType     *string    `form:"actor_type,omitempty" json:"actor_type,omitempty"`
	Since         *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Until         *time.Time `form:"until,omitempty" json:"until,omitempty"`
	Cursor        *string    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostDiagnosticsEchoParams defines parameters for PostDiagnosticsEcho.
type PostDiagnosticsEchoParams struct {
	IdempotencyKey string  `json:"Idempotency-Key"`
	XCorrelationId *string `json:"X-Correlation-Id,omitempty"`
}

// PostDiagnosticsPremiumEchoParams defines parameters for PostDiagnosticsPremiumEcho.
type PostDiagnosticsPremiumEchoParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireHostReadParams defines parameters for PostDiagnosticsRequireHostRead.
type PostDiagnosticsRequireHostReadParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireHostWriteParams defines parameters for PostDiagnosticsRequireHostWrite.
type PostDiagnosticsRequireHostWriteParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireRemediationExecuteParams defines parameters for PostDiagnosticsRequireRemediationExecute.
type PostDiagnosticsRequireRemediationExecuteParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// GetHostsParams defines parameters for GetHosts.
type GetHostsParams struct {
	Environment *string `form:"environment,omitempty" json:"environment,omitempty"`
	Tag         *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// PostAdminLicenseVerifyJSONRequestBody defines body for PostAdminLicenseVerify for application/json ContentType.
type PostAdminLicenseVerifyJSONRequestBody = LicenseVerifyRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthLoginRequest

// PostAuthMFAVerifyJSONRequestBody defines body for PostAuthMFAVerify for application/json ContentType.
type PostAuthMFAVerifyJSONRequestBody = AuthMFAVerifyRequest

// PostAuthPasswordChangeJSONRequestBody defines body for PostAuthPasswordChange for application/json ContentType.
type PostAuthPasswordChangeJSONRequestBody = AuthPasswordChangeRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = AuthRefreshRequest

// PostCredentialsJSONRequestBody defines body for PostCredentials for application/json ContentType.
type PostCredentialsJSONRequestBody = CredentialCreateRequest

// PostDiagnosticsEchoJSONRequestBody defines body for PostDiagnosticsEcho for application/json ContentType.
type PostDiagnosticsEchoJSONRequestBody = EchoRequest

// PostDiagnosticsEvaluateAlertJSONRequestBody defines body for PostDiagnosticsEvaluateAlert for application/json ContentType.
type PostDiagnosticsEvaluateAlertJSONRequestBody = EvaluateAlertRequest

// PostDiagnosticsPremiumEchoJSONRequestBody defines body for PostDiagnosticsPremiumEcho for application/json ContentType.
type PostDiagnosticsPremiumEchoJSONRequestBody = EchoRequest

// PostDiagnosticsRequireHostReadJSONRequestBody defines body for PostDiagnosticsRequireHostRead for application/json ContentType.
type PostDiagnosticsRequireHostReadJSONRequestBody = EchoRequest

// PostDiagnosticsRequireHostWriteJSONRequestBody defines body for PostDiagnosticsRequireHostWrite for application/json ContentType.
type PostDiagnosticsRequireHostWriteJSONRequestBody = EchoRequest

// PostDiagnosticsRequireRemediationExecuteJSONRequestBody defines body for PostDiagnosticsRequireRemediationExecute for application/json ContentType.
type PostDiagnosticsRequireRemediationExecuteJSONRequestBody = EchoRequest

// PostHostsJSONRequestBody defines body for PostHosts for application/json ContentType.
type PostHostsJSONRequestBody = HostCreateRequest

// PatchHostByIDJSONRequestBody defines body for PatchHostByID for application/json ContentType.
type PatchHostByIDJSONRequestBody = HostUpdateRequest

// PostRolesCreateJSONRequestBody defines body for PostRolesCreate for application/json ContentType.
type PostRolesCreateJSONRequestBody = CustomRoleCreateRequest

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreateRequest

// PostUserRolesAssignJSONRequestBody defines body for PostUserRolesAssign for application/json ContentType.
type PostUserRolesAssignJSONRequestBody = UserRoleAssignRequest

// PostUserRolesUnassignJSONRequestBody defines body for PostUserRolesUnassign for application/json ContentType.
type PostUserRolesUnassignJSONRequestBody = UserRoleAssignRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Dry-run validate a JWT license without installing it
	// (POST /api/v1/admin/license:verify)
	PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request)
	// Reload signed policy files from the configured directory
	// (POST /api/v1/admin/policies:reload)
	PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request)
	// List audit events (cursor-paginated, newest first)
	// (GET /api/v1/audit/events)
	GetAuditEvents(w http.ResponseWriter, r *http.Request, params GetAuditEventsParams)
	// Username/password login with optional TOTP
	// (POST /api/v1/auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Revoke the calling session
	// (POST /api/v1/auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Return the calling identity
	// (GET /api/v1/auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Effective permissions for the calling identity
	// (GET /api/v1/auth/me/permissions)
	GetAuthMePermissions(w http.ResponseWriter, r *http.Request)
	// Enroll the calling user in TOTP MFA
	// (POST /api/v1/auth/mfa:enroll)
	PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request)
	// Confirm an enrolled MFA secret by verifying a generated OTP
	// (POST /api/v1/auth/mfa:verify)
	PostAuthMFAVerify(w http.ResponseWriter, r *http.Request)
	// Change the calling user's password
	// (POST /api/v1/auth/password:change)
	PostAuthPasswordChange(w http.ResponseWriter, r *http.Request)
	// Full RBAC registry (categories, permissions, built-in roles)
	// (GET /api/v1/auth/permissions:registry)
	GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request)
	// Rotate the refresh token; mint a new access+refresh pair
	// (POST /api/v1/auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// List credentials (metadata only)
	// (GET /api/v1/credentials)
	GetCredentials(w http.ResponseWriter, r *http.Request)
	// Create a credential
	// (POST /api/v1/credentials)
	PostCredentials(w http.ResponseWriter, r *http.Request)
	// Soft-delete a credential
	// (DELETE /api/v1/credentials/{id})
	DeleteCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a credential's metadata
	// (GET /api/v1/credentials/{id})
	GetCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Echo the request message; exercises idempotency + audit
	// (POST /api/v1/diagnostics:echo)
	PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsEchoParams)
	// Stage-0 queue demo; enqueues a no-op job processed by the in-process worker
	// (POST /api/v1/diagnostics:enqueue-test-job)
	PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request)
	// Stage-0 policy demo; evaluates the alert_thresholds policy
	// (POST /api/v1/diagnostics:evaluate-alert)
	PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request)
	// License-gated echo; requires premium_diagnostics feature
	// (POST /api/v1/diagnostics:premium-echo)
	PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsPremiumEchoParams)
	// Stage-0 RBAC demo; requires host:read permission
	// (POST /api/v1/diagnostics:require-host-read)
	PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostReadParams)
	// Stage-0 RBAC demo; requires host:write permission
	// (POST /api/v1/diagnostics:require-host-write)
	PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostWriteParams)
	// Stage-0 RBAC+license demo; requires remediation:execute + remediation_execution feature
	// (POST /api/v1/diagnostics:require-remediation-execute)
	PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireRemediationExecuteParams)
	// Liveness + readiness probe (anonymous)
	// (GET /api/v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List hosts
	// (GET /api/v1/hosts)
	GetHosts(w http.ResponseWriter, r *http.Request, params GetHostsParams)
	// Create a host
	// (POST /api/v1/hosts)
	PostHosts(w http.ResponseWriter, r *http.Request)
	// Resolve the credential that will be used for a host
	// (POST /api/v1/hosts/{host_id}/credentials:resolve)
	PostHostCredentialsResolve(w http.ResponseWriter, r *http.Request, hostId openapi_types.UUID)
	// Soft-delete a host
	// (DELETE /api/v1/hosts/{id})
	DeleteHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a host
	// (GET /api/v1/hosts/{id})
	GetHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update mutable host fields
	// (PATCH /api/v1/hosts/{id})
	PatchHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get the current license state (tier, features, quotas, status)
	// (GET /api/v1/license)
	GetLicense(w http.ResponseWriter, r *http.Request)
	// List built-in roles
	// (GET /api/v1/roles)
	GetRoles(w http.ResponseWriter, r *http.Request)
	// Create a custom role
	// (POST /api/v1/roles:create)
	PostRolesCreate(w http.ResponseWriter, r *http.Request)
	// List users
	// (GET /api/v1/users)
	GetUsers(w http.ResponseWriter, r *http.Request)
	// Create a user
	// (POST /api/v1/users)
	PostUsers(w http.ResponseWriter, r *http.Request)
	// Soft-delete a user
	// (DELETE /api/v1/users/{id})
	DeleteUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a user
	// (GET /api/v1/users/{id})
	GetUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Assign a role to a user
	// (POST /api/v1/users/{id}/roles:assign)
	PostUserRolesAssign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove a role from a user
	// (POST /api/v1/users/{id}/roles:unassign)
	PostUserRolesUnassign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Dry-run validate a JWT license without installing it
// (POST /api/v1/admin/license:verify)
func (_ Unimplemented) PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reload signed policy files from the configured directory
// (POST /api/v1/admin/policies:reload)
func (_ Unimplemented) PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List audit events (cursor-paginated, newest first)
// (GET /api/v1/audit/events)
func (_ Unimplemented) GetAuditEvents(w http.ResponseWriter, r *http.Request, params GetAuditEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Username/password login with optional TOTP
// (POST /api/v1/auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke the calling session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the calling identity
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Effective permissions for the calling identity
// (GET /api/v1/auth/me/permissions)
func (_ Unimplemented) GetAuthMePermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Enroll the calling user in TOTP MFA
// (POST /api/v1/auth/mfa:enroll)
func (_ Unimplemented) PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm an enrolled MFA secret by verifying a generated OTP
// (POST /api/v1/auth/mfa:verify)
func (_ Unimplemented) PostAuthMFAVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change the calling user's password
// (POST /api/v1/auth/password:change)
func (_ Unimplemented) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Full RBAC registry (categories, permissions, built-in roles)
// (GET /api/v1/auth/permissions:registry)
func (_ Unimplemented) GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate the refresh token; mint a new access+refresh pair
// (POST /api/v1/auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List credentials (metadata only)
// (GET /api/v1/credentials)
func (_ Unimplemented) GetCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a credential
// (POST /api/v1/credentials)
func (_ Unimplemented) PostCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a credential
// (DELETE /api/v1/credentials/{id})
func (_ Unimplemented) DeleteCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a credential's metadata
// (GET /api/v1/credentials/{id})
func (_ Unimplemented) GetCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the request message; exercises idempotency + audit
// (POST /api/v1/diagnostics:echo)
func (_ Unimplemented) PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsEchoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 queue demo; enqueues a no-op job processed by the in-process worker
// (POST /api/v1/diagnostics:enqueue-test-job)
func (_ Unimplemented) PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 policy demo; evaluates the alert_thresholds policy
// (POST /api/v1/diagnostics:evaluate-alert)
func (_ Unimplemented) PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// License-gated echo; requires premium_diagnostics feature
// (POST /api/v1/diagnostics:premium-echo)
func (_ Unimplemented) PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsPremiumEchoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC demo; requires host:read permission
// (POST /api/v1/diagnostics:require-host-read)
func (_ Unimplemented) PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostReadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC demo; requires host:write permission
// (POST /api/v1/diagnostics:require-host-write)
func (_ Unimplemented) PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostWriteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC+license demo; requires remediation:execute + remediation_execution feature
// (POST /api/v1/diagnostics:require-remediation-execute)
func (_ Unimplemented) PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireRemediationExecuteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness + readiness probe (anonymous)
// (GET /api/v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List hosts
// (GET /api/v1/hosts)
func (_ Unimplemented) GetHosts(w http.ResponseWriter, r *http.Request, params GetHostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a host
// (POST /api/v1/hosts)
func (_ Unimplemented) PostHosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve the credential that will be used for a host
// (POST /api/v1/hosts/{host_id}/credentials:resolve)
func (_ Unimplemented) PostHostCredentialsResolve(w http.ResponseWriter, r *http.Request, hostId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a host
// (DELETE /api/v1/hosts/{id})
func (_ Unimplemented) DeleteHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a host
// (GET /api/v1/hosts/{id})
func (_ Unimplemented) GetHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update mutable host fields
// (PATCH /api/v1/hosts/{id})
func (_ Unimplemented) PatchHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current license state (tier, features, quotas, status)
// (GET /api/v1/license)
func (_ Unimplemented) GetLicense(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List built-in roles
// (GET /api/v1/roles)
func (_ Unimplemented) GetRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a custom role
// (POST /api/v1/roles:create)
func (_ Unimplemented) PostRolesCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /api/v1/users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a user
// (POST /api/v1/users)
func (_ Unimplemented) PostUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a user
// (DELETE /api/v1/users/{id})
func (_ Unimplemented) DeleteUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a user
// (GET /api/v1/users/{id})
func (_ Unimplemented) GetUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign a role to a user
// (POST /api/v1/users/{id}/roles:assign)
func (_ Unimplemented) PostUserRolesAssign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a role from a user
// (POST /api/v1/users/{id}/roles:unassign)
func (_ Unimplemented) PostUserRolesUnassign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAdminLicenseVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminLicenseVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminPoliciesReload operation middleware
func (siw *ServerInterfaceWrapper) PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminPoliciesReload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditEventsParams

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", r.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "action"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "correlation_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "correlation_id", r.URL.Query(), &params.CorrelationId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "correlation_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "correlation_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "actor_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_type", r.URL.Query(), &params.ActorType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "actor_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "until", r.URL.Query(), &params.Until, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "until"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMePermissions operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMePermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMePermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMFAEnroll operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMFAEnroll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMFAVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMFAVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMFAVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthPasswordChange operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthPasswordChange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthPermissionsRegistry operation middleware
func (siw *ServerInterfaceWrapper) GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthPermissionsRegistry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCredentials operation middleware
func (siw *ServerInterfaceWrapper) PostCredentials(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCredentialByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentialByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCredentialByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCredentialByID operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentialByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEcho operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsEchoParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEcho(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEnqueueTestJob operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEnqueueTestJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEvaluateAlert operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEvaluateAlert(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsPremiumEcho operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsPremiumEchoParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsPremiumEcho(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireHostRead operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireHostReadParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireHostRead(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireHostWrite operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireHostWriteParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireHostWrite(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireRemediationExecute operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireRemediationExecuteParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireRemediationExecute(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHosts operation middleware
func (siw *ServerInterfaceWrapper) GetHosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHostsParams

	// ------------- Optional query parameter "environment" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "environment", r.URL.Query(), &params.Environment, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "environment"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "environment", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHosts operation middleware
func (siw *ServerInterfaceWrapper) PostHosts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHostCredentialsResolve operation middleware
func (siw *ServerInterfaceWrapper) PostHostCredentialsResolve(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "host_id" -------------
	var hostId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "host_id", chi.URLParam(r, "host_id"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "host_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHostCredentialsResolve(w, r, hostId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteHostByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHostByID operation middleware
func (siw *ServerInterfaceWrapper) GetHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchHostByID operation middleware
func (siw *ServerInterfaceWrapper) PatchHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLicense operation middleware
func (siw *ServerInterfaceWrapper) GetLicense(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLicense(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoles operation middleware
func (siw *ServerInterfaceWrapper) GetRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRolesCreate operation middleware
func (siw *ServerInterfaceWrapper) PostRolesCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRolesCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserByID operation middleware
func (siw *ServerInterfaceWrapper) GetUserByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRolesAssign operation middleware
func (siw *ServerInterfaceWrapper) PostUserRolesAssign(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRolesAssign(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRolesUnassign operation middleware
func (siw *ServerInterfaceWrapper) PostUserRolesUnassign(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRolesUnassign(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/license:verify", wrapper.PostAdminLicenseVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/policies:reload", wrapper.PostAdminPoliciesReload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/audit/events", wrapper.GetAuditEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me/permissions", wrapper.GetAuthMePermissions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa:enroll", wrapper.PostAuthMFAEnroll)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa:verify", wrapper.PostAuthMFAVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password:change", wrapper.PostAuthPasswordChange)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/permissions:registry", wrapper.GetAuthPermissionsRegistry)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/credentials", wrapper.GetCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/credentials", wrapper.PostCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/credentials/{id}", wrapper.DeleteCredentialByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/credentials/{id}", wrapper.GetCredentialByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:echo", wrapper.PostDiagnosticsEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:enqueue-test-job", wrapper.PostDiagnosticsEnqueueTestJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:evaluate-alert", wrapper.PostDiagnosticsEvaluateAlert)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:premium-echo", wrapper.PostDiagnosticsPremiumEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-host-read", wrapper.PostDiagnosticsRequireHostRead)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-host-write", wrapper.PostDiagnosticsRequireHostWrite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-remediation-execute", wrapper.PostDiagnosticsRequireRemediationExecute)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/hosts", wrapper.GetHosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/hosts", wrapper.PostHosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/hosts/{host_id}/credentials:resolve", wrapper.PostHostCredentialsResolve)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/hosts/{id}", wrapper.DeleteHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/hosts/{id}", wrapper.GetHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/hosts/{id}", wrapper.PatchHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/license", wrapper.GetLicense)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/roles", wrapper.GetRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/roles:create", wrapper.PostRolesCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users", wrapper.PostUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/users/{id}", wrapper.DeleteUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users/{id}", wrapper.GetUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users/{id}/roles:assign", wrapper.PostUserRolesAssign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users/{id}/roles:unassign", wrapper.PostUserRolesUnassign)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F17bxs5kv8qRN8Ca2NasZzHYFfB4pBJMpvMJTOGk+wcMJsTqO6SxLib7JBsObrAwH2I+4T3SQ589Jvs",
	"bnksybMz/yS2xEex6sd6sUh/DSKWZowClSKYfQ04iIxRAfqX73B8CZ9zEFL9FjEqgeofcZYlJMKSMHr2",
	"STCqPhPRGlKsfvoTh2UwC/7trBr6zHwrzl5yzvhLuoGEZRDc3NyEQQwi4iRTgwWz4B84IbEeOUQZXhFq",
	"f2YckRjSjEmg0RaBGie4CYO3INcs/pHJZ0nCriE+HKU/c0ZX6NX79xco1UQEqo3trkZ/FqeEXrIExKXl",
	"qvo04ywDLolhMVdfqx+IhFQM0aQGe0kl36qVy20GwSzAnOOtnprD55xwxYJf7Lgfy1Zs8Qkiqbo9y2Mi",
	"X24sf5rU4Mis7WvRTUhO6Ep1w5FkfE40f2meJHiRQDCTPIfQ19h87BgrYpxDooViR+w0iUFikmia4pio",
	"lji5qNHamLhanBltyXiKZTAL8pzEgYM+FkU55xDPsWy0j7GEiSQpuDpxiBiPd+4UG6Y2hdxp1xSm6idY",
	"ziMYy/GyfcH0wR4CNsCJ3DrIaWFJ87Als7DASkPYTc72o09c4JVjQ5QsGrUhamB2MJHCFzmPci4YVwM1",
	"t+9PGf6cAzJfP0UZFgJhgf7dfPA3JBlagozWSK4BqZGUOlJLHOBsm3l6GU1a3IyR6zdsRWhN4zY5w2Sm",
	"/kvxlzdAV3IdzL4Ng5TQ2m8dIatVXTMetzo+fNLseu7omgvgFKewc9cWA8pxatQMMMCnLHEUgRBzya7A",
	"raQ4LDmIdU8LRc0wqOT6LZRktBfUoKI9p53Bt8C33z97STlLEv8iM842RBBGCV3Nc06G92enR8/s/wBO",
	"lts7xFiLFjWAd3q4AJ4SoUjtMYkkBiqtYmp/45QpEXNMGd2mLK8r1wVjCWCqccESGKnndNPWmK4FZdVS",
	"dtHsnSntWpsD+jnoZxuk1mB2+TPOKHqY1NQEIzhY2/CGJju0b1EXVis8X2O6Ai80tV2hct5Qaf0qjML1",
	"+OatpXSmaw3nW82lUQfeZQypqLYf12jumvQ5lrBifGv8ws58DaPnBccIsdYHctLBQYMZJ885YOkXJM7l",
	"em49ZoVbmqdqEiHW8yvY1s1EGCyYXNdmq/uHjWXVFNb59OHj0KkkYljiPJFuFXErU9c0sN0vOdlgCXpZ",
	"A99rYGVrjoV7D4qIGb+uZNdWSEiDMFgzIZ0s0l3m7s0/6B3elfU3dFv2NnRDHQb9eHpDhPTrvahsN95t",
	"rMaurPyApq5P009uj/9yF8iP9O7aLQop+iy2oyzBOJ0xOIyyoZEkG3DvuLE78uh7wcpnviCybuIJlbAC",
	"Xm8RsTS1gbV3lCWhK+AZJwPtvNFznsU7A2BHEz5u1zZEWBe3c3/kQrL0kiUwYB78mn2MPjYizrCUwFWU",
	"91+/4Ml/f1T/TCd/nX/8eh5+++jmTy4WjXboUkJfmy/PB727lt0c9vIqNvnVyK1MupbPIieJnBPq3nB3",
	"5dJ2Fl2feZgFL6M186IjBSFs3qBj83exS8U4fgL8Sjwmcg4b5RyOVIQj8l0QrRmMcMVsu86YznXQzznk",
	"8B6E/IEteizoMHmf2GLcYlvk2n7jyG0kXLvxjc74OoiPD51kLG1WYX+ihCitHwYC+Aa4wjhLSKQsOnxR",
	"iggnTqu0zlNM5zVIOxIakm+Nceru2LaHojhRUFfv2p6oy/w2yDSrnTLa4CTHEp4lwKV3k4qI8WKLklTx",
	"6Hw61fvT/DYNOza06zZy9+Z8BThRUZZXOS7mEaMUItnYTjU1JySWJlFQyG+tx9xqvbXiOIbYKa4NcOHW",
	"uW3qzQxhk5hqAOe6mJC3toyemCcmIkvwdu5z5LtaiG4IZ7TwYeppINf4K87y7LZelfLVbhl0kWyO45iD",
	"EA4qhwI2xmUDmt8+efLoSQ2c56HDwZN41bSJQ6xpp6L74ql+MJV8aqzbB6H+WEmNNT5KUuONjo/M0D6y",
	"esO3Y4cz7W0ytC32tw9uHWk1NoQX8yNwPQzk/UcfbsTbZTSl4cPbB03lvdWkAzrqV+HpX145dgT+hkRA",
	"BbyTWuReRaMjK+BeD/xLRjiIPmAP8n4JWOYcdtxShM5XHEcwz4ATNtprscG2gguOdLZdr0CDhM0TwxS1",
	"h+gGJ8Tt0khijsOKMZcc9CluBvQay2g9zxLtyACVOmchwDlMLghdzTMOm1au0+er6nnDylEqGffRL9+B",
	"oyu74PmnazmsZ+qNR0zpPXM5GGY8w1QYEnMjZSd4CjEPErPRC55zEM20XNXiGnNK6OpXkdtW+gXt7fld",
	"kqmOED0HHpE9D3GbekxXwL3nhLfMrBRoWmEJY49TSjLbyZKKxP7li0tYESF5DzztHGSHCqPmaZJDWfmS",
	"RH2DtmXmqnfZUx1UjQVN2sOeEqkLFb0TEJeQMBz7+ctyGbHUpoWcGQS/9veE3uWQXrq2LyDSp/19CcJb",
	"5TWG0xGWOo+TqYjzp63t9/4gWjECizHxdUFGc9LOFOWALl5WEPrt51ebuK7T4Vr5BwF8INNQ1hL0BOaP",
	"bl9u9JfDlBsV1Qe9Z/aKG3cbnf7qQowEi6ruYB7psojd4q39x2gdNnt5yxJ4JgRZ+QvblCK2Xvkuki66",
	"+WYW/bkQtYLxFqcBk6EtaoZ2pFm1s79k3WLEdxKvAE3RNU6uCF1NxBUkIBlFIudLHAH6v//5XyTXHAAB",
	"jTNGqBRIrrFE8AV4RAQguYZ/0iXLqameRkLi6Aqd1NLgYb2COkT6ICM0ldQIbN799ME/lUaRRCrnLfgp",
	"A/qzCgTQiSXxtJbHnAXTB+cPphOcZGv84FxbiAwozkgwCx49mD54pHefXGv2nuGMnG3Oz3CcEnpmfaaZ",
	"8fi0eJgBhxKSpvd1HMyCCyakLqRuuOSBYTgI+R2Lt3dW8+2MNG6a4lXG0xTcVoXyD6fTfdFQFiF2K+VV",
	"CzsHMh4zOhG5rk5EjCMFvhgtMUlyDqemOD1PU6xMXvCCbyc8p2hjyu0BYfTDz++RlQq6JnLNcokIFRIn",
	"CaErRIyz0pRiZj2lGdeu0ggxNn2rYI+M9HhxDk5eAJ8obiGzClQ6YTdh8Hj66HBXCp7jJAGOEhxdCWS8",
	"mYKzTfGZNSGlViG2LdGSJCDQkrNU1yxHjC7JKucQo5hwiKSJNr5MCixPKr8hmAXd6UpRK0Vxpk88tZBW",
	"4BDw30HWarv1vuc4BamV7C9fA+UUBZ9z0DQYQ1OVkFfs66h8d89ONfrOIzSq1nfuLQiNmh3HWFnfaDmV",
	"2lG5m9FskfktVpWQlMhGx7JA58k0rLKCDxuneY6c4M3HPe7r9hUC14ZWpootjYlDFrl6M099o5fkntVu",
	"PTU3nfInGkOiE8Prib2oBHGIKFyDkGhJuJCnrW0k12cJW5nwoEdNFoXwezJynZsGBzZw3UJ/hwR1A6St",
	"GcQQP0W6AFYgIkQOsZHl+eEU82uTQ0W1KkBlYt9+/wyVjNNggSg3l2p++ViHzgfrLp8Vbj3SQNB2FrHM",
	"hOjo/U/vL5yQYbkchRnVriO5xw53E7TWRxw27Aq6xkV9amyINf7CdOgSZwIGv0WQ67cQ7BlMjbsaXdEV",
	"JfaHxsyPzHhXBfMUYBaAuS13qPNb5pw2+F3eC3Aw/KyVR+hn/kUz57VfObjud7j9LdsMJaSjZl8ul6CP",
	"NlBtoWipPNpxHFriGehLNsN7pryPs3fedC7+uPhSu8iDPly+RlwjQ3nxdvVqgWrdEZaMI5xlbd7pORqM",
	"UsEoIlQrF6Ww3AwbFYbVrxDt0Th1rimNMlAONafUs14YOYLJUJMrltvjN7X7OWQJ3nb07XPlqPMUYYoM",
	"biHWlkVAxEGixdYsYqukidEKqBIMxMhpLQoDMzN5o2GJNq/f7FGs7ns+t5VtMRqyya6ae3cg9Q7XqLTm",
	"HD7pIi8lLFv7d2i8PTcXliqarjmzWbMa1DTvO/rhz6Ls5kBUpYVn3J45DdkdxzHVXkP9nlMxB6tKkprM",
	"+T5PEnT53bPnqFgmOqnOj8K6OQqRTrFPCEX6GMnh6dubW8Mb0N4Y2+POa91Ju4/+vtpN2sVHGSb8WG6+",
	"ZZSlxGruENnCitDo8FxArIAhIhyDdaGR5GS1Ag7xaW8ccMkklmb/8fpcT1FKqERYhY/IXDD+pmigGNKA",
	"V+vGk28fPq8126N4Pfe0XBqqbIlSkDjGElv/75hptoqbMw6dRJuO+etR30lJOqPJ9rQnodYZOOxRBG1h",
	"3b0i8N3PHKUNzvdAxkio2CO4g9v3+kM0hQ+n70WFaM2ERJRJpI9bzNs0tsW7d6/QFVjr/9cDept5IkmW",
	"ADJ34ZBN3Im2/dfMRLgG6XEIvuZEgk8LnX0l8Y1x0RKQ0EX4C/15JdTvtq9feFLEGZbrKiNpruQ3wOlM",
	"k3ouo3wc40ka4mJ0Ul5g+9sSJwJOjRAfH1AvVagv0dUS4Du2lBPD5ltI0crnJhxhNI4no+nxlE2h3O+j",
	"6L/Xr9HUhf5nURG8gx2qbeKY4BVlQpJIzCBas35v9UXV+qVq7EbHGnCsqzstPl5Xh86T/4BtL1galR9P",
	"Bis/PDP+5+R5dT40ed1/PvRxP+a2fovxwA534/6iA2vq+yq1fqtzEdXlyXCXzuNshzaLLewV3rtOu8dk",
	"uQQdMi+U4FuJNMUj46brJSNbFve0LLgQjffovjEHQ/7NZe5iTiQIOfnEFuM3WuMSZ9eRf3h3zHRfF3Vw",
	"9Qe20EFKJiF+iq4ZvwKOrkmSoJhjQtsmS+IVTKZIj45iSNlTZNkhVMTDJixDn9gCZZypwMdkURTvCZ3Y",
	"z+wkfvbae4kTnACX45lbv864J7/beWXywBrBUzjqSkGbUoLYNvWIMitaaVnaBQqToVbLnMu1Cl1ZEosy",
	"HeaRXMYhJXk62cn6XJhO98II/T7tR6HLHx5Ol9vCKBQzENpJIjRK8hiQhdC8Bitkb1V0onk9xEQX6iMF",
	"uafF+a3oHabhXRUfzgJHFy/QbfeJCh4n2hEbi/ZL09Pco9Q1U38g/hiIRyeRSRwZxaYEqT3q0+MmsEo6",
	"PMpaZ7SNqi6xXvapJbV7QojmFIPoNsmCW8D7Z93xD3zfH3xrUd4HgFcJqB0QrjvtAPFulsuFcQ4pxMQE",
	"l/AFonx3sF9WQ7y0I/yB+t+7H1PD1dzgSnvgx9x6NZJmBdT9e/Cbony8tRcdo6Bv3Msd8rjcPPJva98C",
	"iv1tnn7pO0YzD87s8wSt9aSNQybvgG9IBIgIVLxVcxMGTw4JixoJxSM5iHGUU7zBxNz17Tv4fEM2QFUg",
	"r+SOY6J/zjhbADopH9ptnqKXj5V4JaMbjKo0rz/HcIvCaIlXwznEfaGj/aqLQziqzT04SvV5ovoQdW2l",
	"NcLH7DsoLYS+D1vVfYPpwIejzRd3PHI+/oFocakInSxwjIrnWkJEshBljMsQgYwenB482/vKUoJwooC0",
	"RfCFCCkQoaiuADxHovrx0J0dRA3rs6/qvzmJb+rHojMOgiWbAefwVfP0/9L2GXPyZif9jR+/2RXXi+uP",
	"dw73I6uTUdo2XYCrj/0Zbx2xd4q59WpMiV01kr6rqVPkC0D6DEKNOAi6vrM7i7xRR+8KZPfz0N3QHc+x",
	"RALk4c/cXzVqOXpP28coiOET9uOKYnpQW3W/pFkcoI+RY+mIYBmtHYpbfXxwSe7H42m+lXbgGH2Ux3Os",
	"Eu+ux3O/AG0kh9Jcahul7dOSQBKL3f2Y4r2wnnjrTfmk2L4vvzefcuvJoQjVsMWVv4M01tcWxCf1tuhE",
	"EuBhkWYQIfqcM4lFiMxbZM0QtHyVyMcS/dfd9np3qPs35FwuFEvgHsR/il3e+K9ZMN+XsmmM0hDFzMQ+",
	"/Q615pbx6vdVSut5y/7QpbTdt+Kd90JUK831o4WOtQt/Ob2i7JoePDbUW4TESOIroN6q2IpXQwDtatDy",
	"QRmfstCP0uxTWXRfvXEwQjW6B7pCccurK3LLKZ8Eap37ckUVw+9eB3Rf0Trw7m++SOSR8z3IFTFevk9S",
	"96GOijvXYWKpBPQf8BvAnmf3j4zGlWjuYzR+cO9WY3Rc8D1GKsPB93E5Pz3o5r9f0iyC7zFy7Dh/1eay",
	"fiDWL8r1+4HF63PCPD/3G47S3e/o3fbmtPaEDAOPYBk+GP/P+KOkjRKzQoTN15INA0Y7YxYOvZDJ6U6g",
	"+VA0/wM2NdhwSNlG35Uq6lDkaScBrpoUItSvke0oxJviD+kYfrcfBopwgmLQCLPnuTlPglmwljITs7Oz",
	"RLXQWY6/PH78KLj5ePP/AQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
