// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CredentialCreateRequestAuthMethod.
const (
	CredentialCreateRequestAuthMethodBoth     CredentialCreateRequestAuthMethod = "both"
	CredentialCreateRequestAuthMethodPassword CredentialCreateRequestAuthMethod = "password"
	CredentialCreateRequestAuthMethodSshKey   CredentialCreateRequestAuthMethod = "ssh_key"
)

// Valid indicates whether the value is a known member of the CredentialCreateRequestAuthMethod enum.
func (e CredentialCreateRequestAuthMethod) Valid() bool {
	switch e {
	case CredentialCreateRequestAuthMethodBoth:
		return true
	case CredentialCreateRequestAuthMethodPassword:
		return true
	case CredentialCreateRequestAuthMethodSshKey:
		return true
	default:
		return false
	}
}

// Defines values for CredentialCreateRequestScope.
const (
	CredentialCreateRequestScopeHost   CredentialCreateRequestScope = "host"
	CredentialCreateRequestScopeSystem CredentialCreateRequestScope = "system"
)

// Valid indicates whether the value is a known member of the CredentialCreateRequestScope enum.
func (e CredentialCreateRequestScope) Valid() bool {
	switch e {
	case CredentialCreateRequestScopeHost:
		return true
	case CredentialCreateRequestScopeSystem:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResponseAuthMethod.
const (
	CredentialResponseAuthMethodBoth     CredentialResponseAuthMethod = "both"
	CredentialResponseAuthMethodPassword CredentialResponseAuthMethod = "password"
	CredentialResponseAuthMethodSshKey   CredentialResponseAuthMethod = "ssh_key"
)

// Valid indicates whether the value is a known member of the CredentialResponseAuthMethod enum.
func (e CredentialResponseAuthMethod) Valid() bool {
	switch e {
	case CredentialResponseAuthMethodBoth:
		return true
	case CredentialResponseAuthMethodPassword:
		return true
	case CredentialResponseAuthMethodSshKey:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResponseScope.
const (
	CredentialResponseScopeHost   CredentialResponseScope = "host"
	CredentialResponseScopeSystem CredentialResponseScope = "system"
)

// Valid indicates whether the value is a known member of the CredentialResponseScope enum.
func (e CredentialResponseScope) Valid() bool {
	switch e {
	case CredentialResponseScopeHost:
		return true
	case CredentialResponseScopeSystem:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeErrorFault.
const (
	Client   ErrorEnvelopeErrorFault = "client"
	External ErrorEnvelopeErrorFault = "external"
	Policy   ErrorEnvelopeErrorFault = "policy"
	Server   ErrorEnvelopeErrorFault = "server"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorFault enum.
func (e ErrorEnvelopeErrorFault) Valid() bool {
	switch e {
	case Client:
		return true
	case External:
		return true
	case Policy:
		return true
	case Server:
		return true
	default:
		return false
	}
}

// Defines values for FleetTransactionChangeKind.
const (
	FirstSeen       FleetTransactionChangeKind = "first_seen"
	SeverityChanged FleetTransactionChangeKind = "severity_changed"
	StateChanged    FleetTransactionChangeKind = "state_changed"
)

// Valid indicates whether the value is a known member of the FleetTransactionChangeKind enum.
func (e FleetTransactionChangeKind) Valid() bool {
	switch e {
	case FirstSeen:
		return true
	case SeverityChanged:
		return true
	case StateChanged:
		return true
	default:
		return false
	}
}

// Defines values for FleetTransactionStatus.
const (
	Error   FleetTransactionStatus = "error"
	Fail    FleetTransactionStatus = "fail"
	Pass    FleetTransactionStatus = "pass"
	Skipped FleetTransactionStatus = "skipped"
)

// Valid indicates whether the value is a known member of the FleetTransactionStatus enum.
func (e FleetTransactionStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Fail:
		return true
	case Pass:
		return true
	case Skipped:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Healthy  HealthResponseStatus = "healthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Healthy:
		return true
	default:
		return false
	}
}

// Defines values for LicenseStateResponseStatus.
const (
	Active    LicenseStateResponseStatus = "active"
	Expired   LicenseStateResponseStatus = "expired"
	Grace     LicenseStateResponseStatus = "grace"
	Invalid   LicenseStateResponseStatus = "invalid"
	NoLicense LicenseStateResponseStatus = "no_license"
)

// Valid indicates whether the value is a known member of the LicenseStateResponseStatus enum.
func (e LicenseStateResponseStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Expired:
		return true
	case Grace:
		return true
	case Invalid:
		return true
	case NoLicense:
		return true
	default:
		return false
	}
}

// Defines values for LicenseStateResponseTier.
const (
	Enterprise    LicenseStateResponseTier = "enterprise"
	Free          LicenseStateResponseTier = "free"
	OpenwatchPlus LicenseStateResponseTier = "openwatch_plus"
)

// Valid indicates whether the value is a known member of the LicenseStateResponseTier enum.
func (e LicenseStateResponseTier) Valid() bool {
	switch e {
	case Enterprise:
		return true
	case Free:
		return true
	case OpenwatchPlus:
		return true
	default:
		return false
	}
}

// AdminRolesResponse defines model for AdminRolesResponse.
type AdminRolesResponse struct {
	Roles []RoleEntry `json:"roles"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action        string                  `json:"action"`
	ActorId       *string                 `json:"actor_id,omitempty"`
	ActorType     string                  `json:"actor_type"`
	CorrelationId string                  `json:"correlation_id"`
	Detail        *map[string]interface{} `json:"detail,omitempty"`
	Id            openapi_types.UUID      `json:"id"`
	OccurredAt    time.Time               `json:"occurred_at"`
	RecordedAt    *time.Time              `json:"recorded_at,omitempty"`
	Redactions    *[]string               `json:"redactions,omitempty"`
	ResourceId    *string                 `json:"resource_id,omitempty"`
	ResourceType  *string                 `json:"resource_type,omitempty"`
	Severity      *string                 `json:"severity,omitempty"`
}

// AuditEventsPage defines model for AuditEventsPage.
type AuditEventsPage struct {
	Items []AuditEvent `json:"items"`

	// NextCursor Opaque cursor; pass as ?cursor= to fetch the next page
	NextCursor *string `json:"next_cursor"`
}

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Otp      *string `json:"otp,omitempty"`
	Password string  `json:"password"`
	Username string  `json:"username"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	User         AuthMeResponse `json:"user"`
}

// AuthMFAEnrollResponse defines model for AuthMFAEnrollResponse.
type AuthMFAEnrollResponse struct {
	ProvisioningUri string `json:"provisioning_uri"`
}

// AuthMFAVerifyRequest defines model for AuthMFAVerifyRequest.
type AuthMFAVerifyRequest struct {
	Otp string `json:"otp"`
}

// AuthMePermissionsResponse defines model for AuthMePermissionsResponse.
type AuthMePermissionsResponse struct {
	Identity struct {
		Id          string `json:"id"`
		IsAnonymous bool   `json:"is_anonymous"`
		Role        string `json:"role"`
	} `json:"identity"`
	Permissions []string `json:"permissions"`
}

// AuthMeResponse defines model for AuthMeResponse.
type AuthMeResponse struct {
	Email    string             `json:"email"`
	Id       openapi_types.UUID `json:"id"`
	Role     string             `json:"role"`
	Username string             `json:"username"`
}

// AuthPasswordChangeRequest defines model for AuthPasswordChangeRequest.
type AuthPasswordChangeRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// CategoryEntry defines model for CategoryEntry.
type CategoryEntry struct {
	Description string `json:"description"`
	Id          string `json:"id"`
}

// CredentialCreateRequest defines model for CredentialCreateRequest.
type CredentialCreateRequest struct {
	AuthMethod           CredentialCreateRequestAuthMethod `json:"auth_method"`
	Description          *string                           `json:"description,omitempty"`
	IsDefault            *bool                             `json:"is_default,omitempty"`
	Name                 string                            `json:"name"`
	Password             *string                           `json:"password,omitempty"`
	PrivateKey           *string                           `json:"private_key,omitempty"`
	PrivateKeyPassphrase *string                           `json:"private_key_passphrase,omitempty"`
	Scope                CredentialCreateRequestScope      `json:"scope"`
	ScopeId              *openapi_types.UUID               `json:"scope_id,omitempty"`
	Username             string                            `json:"username"`
}

// CredentialCreateRequestAuthMethod defines model for CredentialCreateRequest.AuthMethod.
type CredentialCreateRequestAuthMethod string

// CredentialCreateRequestScope defines model for CredentialCreateRequest.Scope.
type CredentialCreateRequestScope string

// CredentialListResponse defines model for CredentialListResponse.
type CredentialListResponse struct {
	Credentials []CredentialResponse `json:"credentials"`
}

// CredentialResponse defines model for CredentialResponse.
type CredentialResponse struct {
	AuthMethod        CredentialResponseAuthMethod `json:"auth_method"`
	CreatedAt         *time.Time                   `json:"created_at,omitempty"`
	CreatedBy         *openapi_types.UUID          `json:"created_by,omitempty"`
	Description       *string                      `json:"description,omitempty"`
	Id                openapi_types.UUID           `json:"id"`
	IsActive          bool                         `json:"is_active"`
	IsDefault         bool                         `json:"is_default"`
	Name              string                       `json:"name"`
	Scope             CredentialResponseScope      `json:"scope"`
	ScopeId           *openapi_types.UUID          `json:"scope_id,omitempty"`
	SshKeyBits        *int                         `json:"ssh_key_bits,omitempty"`
	SshKeyComment     *string                      `json:"ssh_key_comment,omitempty"`
	SshKeyFingerprint *string                      `json:"ssh_key_fingerprint,omitempty"`
	SshKeyType        *string                      `json:"ssh_key_type,omitempty"`
	UpdatedAt         *time.Time                   `json:"updated_at,omitempty"`
	Username          string                       `json:"username"`
}

// CredentialResponseAuthMethod defines model for CredentialResponse.AuthMethod.
type CredentialResponseAuthMethod string

// CredentialResponseScope defines model for CredentialResponse.Scope.
type CredentialResponseScope string

// CustomRoleCreateRequest defines model for CustomRoleCreateRequest.
type CustomRoleCreateRequest struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	Permissions []string `json:"permissions"`
}

// CustomRoleResponse defines model for CustomRoleResponse.
type CustomRoleResponse struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	IsBuiltIn   bool     `json:"is_built_in"`
	Permissions []string `json:"permissions"`
}

// EchoRequest defines model for EchoRequest.
type EchoRequest struct {
	Message string `json:"message"`
}

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	AuditEventId  *openapi_types.UUID `json:"audit_event_id,omitempty"`
	CorrelationId string              `json:"correlation_id"`
	Echoed        string              `json:"echoed"`
}

// EnqueueTestJobResponse defines model for EnqueueTestJobResponse.
type EnqueueTestJobResponse struct {
	CorrelationId string             `json:"correlation_id"`
	JobId         openapi_types.UUID `json:"job_id"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code          string                  `json:"code"`
		CorrelationId *string                 `json:"correlation_id,omitempty"`
		Detail        *map[string]interface{} `json:"detail,omitempty"`
		Fault         ErrorEnvelopeErrorFault `json:"fault"`
		HumanMessage  string                  `json:"human_message"`
		Retryable     bool                    `json:"retryable"`
	} `json:"error"`
}

// ErrorEnvelopeErrorFault defines model for ErrorEnvelope.Error.Fault.
type ErrorEnvelopeErrorFault string

// EvaluateAlertRequest defines model for EvaluateAlertRequest.
type EvaluateAlertRequest struct {
	Score int `json:"score"`
}

// FleetHostFailure defines model for FleetHostFailure.
type FleetHostFailure struct {
	FailingRuleCount int64              `json:"failing_rule_count"`
	HostId           openapi_types.UUID `json:"host_id"`
}

// FleetLiveness defines model for FleetLiveness.
type FleetLiveness struct {
	NeverProbed int64 `json:"never_probed"`
	Reachable   int64 `json:"reachable"`
	Unknown     int64 `json:"unknown"`
	Unreachable int64 `json:"unreachable"`
}

// FleetRecentChanges defines model for FleetRecentChanges.
type FleetRecentChanges struct {
	Items []FleetTransaction `json:"items"`
}

// FleetRuleFailure defines model for FleetRuleFailure.
type FleetRuleFailure struct {
	FailingHostCount int64  `json:"failing_host_count"`
	RuleId           string `json:"rule_id"`
}

// FleetScore defines model for FleetScore.
type FleetScore struct {
	// PassingFraction Passing rules / (passing + failing) across all hosts. 0..1.
	PassingFraction float64 `json:"passing_fraction"`

	// TotalEvaluations Count of host_rule_state rows where current_status is pass or fail.
	TotalEvaluations int64 `json:"total_evaluations"`
}

// FleetTopFailingHosts defines model for FleetTopFailingHosts.
type FleetTopFailingHosts struct {
	Items []FleetHostFailure `json:"items"`
}

// FleetTopFailingRules defines model for FleetTopFailingRules.
type FleetTopFailingRules struct {
	Items []FleetRuleFailure `json:"items"`
}

// FleetTransaction defines model for FleetTransaction.
type FleetTransaction struct {
	ChangeKind FleetTransactionChangeKind `json:"change_kind"`
	HostId     openapi_types.UUID         `json:"host_id"`
	Id         openapi_types.UUID         `json:"id"`
	OccurredAt time.Time                  `json:"occurred_at"`
	RuleId     string                     `json:"rule_id"`
	Severity   *string                    `json:"severity,omitempty"`
	Status     FleetTransactionStatus     `json:"status"`
}

// FleetTransactionChangeKind defines model for FleetTransaction.ChangeKind.
type FleetTransactionChangeKind string

// FleetTransactionStatus defines model for FleetTransaction.Status.
type FleetTransactionStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	DbConnected bool                 `json:"db_connected"`
	Status      HealthResponseStatus `json:"status"`
	Version     string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HostCreateRequest defines model for HostCreateRequest.
type HostCreateRequest struct {
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment *string             `json:"environment,omitempty"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	Hostname    string              `json:"hostname"`
	IpAddress   string              `json:"ip_address"`
	Port        *int                `json:"port,omitempty"`
	Tags        *[]string           `json:"tags,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// HostListResponse defines model for HostListResponse.
type HostListResponse struct {
	Hosts []HostResponse `json:"hosts"`
}

// HostResponse defines model for HostResponse.
type HostResponse struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	CreatedBy   *openapi_types.UUID `json:"created_by,omitempty"`
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment string              `json:"environment"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	Hostname    string              `json:"hostname"`
	Id          openapi_types.UUID  `json:"id"`
	IpAddress   string              `json:"ip_address"`
	Port        int                 `json:"port"`
	Tags        *[]string           `json:"tags,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// HostUpdateRequest defines model for HostUpdateRequest.
type HostUpdateRequest struct {
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment *string             `json:"environment,omitempty"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	IpAddress   *string             `json:"ip_address,omitempty"`
	Port        *int                `json:"port,omitempty"`
	Tags        *[]string           `json:"tags,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// LicenseStateResponse defines model for LicenseStateResponse.
type LicenseStateResponse struct {
	CustomerId    *string                    `json:"customer_id,omitempty"`
	ExpiresAt     *time.Time                 `json:"expires_at,omitempty"`
	Features      []string                   `json:"features"`
	InGracePeriod *bool                      `json:"in_grace_period,omitempty"`
	Status        LicenseStateResponseStatus `json:"status"`
	Tier          LicenseStateResponseTier   `json:"tier"`
	UsingPrevKey  *bool                      `json:"using_prev_key,omitempty"`
}

// LicenseStateResponseStatus defines model for LicenseStateResponse.Status.
type LicenseStateResponseStatus string

// LicenseStateResponseTier defines model for LicenseStateResponse.Tier.
type LicenseStateResponseTier string

// LicenseVerifyRequest defines model for LicenseVerifyRequest.
type LicenseVerifyRequest struct {
	LicenseJwt string `json:"license_jwt"`
}

// LicenseVerifyResponse defines model for LicenseVerifyResponse.
type LicenseVerifyResponse struct {
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	Features     *[]string  `json:"features,omitempty"`
	IsValid      bool       `json:"is_valid"`
	Tier         *string    `json:"tier,omitempty"`
	VerifyResult string     `json:"verify_result"`
	Warnings     *[]string  `json:"warnings,omitempty"`
}

// PermissionEntry defines model for PermissionEntry.
type PermissionEntry struct {
	Category     string  `json:"category"`
	Dangerous    bool    `json:"dangerous"`
	Description  string  `json:"description"`
	Id           string  `json:"id"`
	LicenseGated *string `json:"license_gated,omitempty"`
}

// PermissionsRegistryResponse defines model for PermissionsRegistryResponse.
type PermissionsRegistryResponse struct {
	Categories  []CategoryEntry   `json:"categories"`
	Permissions []PermissionEntry `json:"permissions"`
	Roles       []RoleEntry       `json:"roles"`
}

// PoliciesReloadResponse defines model for PoliciesReloadResponse.
type PoliciesReloadResponse struct {
	Outcomes map[string]string `json:"outcomes"`
}

// PolicyDecisionResponse defines model for PolicyDecisionResponse.
type PolicyDecisionResponse struct {
	Detail        *map[string]interface{} `json:"detail,omitempty"`
	HumanMessage  *string                 `json:"human_message,omitempty"`
	Outcome       string                  `json:"outcome"`
	PolicyType    string                  `json:"policy_type"`
	PolicyVersion string                  `json:"policy_version"`
	Reason        string                  `json:"reason"`
}

// RoleEntry defines model for RoleEntry.
type RoleEntry struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	IsBuiltIn   bool     `json:"is_built_in"`
	Permissions []string `json:"permissions"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt            *time.Time         `json:"created_at,omitempty"`
	Email                string             `json:"email"`
	Id                   openapi_types.UUID `json:"id"`
	LastPasswordChangeAt *time.Time         `json:"last_password_change_at,omitempty"`
	UpdatedAt            *time.Time         `json:"updated_at,omitempty"`
	Username             string             `json:"username"`
}

// UserRoleAssignRequest defines model for UserRoleAssignRequest.
type UserRoleAssignRequest struct {
	RoleId string `json:"role_id"`
}

// UsersListResponse defines model for UsersListResponse.
type UsersListResponse struct {
	Users []UserResponse `json:"users"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorEnvelope

// GetAuditEventsParams defines parameters for GetAuditEvents.
type GetAuditEventsParams struct {
	Action        *string    `form:"action,omitempty" json:"action,omitempty"`
	CorrelationId *string    `form:"correlation_id,omitempty" json:"correlation_id,omitempty"`
	ActorType     *string    `form:"actor_type,omitempty" json:"actor_type,omitempty"`
	Since         *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Until         *time.Time `form:"until,omitempty" json:"until,omitempty"`
	Cursor        *string    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostDiagnosticsEchoParams defines parameters for PostDiagnosticsEcho.
type PostDiagnosticsEchoParams struct {
	IdempotencyKey string  `json:"Idempotency-Key"`
	XCorrelationId *string `json:"X-Correlation-Id,omitempty"`
}

// PostDiagnosticsPremiumEchoParams defines parameters for PostDiagnosticsPremiumEcho.
type PostDiagnosticsPremiumEchoParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireHostReadParams defines parameters for PostDiagnosticsRequireHostRead.
type PostDiagnosticsRequireHostReadParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireHostWriteParams defines parameters for PostDiagnosticsRequireHostWrite.
type PostDiagnosticsRequireHostWriteParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireRemediationExecuteParams defines parameters for PostDiagnosticsRequireRemediationExecute.
type PostDiagnosticsRequireRemediationExecuteParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// GetFleetRecentChangesParams defines parameters for GetFleetRecentChanges.
type GetFleetRecentChangesParams struct {
	// Since Filter to transactions strictly newer than this RFC3339 timestamp
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Limit *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetFleetTopFailingHostsParams defines parameters for GetFleetTopFailingHosts.
type GetFleetTopFailingHostsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetFleetTopFailingRulesParams defines parameters for GetFleetTopFailingRules.
type GetFleetTopFailingRulesParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetHostsParams defines parameters for GetHosts.
type GetHostsParams struct {
	Environment *string `form:"environment,omitempty" json:"environment,omitempty"`
	Tag         *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// PostAdminLicenseVerifyJSONRequestBody defines body for PostAdminLicenseVerify for application/json ContentType.
type PostAdminLicenseVerifyJSONRequestBody = LicenseVerifyRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthLoginRequest

// PostAuthMFAVerifyJSONRequestBody defines body for PostAuthMFAVerify for application/json ContentType.
type PostAuthMFAVerifyJSONRequestBody = AuthMFAVerifyRequest

// PostAuthPasswordChangeJSONRequestBody defines body for PostAuthPasswordChange for application/json ContentType.
type PostAuthPasswordChangeJSONRequestBody = AuthPasswordChangeRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = AuthRefreshRequest

// PostCredentialsJSONRequestBody defines body for PostCredentials for application/json ContentType.
type PostCredentialsJSONRequestBody = CredentialCreateRequest

// PostDiagnosticsEchoJSONRequestBody defines body for PostDiagnosticsEcho for application/json ContentType.
type PostDiagnosticsEchoJSONRequestBody = EchoRequest

// PostDiagnosticsEvaluateAlertJSONRequestBody defines body for PostDiagnosticsEvaluateAlert for application/json ContentType.
type PostDiagnosticsEvaluateAlertJSONRequestBody = EvaluateAlertRequest

// PostDiagnosticsPremiumEchoJSONRequestBody defines body for PostDiagnosticsPremiumEcho for application/json ContentType.
type PostDiagnosticsPremiumEchoJSONRequestBody = EchoRequest

// PostDiagnosticsRequireHostReadJSONRequestBody defines body for PostDiagnosticsRequireHostRead for application/json ContentType.
type PostDiagnosticsRequireHostReadJSONRequestBody = EchoRequest

// PostDiagnosticsRequireHostWriteJSONRequestBody defines body for PostDiagnosticsRequireHostWrite for application/json ContentType.
type PostDiagnosticsRequireHostWriteJSONRequestBody = EchoRequest

// PostDiagnosticsRequireRemediationExecuteJSONRequestBody defines body for PostDiagnosticsRequireRemediationExecute for application/json ContentType.
type PostDiagnosticsRequireRemediationExecuteJSONRequestBody = EchoRequest

// PostHostsJSONRequestBody defines body for PostHosts for application/json ContentType.
type PostHostsJSONRequestBody = HostCreateRequest

// PatchHostByIDJSONRequestBody defines body for PatchHostByID for application/json ContentType.
type PatchHostByIDJSONRequestBody = HostUpdateRequest

// PostRolesCreateJSONRequestBody defines body for PostRolesCreate for application/json ContentType.
type PostRolesCreateJSONRequestBody = CustomRoleCreateRequest

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody = UserCreateRequest

// PostUserRolesAssignJSONRequestBody defines body for PostUserRolesAssign for application/json ContentType.
type PostUserRolesAssignJSONRequestBody = UserRoleAssignRequest

// PostUserRolesUnassignJSONRequestBody defines body for PostUserRolesUnassign for application/json ContentType.
type PostUserRolesUnassignJSONRequestBody = UserRoleAssignRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Dry-run validate a JWT license without installing it
	// (POST /api/v1/admin/license:verify)
	PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request)
	// Reload signed policy files from the configured directory
	// (POST /api/v1/admin/policies:reload)
	PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request)
	// List audit events (cursor-paginated, newest first)
	// (GET /api/v1/audit/events)
	GetAuditEvents(w http.ResponseWriter, r *http.Request, params GetAuditEventsParams)
	// Username/password login with optional TOTP
	// (POST /api/v1/auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Revoke the calling session
	// (POST /api/v1/auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Return the calling identity
	// (GET /api/v1/auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Effective permissions for the calling identity
	// (GET /api/v1/auth/me/permissions)
	GetAuthMePermissions(w http.ResponseWriter, r *http.Request)
	// Enroll the calling user in TOTP MFA
	// (POST /api/v1/auth/mfa:enroll)
	PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request)
	// Confirm an enrolled MFA secret by verifying a generated OTP
	// (POST /api/v1/auth/mfa:verify)
	PostAuthMFAVerify(w http.ResponseWriter, r *http.Request)
	// Change the calling user's password
	// (POST /api/v1/auth/password:change)
	PostAuthPasswordChange(w http.ResponseWriter, r *http.Request)
	// Full RBAC registry (categories, permissions, built-in roles)
	// (GET /api/v1/auth/permissions:registry)
	GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request)
	// Rotate the refresh token; mint a new access+refresh pair
	// (POST /api/v1/auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// List credentials (metadata only)
	// (GET /api/v1/credentials)
	GetCredentials(w http.ResponseWriter, r *http.Request)
	// Create a credential
	// (POST /api/v1/credentials)
	PostCredentials(w http.ResponseWriter, r *http.Request)
	// Soft-delete a credential
	// (DELETE /api/v1/credentials/{id})
	DeleteCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a credential's metadata
	// (GET /api/v1/credentials/{id})
	GetCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Echo the request message; exercises idempotency + audit
	// (POST /api/v1/diagnostics:echo)
	PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsEchoParams)
	// Stage-0 queue demo; enqueues a no-op job processed by the in-process worker
	// (POST /api/v1/diagnostics:enqueue-test-job)
	PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request)
	// Stage-0 policy demo; evaluates the alert_thresholds policy
	// (POST /api/v1/diagnostics:evaluate-alert)
	PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request)
	// License-gated echo; requires premium_diagnostics feature
	// (POST /api/v1/diagnostics:premium-echo)
	PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsPremiumEchoParams)
	// Stage-0 RBAC demo; requires host:read permission
	// (POST /api/v1/diagnostics:require-host-read)
	PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostReadParams)
	// Stage-0 RBAC demo; requires host:write permission
	// (POST /api/v1/diagnostics:require-host-write)
	PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostWriteParams)
	// Stage-0 RBAC+license demo; requires remediation:execute + remediation_execution feature
	// (POST /api/v1/diagnostics:require-remediation-execute)
	PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireRemediationExecuteParams)
	// Host counts by reachability status
	// (GET /api/v1/fleet/liveness)
	GetFleetLiveness(w http.ResponseWriter, r *http.Request)
	// Recent transactions (state changes), newest first
	// (GET /api/v1/fleet/recent-changes)
	GetFleetRecentChanges(w http.ResponseWriter, r *http.Request, params GetFleetRecentChangesParams)
	// Fleet-wide compliance score (passing/total)
	// (GET /api/v1/fleet/score)
	GetFleetScore(w http.ResponseWriter, r *http.Request)
	// Hosts with the most failing rules (descending)
	// (GET /api/v1/fleet/top-failing-hosts)
	GetFleetTopFailingHosts(w http.ResponseWriter, r *http.Request, params GetFleetTopFailingHostsParams)
	// Rules with the most failing hosts (descending)
	// (GET /api/v1/fleet/top-failing-rules)
	GetFleetTopFailingRules(w http.ResponseWriter, r *http.Request, params GetFleetTopFailingRulesParams)
	// Liveness + readiness probe (anonymous)
	// (GET /api/v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// List hosts
	// (GET /api/v1/hosts)
	GetHosts(w http.ResponseWriter, r *http.Request, params GetHostsParams)
	// Create a host
	// (POST /api/v1/hosts)
	PostHosts(w http.ResponseWriter, r *http.Request)
	// Resolve the credential that will be used for a host
	// (POST /api/v1/hosts/{host_id}/credentials:resolve)
	PostHostCredentialsResolve(w http.ResponseWriter, r *http.Request, hostId openapi_types.UUID)
	// Soft-delete a host
	// (DELETE /api/v1/hosts/{id})
	DeleteHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a host
	// (GET /api/v1/hosts/{id})
	GetHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update mutable host fields
	// (PATCH /api/v1/hosts/{id})
	PatchHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get the current license state (tier, features, quotas, status)
	// (GET /api/v1/license)
	GetLicense(w http.ResponseWriter, r *http.Request)
	// List built-in roles
	// (GET /api/v1/roles)
	GetRoles(w http.ResponseWriter, r *http.Request)
	// Create a custom role
	// (POST /api/v1/roles:create)
	PostRolesCreate(w http.ResponseWriter, r *http.Request)
	// List users
	// (GET /api/v1/users)
	GetUsers(w http.ResponseWriter, r *http.Request)
	// Create a user
	// (POST /api/v1/users)
	PostUsers(w http.ResponseWriter, r *http.Request)
	// Soft-delete a user
	// (DELETE /api/v1/users/{id})
	DeleteUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a user
	// (GET /api/v1/users/{id})
	GetUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Assign a role to a user
	// (POST /api/v1/users/{id}/roles:assign)
	PostUserRolesAssign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove a role from a user
	// (POST /api/v1/users/{id}/roles:unassign)
	PostUserRolesUnassign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Dry-run validate a JWT license without installing it
// (POST /api/v1/admin/license:verify)
func (_ Unimplemented) PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reload signed policy files from the configured directory
// (POST /api/v1/admin/policies:reload)
func (_ Unimplemented) PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List audit events (cursor-paginated, newest first)
// (GET /api/v1/audit/events)
func (_ Unimplemented) GetAuditEvents(w http.ResponseWriter, r *http.Request, params GetAuditEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Username/password login with optional TOTP
// (POST /api/v1/auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke the calling session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the calling identity
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Effective permissions for the calling identity
// (GET /api/v1/auth/me/permissions)
func (_ Unimplemented) GetAuthMePermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Enroll the calling user in TOTP MFA
// (POST /api/v1/auth/mfa:enroll)
func (_ Unimplemented) PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm an enrolled MFA secret by verifying a generated OTP
// (POST /api/v1/auth/mfa:verify)
func (_ Unimplemented) PostAuthMFAVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change the calling user's password
// (POST /api/v1/auth/password:change)
func (_ Unimplemented) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Full RBAC registry (categories, permissions, built-in roles)
// (GET /api/v1/auth/permissions:registry)
func (_ Unimplemented) GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate the refresh token; mint a new access+refresh pair
// (POST /api/v1/auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List credentials (metadata only)
// (GET /api/v1/credentials)
func (_ Unimplemented) GetCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a credential
// (POST /api/v1/credentials)
func (_ Unimplemented) PostCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a credential
// (DELETE /api/v1/credentials/{id})
func (_ Unimplemented) DeleteCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a credential's metadata
// (GET /api/v1/credentials/{id})
func (_ Unimplemented) GetCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the request message; exercises idempotency + audit
// (POST /api/v1/diagnostics:echo)
func (_ Unimplemented) PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsEchoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 queue demo; enqueues a no-op job processed by the in-process worker
// (POST /api/v1/diagnostics:enqueue-test-job)
func (_ Unimplemented) PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 policy demo; evaluates the alert_thresholds policy
// (POST /api/v1/diagnostics:evaluate-alert)
func (_ Unimplemented) PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// License-gated echo; requires premium_diagnostics feature
// (POST /api/v1/diagnostics:premium-echo)
func (_ Unimplemented) PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsPremiumEchoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC demo; requires host:read permission
// (POST /api/v1/diagnostics:require-host-read)
func (_ Unimplemented) PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostReadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC demo; requires host:write permission
// (POST /api/v1/diagnostics:require-host-write)
func (_ Unimplemented) PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostWriteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC+license demo; requires remediation:execute + remediation_execution feature
// (POST /api/v1/diagnostics:require-remediation-execute)
func (_ Unimplemented) PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireRemediationExecuteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Host counts by reachability status
// (GET /api/v1/fleet/liveness)
func (_ Unimplemented) GetFleetLiveness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Recent transactions (state changes), newest first
// (GET /api/v1/fleet/recent-changes)
func (_ Unimplemented) GetFleetRecentChanges(w http.ResponseWriter, r *http.Request, params GetFleetRecentChangesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fleet-wide compliance score (passing/total)
// (GET /api/v1/fleet/score)
func (_ Unimplemented) GetFleetScore(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Hosts with the most failing rules (descending)
// (GET /api/v1/fleet/top-failing-hosts)
func (_ Unimplemented) GetFleetTopFailingHosts(w http.ResponseWriter, r *http.Request, params GetFleetTopFailingHostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rules with the most failing hosts (descending)
// (GET /api/v1/fleet/top-failing-rules)
func (_ Unimplemented) GetFleetTopFailingRules(w http.ResponseWriter, r *http.Request, params GetFleetTopFailingRulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness + readiness probe (anonymous)
// (GET /api/v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List hosts
// (GET /api/v1/hosts)
func (_ Unimplemented) GetHosts(w http.ResponseWriter, r *http.Request, params GetHostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a host
// (POST /api/v1/hosts)
func (_ Unimplemented) PostHosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve the credential that will be used for a host
// (POST /api/v1/hosts/{host_id}/credentials:resolve)
func (_ Unimplemented) PostHostCredentialsResolve(w http.ResponseWriter, r *http.Request, hostId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a host
// (DELETE /api/v1/hosts/{id})
func (_ Unimplemented) DeleteHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a host
// (GET /api/v1/hosts/{id})
func (_ Unimplemented) GetHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update mutable host fields
// (PATCH /api/v1/hosts/{id})
func (_ Unimplemented) PatchHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current license state (tier, features, quotas, status)
// (GET /api/v1/license)
func (_ Unimplemented) GetLicense(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List built-in roles
// (GET /api/v1/roles)
func (_ Unimplemented) GetRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a custom role
// (POST /api/v1/roles:create)
func (_ Unimplemented) PostRolesCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /api/v1/users)
func (_ Unimplemented) GetUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a user
// (POST /api/v1/users)
func (_ Unimplemented) PostUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a user
// (DELETE /api/v1/users/{id})
func (_ Unimplemented) DeleteUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a user
// (GET /api/v1/users/{id})
func (_ Unimplemented) GetUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign a role to a user
// (POST /api/v1/users/{id}/roles:assign)
func (_ Unimplemented) PostUserRolesAssign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a role from a user
// (POST /api/v1/users/{id}/roles:unassign)
func (_ Unimplemented) PostUserRolesUnassign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostAdminLicenseVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminLicenseVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminPoliciesReload operation middleware
func (siw *ServerInterfaceWrapper) PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminPoliciesReload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditEventsParams

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", r.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "action"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "correlation_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "correlation_id", r.URL.Query(), &params.CorrelationId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "correlation_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "correlation_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "actor_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_type", r.URL.Query(), &params.ActorType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "actor_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "until", r.URL.Query(), &params.Until, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "until"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMePermissions operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMePermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMePermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMFAEnroll operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMFAEnroll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMFAVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMFAVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMFAVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthPasswordChange operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthPasswordChange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthPermissionsRegistry operation middleware
func (siw *ServerInterfaceWrapper) GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthPermissionsRegistry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetCredentials(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostCredentials operation middleware
func (siw *ServerInterfaceWrapper) PostCredentials(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCredentialByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteCredentialByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCredentialByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCredentialByID operation middleware
func (siw *ServerInterfaceWrapper) GetCredentialByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCredentialByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEcho operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsEchoParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEcho(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEnqueueTestJob operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEnqueueTestJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEvaluateAlert operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEvaluateAlert(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsPremiumEcho operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsPremiumEchoParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsPremiumEcho(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireHostRead operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireHostReadParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireHostRead(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireHostWrite operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireHostWriteParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireHostWrite(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireRemediationExecute operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireRemediationExecuteParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireRemediationExecute(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFleetLiveness operation middleware
func (siw *ServerInterfaceWrapper) GetFleetLiveness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFleetLiveness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFleetRecentChanges operation middleware
func (siw *ServerInterfaceWrapper) GetFleetRecentChanges(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFleetRecentChangesParams

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFleetRecentChanges(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFleetScore operation middleware
func (siw *ServerInterfaceWrapper) GetFleetScore(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFleetScore(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFleetTopFailingHosts operation middleware
func (siw *ServerInterfaceWrapper) GetFleetTopFailingHosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFleetTopFailingHostsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFleetTopFailingHosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFleetTopFailingRules operation middleware
func (siw *ServerInterfaceWrapper) GetFleetTopFailingRules(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFleetTopFailingRulesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFleetTopFailingRules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHosts operation middleware
func (siw *ServerInterfaceWrapper) GetHosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHostsParams

	// ------------- Optional query parameter "environment" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "environment", r.URL.Query(), &params.Environment, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "environment"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "environment", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHosts operation middleware
func (siw *ServerInterfaceWrapper) PostHosts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostHostCredentialsResolve operation middleware
func (siw *ServerInterfaceWrapper) PostHostCredentialsResolve(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "host_id" -------------
	var hostId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "host_id", chi.URLParam(r, "host_id"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "host_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostHostCredentialsResolve(w, r, hostId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteHostByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHostByID operation middleware
func (siw *ServerInterfaceWrapper) GetHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchHostByID operation middleware
func (siw *ServerInterfaceWrapper) PatchHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLicense operation middleware
func (siw *ServerInterfaceWrapper) GetLicense(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLicense(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoles operation middleware
func (siw *ServerInterfaceWrapper) GetRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRolesCreate operation middleware
func (siw *ServerInterfaceWrapper) PostRolesCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRolesCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUsers operation middleware
func (siw *ServerInterfaceWrapper) GetUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUsers operation middleware
func (siw *ServerInterfaceWrapper) PostUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUserByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUserByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserByID operation middleware
func (siw *ServerInterfaceWrapper) GetUserByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRolesAssign operation middleware
func (siw *ServerInterfaceWrapper) PostUserRolesAssign(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRolesAssign(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostUserRolesUnassign operation middleware
func (siw *ServerInterfaceWrapper) PostUserRolesUnassign(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostUserRolesUnassign(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/license:verify", wrapper.PostAdminLicenseVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/policies:reload", wrapper.PostAdminPoliciesReload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/audit/events", wrapper.GetAuditEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me/permissions", wrapper.GetAuthMePermissions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa:enroll", wrapper.PostAuthMFAEnroll)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa:verify", wrapper.PostAuthMFAVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password:change", wrapper.PostAuthPasswordChange)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/permissions:registry", wrapper.GetAuthPermissionsRegistry)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/credentials", wrapper.GetCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/credentials", wrapper.PostCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/credentials/{id}", wrapper.DeleteCredentialByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/credentials/{id}", wrapper.GetCredentialByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:echo", wrapper.PostDiagnosticsEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:enqueue-test-job", wrapper.PostDiagnosticsEnqueueTestJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:evaluate-alert", wrapper.PostDiagnosticsEvaluateAlert)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:premium-echo", wrapper.PostDiagnosticsPremiumEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-host-read", wrapper.PostDiagnosticsRequireHostRead)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-host-write", wrapper.PostDiagnosticsRequireHostWrite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-remediation-execute", wrapper.PostDiagnosticsRequireRemediationExecute)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/fleet/liveness", wrapper.GetFleetLiveness)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/fleet/recent-changes", wrapper.GetFleetRecentChanges)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/fleet/score", wrapper.GetFleetScore)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/fleet/top-failing-hosts", wrapper.GetFleetTopFailingHosts)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/fleet/top-failing-rules", wrapper.GetFleetTopFailingRules)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/hosts", wrapper.GetHosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/hosts", wrapper.PostHosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/hosts/{host_id}/credentials:resolve", wrapper.PostHostCredentialsResolve)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/hosts/{id}", wrapper.DeleteHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/hosts/{id}", wrapper.GetHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/hosts/{id}", wrapper.PatchHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/license", wrapper.GetLicense)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/roles", wrapper.GetRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/roles:create", wrapper.PostRolesCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users", wrapper.GetUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users", wrapper.PostUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/users/{id}", wrapper.DeleteUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/users/{id}", wrapper.GetUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users/{id}/roles:assign", wrapper.PostUserRolesAssign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/users/{id}/roles:unassign", wrapper.PostUserRolesUnassign)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F17bxs5kv8qRN8Ca2MkP/IY7CpYHDKeZJO9zIzhJDsHzOYEurskMe4mOyRbji4wcB/iPuF9kgMf/WA3",
	"2d1yLNmzm39mHImPYtWPVcVisfQlilmWMwpUimj2JeIgckYF6H/8gJML+FSAkOpfMaMSqP4T53lKYiwJ",
	"o8cfBaPqMxGvIMPqrz9wWESz6N+O66GPzbfi+AXnjL+ga0hZDtHNzc0kSkDEnORqsGgW/R2nJNEjT1CO",
	"l4TavxlHJIEsZxJovEGgxoluJtFPIFcs+ZnJ52nKriHZH6W/ckaX6NW7d+co00REqo3trkZ/nmSEXrAU",
	"xIXlqvo05ywHLolhMVdfqz+IhEwM0aQGe0El36iVy00O0SzCnOONnprDp4JwxYLf7Lgfqlbs8iPEUnV7",
	"XiREvlhb/rjU4Nis7UvZTUhO6FJ1w7FkfE40f2mRpvgyhWgmeQGTUGPzsWesmHEOqRaKHbHTJAGJSapp",
	"ShKiWuL0vEGrM3G9ODPagvEMy2gWFQVJIg99LI4LziGZY+m0T7CEqSQZ+DpxiBlPtu6UGKa6Qu60c4Wp",
	"+glW8BjGcrxqXzJ9sIeANXAiNx5yWljSPGzJbFJixRG2y9l+9IlzvPRsiIpFozZEA8weJlL4LOdxwQXj",
	"aiB3+/6S408FIPP1M5RjIRAW6N/NB39BkqEFyHiF5AqQGkmpI7XEAc62maeX4dLiZ4xcvWFLQhsa1+UM",
	"k7n6X4Y/vwG6lKto9v0kyght/KsjZLWqa8aTVsdHT92up56uhQBOcQZbd20xoBqnQc0AA0LKEscxCDGX",
	"7Ar8SorDgoNY9bRQ1AyDSq5+goqM9oIcKtpz2hlCC/zp5fMXlLM0DS8y52xNBGGU0OW84GR4f3Z69Mz+",
	"d+BksblDjLVoUQMEp4dz4BkRitQek0gSoNIqpvY3XpkSMceU0U3GiqZyvWQsBUw1LlgKI/Wcbtoa07eg",
	"vF7KNpq9M6VdqztgmINhtkFmDWaXP+OMYoBJriYYwcHGhjc02aFDizq3WuFshekSgtDUdoXKuaPS+lUY",
	"hevxzVtL6UzXGi60mgujDoLLGFJRbT/Oae6b9AxLWDK+MX5hZz7H6AXBMUKszYG8dHDQYMbpGQcsw4LE",
	"hVzNrcescEuLTE0ixGp+BZummZhEl0yuGrM1/UNnWQ2FdXry6MnEqyQSWOAilX4VcStT5xrY7pecrLEE",
	"vayB7zWw8hXHwr8HRcyMX1exayMkZNEkWjEhvSzSXeb+zT/oHd6V9Td0W/Y6uqEJg348vSFChvVeXLUb",
	"7zbWY9dWfkBTN6fpJ7fHf7kL5Md6d213Cin7XG5GWYJxOmNwGGVDY0nW4N9xY3fkve8FK5/5JZFNE0+o",
	"hCXwZouYZZk9WAdHWRC6BJ5zMtAueHou8mRrAGxpwsftWkeETXF790chJMsuWAoD5iGs2cfoYyPiHEsJ",
	"XJ3y/us3PP3vD+o/J9M/zz98OZ18//jmDz4WjXboMkJfmy9PB727lt0c9vJqNoXVyK1MupbPZUFSOSfU",
	"v+HuyqXtLLo58zALXsQrFkRHBkLYuEHH5m9jl8pxwgSElXhC5BzWyjkcqQhHxLsgXjEY4YrZdp0xveug",
	"nwoo4B0I+Td22WNBh8n7yC7HLbZFru03jlwn4No93+iIr4f4ZN9BxspmlfYnTonS+pNIAF8DVxhnKYmV",
	"RYfPShHh1GuVVkWG6bwBaU9AQ/KNMU7dHdv2UBQnSuqaXdsTdZnfBplmtVdGa5wWWMLzFLgMblIRM15u",
	"UZIpHp2enOj9af51MunY0K7byP2b82UKIF8xIV9ikhbcA5QFJimhyzkvUpjHrKCunSRUfv8kmnisuPIe",
	"boXysuPEN3dwEW/IGigI0V0BhTXwec7ZJSQjaeeA41UJlBHtC3pF2TUd3Xq78TuH2LKzO1RNxsRdc5Bn",
	"FxADlSZSIL42eKxHfMcxFTaWPWja9Khh4ooUBlGpsbINKjWUxpzSy4YT31xBot+We7UVhcRCqCEWvL4T",
	"cuPn56YFUtMKdIwObBf0HbLzHyIccyYEwmmKFC3iCJ0cHZ0eKRIrt5UVBgqWPFpkl2bhkkmczsFonNIp",
	"cWk4U2tDbKFHN5tOSCwBcXYt0PUKuA7w60CO+qIQiAgT6mdck+nQMhLOHd74aA0y/B3LXxr+KC12NyBu",
	"6sOvBHFNnoLz3ZDX3BhfS15ju3Z9Aa0X5leEOufrBeFCzgXo8LzGx9y01Ecdew1WfeQ11KMtw46vIIO6",
	"oPc+z6zaBMdLpigQW1WhuHBF8lzzo237+46Jtd2rdY+daeIIY/he8BXgVK56zjyX85hRCrF0vOTG6aW7",
	"xJUec6OPI0uOk4Bw18CF/yjVdkrKpTnE1AN418WEvPWBNxDKTIjIU7yZh+Jz3cMFXRPOaBmaaN7u+MZf",
	"clbktw2WKEzcMpZK8jlOEm5dohaVQ3FYxqXjcX7/9Onjpw2f89RnWyVeuqpsiDXtG+a+MOmwz2hjKo11",
	"hyDUHwJdlYZklEpW440Oe5qhQ2T1RmXvO0rZ3iZD22J3++DWAVRnQwQxPwLXw0DefVDRj3i7DFcaIby9",
	"11Q+WE06oKO+Ck//9MqxI/A3JAYq4K3UIg8qGh0wBR4MrH3OCQfRB+xB3i8Ay4LDlluK0PmS4xjmOXDC",
	"RnstNoau4IJjfYmuV6BBwuapYYraQ3SNU+J3aSQxWS6VB8xBJ2flQK+xjFfzPNWODFCpryIEeIcp9DEn",
	"57BuXWGGQlB63oYPWDHuQ1i+AxkpdsHzj9dyWM80G4+YMphKsTfMBIapMSTmRspe8JRiHiRmrRc85yDc",
	"27a6xTXmlNDlV5HbVvol7e35fZKpM4MCeQyxTXPwm3p11ODB9J9bXpiUaFpiCWOzJCoy23cgNYn9yxcX",
	"sCRC8h542jnIFonDbpKIR1mF7n76Bm3LzJfGuqP05gYLXNonPZnP5ywlMQFxASnDSZi/rJAxy+xtj/di",
	"IKz9AxH1asggXZsfIdZJfH33fre6rhi+ZbDUBZxMRVz4Ntp+Hz5E69i0GHO+LslwJ+1MUQ3o42UNod//",
	"tamL6yYdvpW/F8AHIg1VimDPwfzx7bOI/7SfLOIyqbA3FU9x425Pp1+dX5liUacT2nDjduet3Z/ROmwO",
	"8pal8FwIsgznqytFbL3ybSRddgvNLPpjIWoF4y2OA5OhLWqG9tyeamd/wbr3E28lXgI6Qdc4vSJ0ORVX",
	"kIJkFImCL3AM6P/+53+RXHEABDTJGaFSILnCEsFn4DERgOQK/kEXrKDmURQSEsdX6KBxuz1pPoyaIJ2f",
	"MDEPpBDY6/TDo3/oawoilfMW/ZID/VUdBNCBJfGwEcecRSdHp0cnU5zmK3x0qi1EDhTnJJpFj49Ojh7r",
	"3SdXmr3HOCfH69NjnGSEHlufaWY8Pi0eZsChhKTpfZ1Es+icCanfRzkueWQYDkL+wJLNnT3l8p40blzx",
	"KuNp3tHU798enZzsiobqbUH3AZxqYedAxmNGB6LQjw4Q40iBL9F3VwWHQ/PmrMgyrExe9CPfTHlB0dq8",
	"ogOE0d9+fYesVNA1kStWSESokDhNCV0iYpwVV4q59ZRmXLtKI8To+lbRDhkZ8OI8nDwHPlXcQmYVqHLC",
	"bibRk5PH+3speIbTFDhKcXwlkPFmSs664jNrQkqtQmJbogVJQaAFZ5l+ihQzuiDLgkOCEsIhlua08Xla",
	"Ynla+w3RLOpOV4laKYpjncikhbQEj4D/CrLxZEvve44zkFrJ/vYlUk5R9KkATYMxNPXLsJp9HZXv79l5",
	"ZLb1CM5jtK17C0Jjt+MYKxsaraDSXK7dyWj27dgtVpWSjEinY5V3+/RkUkcFHzlJOp6Y4M2HHe7r9stA",
	"34ZWpootjIlDFrl6M5+ERq/IPW48ZnY3nfInnCHRgeH11L4/hmSCKFyDkEhfJR+2tpFcHadsaY4HPWqy",
	"fN+2IyPXeUC4ZwPXfb/nkaBugLQ1gwSSZ0i/axGICFFAYmR5uj/F/NrEUFEjuV+Z2J9ePkcV4zRYIC7M",
	"3fpvH5rQeW/d5ePSrUcaCNrOIpabIzp698u7cy9kWCFHYUa160juicfdBK31EYc1u4KucVGfGhtijb8w",
	"HbrEmQND2CLI1U8Q7RhMzhPMrujKl3P7xszPzHhXJfMUYC4Bc5so1OS3LDh1+F099/Mw/LgVR+hn/rkb",
	"89qtHHzPNv3+lm2GUtJRsy8WC9BXG6ixULRQHu04Di3wDPTb2eE9Uz2z3TlvOu95fXxpvM9F7y9eI66R",
	"obx4u3q1QLXuGEvGEc7zNu/0HA6j1GEUEaqVi1JYfoaNOoY1Xwbv0Dh1Xh+PMlAeNafUs14YuQeToSZX",
	"LLfXb2r3c8hTvOno2zPlqPMMYYoMbiHRlkVAzEGiy41ZxEZJE6MlUCUYSJDXWpQGZmbiRsMSdV/V7lCs",
	"/ue7t5VtORqywa6Ge7cn9Q7XqLLmHD7qJC8lLJvSv2+8nZn01Zqma85s1KwBNc37jn74o6i6eRBVa+EZ",
	"t3dOQ3bHc02106N+z62Yh1UVSS5zXhZpii5+eH6GymWig/r+aNI0RxOkQ+xTQpG+RvJ4+vZB9vAGtA/B",
	"d7jzWk/NH6K/r3aTdvFRjgm/LzffMspSYjX3BNnEionR4YWARAFDxDgB60IjyclyCRySw95zwAXTWedq",
	"//HmXM9QRqhEWB0fkakb8l3ZQDHEgVfrIXNoH541mu1QvIHn1z4NVbVEGUicYImt/3efYbaamzMOnUCb",
	"PvM3T30HFemMppvDnoBaZ+BJjyJoC+vuFUGo7MIobXC6AzJGQsVewe3dvjfry5U+nH7uPNGPSBBlEunr",
	"FlNyzrZ4+/YVugJr/f+8R2+zSCXJU0DmiTuygTvRtv+amQg3ID0OwdecSAhpoeMvJLkxLloKEroI/1F/",
	"Xgv1h83rHwMh4hzLVR2RNG8GHHB6w6SB13cfxniShrgEHVTv0v+ywKmAQyPEJ3vUSzXqK3S1BPiWLeTU",
	"sPkWUrTyuZmMMBr3J6OT+1M2pXJ/iKJ/qYvMNYX+R1ETvIUdamzihOAlZUKSWMwgXrF+b/XHuvUL1diP",
	"jhXgRGd3Wny8ri+dp/8Bm16wOJkfTwczPwIz/uf0rL4fmr7uvx/6sBtz2yxOsGeH2ylL4MGa+r4Ord/q",
	"XkR1eTrcpVNzdd9msYW90nvXYfeELBagj8yXSvCtQJrikXHT9ZKRTYt7ViVcCKfM7HfmYii8uUyJhakE",
	"Iacf2eX4jebUZug68o/ujpn+KhAerv6NXepDSi4heYauGb8Cjq5JmqKEY0LbJkviJUxPkB4dJZCxZ8iy",
	"Q6gTD5uyHH1klyjnTB18TBRF8Z7Qqf3MThJmry03MMUpcDmeuc0qBTvyu72VEPasEQKJo74QtEklSGzT",
	"gCjzspWWpV2gMBFqtcy5XKmjK0sTUYXDApLLOWSkyKZbWZ9z0+lBGKF/TftR6vJH+9PlNjEKJQyEdpII",
	"jdMiAWQhNG/ACtlXFZ3TvB5iqhP1kYLcs/L+VvQO43hX5YezyNMlCHTbfaoOj1PtiI1F+4Xpad5R6pyp",
	"b4i/D8Sjg9gEjoxiU4LUHvXh/QawKjoCylpHtI2qrrBe9WkEtXuOEO4Ug+g2wYJbwPtX3fEbvh8OvrUo",
	"HwLA6wDUFgjXnbaAeDfK5cM4hwwSYg6X8BniYnuwX9RDvLAjfEP9v7of08DV3ODK1pq6v63XIGlWQj28",
	"B78r08dbe9EzCvrOv9whj8vPo/C2Di2g3N+LFEAep40Ka6HIqFuKbYewdSfyAsh8hzhL0yLf+y3p8zoJ",
	"ySQRlgmQ94lUc+/R8WlcsCofA+k6ZwJdbpAtMEdSIjfIvkXvgoPrUnLTuK4l1wsRt/JcR6u7S3hJUgkc",
	"SYZkXa9KIKWUY5ludDYxR3KFKZIrItDFy7PHjx//GUmSgZA4y/X7/l3np4/NCz89udfEcA/7vXf8qkGT",
	"3+b3Wm4bBv228UZsvC7TBTowFfjsvjp0U+c9+7AqFtq7/UyZwl2jzMziYY3+FhlSv8FjLDw016bXJAGk",
	"JkwJpjEYLlblIo916cRDDzAky6e2kuS0qnDVC5J2acVRr5V+T1qwvUCfHsT0ChKTy2AfCYpvSnDX3ocw",
	"d09yBSgrOV8XRz1QUwBNCF0OAZ2XRTdHAt0U6fwnBrpZYBjoimHfgL4fa6/B7Ae6VtBhoJtSnH24NgVA",
	"d2nhWyVGPSx5C3xNYkBEoLJ26M0kerpPqTRIKIuWIsZRQfEaE1N7qS8RtTpDqnM4Toj+WxfVRgfV75m1",
	"RDNkWrewpc3yeLd4qCrxcjinY1foaFfZ9AhHnzPvP7U1dDOgk1pXVlojYv59iaul0HcRO+zWxN1zsqpb",
	"ATUg5/tPUC3NGjq4xMajU/tkgkg+QTnjcoJAxkeHe8++eWUpQThVQNog+EyU9icUNRVAIEVV/0bT1gF7",
	"DevjL7bi9E0zTXXGQbB0PRCsf+VmY1/YPmMyIRtlrn/H6ZB2xc3HzveXF/kza5JR2Tb9IFIfXRhvpTx3",
	"Ig96NebJUz2Srp2jU5YuAemcMDXiIOj6cikt8kalQiuQPcwkaEN3MscSCZD7z4F+5eTW92Y/j1EQwxnP",
	"9yuKk73aqoclzTKheYwcK0cEy3jlUdzq471Lcjcej1u7es93pqM8nvt6ctv1eB4WoI3kUFZIbaNMaI1A",
	"mojt/ZiyfnPPeetNVeJ518XI3NLaPXfaOqTf4spfQRrrax8op8226EAS4JPy2ldM0KeCSSwm9j7OPYJW",
	"VWJDLLlgJsq1u8esSUaonqXXhWIpPIDzn2JX8PznPmDuu0J3RnFEMTNnn36HWnPLePW7etoY+MnQfT9t",
	"7P4kp/edvmqluX5vR8dGAZbyh9X2fTbUW4QkSOIroMFXijWvhgDa1aBVgc+QstBFQnepLLpVSD2MUI0e",
	"gK5Q3ArqisJyKiSBRue+WFHN8LvXAd2qxnve/W6F2ICcH0CsiPGqXmTTh7pX3PmSOysloFoMYS+w+0ee",
	"xpVoHuJpfO/ercbouMP3GKkMH77vl/Mne938D0ua5eF7jBw7zl+9uawfiHWF734/sKwGLkw58N/xKd1f",
	"1/y2lay0J2QYeA+W4b3x/4w/StooMStE2Hwt2TBgtDNm4dALmYJuBZr3ZfNvsGnAhkPG1rp2RfkuQB52",
	"AuCqSSlCXR16SyHelL9X7stgfcNinKIENMLsfW7B02gWraTMxez4OFUtdJTjT0+ePI5uPtz8fwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
