// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CredentialCreateRequestAuthMethod.
const (
	CredentialCreateRequestAuthMethodBoth     CredentialCreateRequestAuthMethod = "both"
	CredentialCreateRequestAuthMethodPassword CredentialCreateRequestAuthMethod = "password"
	CredentialCreateRequestAuthMethodSshKey   CredentialCreateRequestAuthMethod = "ssh_key"
)

// Valid indicates whether the value is a known member of the CredentialCreateRequestAuthMethod enum.
func (e CredentialCreateRequestAuthMethod) Valid() bool {
	switch e {
	case CredentialCreateRequestAuthMethodBoth:
		return true
	case CredentialCreateRequestAuthMethodPassword:
		return true
	case CredentialCreateRequestAuthMethodSshKey:
		return true
	default:
		return false
	}
}

// Defines values for CredentialCreateRequestScope.
const (
	CredentialCreateRequestScopeHost   CredentialCreateRequestScope = "host"
	CredentialCreateRequestScopeSystem CredentialCreateRequestScope = "system"
)

// Valid indicates whether the value is a known member of the CredentialCreateRequestScope enum.
func (e CredentialCreateRequestScope) Valid() bool {
	switch e {
	case CredentialCreateRequestScopeHost:
		return true
	case CredentialCreateRequestScopeSystem:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResponseAuthMethod.
const (
	CredentialResponseAuthMethodBoth     CredentialResponseAuthMethod = "both"
	CredentialResponseAuthMethodPassword CredentialResponseAuthMethod = "password"
	CredentialResponseAuthMethodSshKey   CredentialResponseAuthMethod = "ssh_key"
)

// Valid indicates whether the value is a known member of the CredentialResponseAuthMethod enum.
func (e CredentialResponseAuthMethod) Valid() bool {
	switch e {
	case CredentialResponseAuthMethodBoth:
		return true
	case CredentialResponseAuthMethodPassword:
		return true
	case CredentialResponseAuthMethodSshKey:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResponseScope.
const (
	CredentialResponseScopeHost   CredentialResponseScope = "host"
	CredentialResponseScopeSystem CredentialResponseScope = "system"
)

// Valid indicates whether the value is a known member of the CredentialResponseScope enum.
func (e CredentialResponseScope) Valid() bool {
	switch e {
	case CredentialResponseScopeHost:
		return true
	case CredentialResponseScopeSystem:
		return true
	default:
		return false
	}
}

// Defines values for ErrorEnvelopeErrorFault.
const (
	Client   ErrorEnvelopeErrorFault = "client"
	External ErrorEnvelopeErrorFault = "external"
	Policy   ErrorEnvelopeErrorFault = "policy"
	Server   ErrorEnvelopeErrorFault = "server"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorFault enum.
func (e ErrorEnvelopeErrorFault) Valid() bool {
	switch e {
	case Client:
		return true
	case External:
		return true
	case Policy:
		return true
	case Server:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Healthy  HealthResponseStatus = "healthy"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Healthy:
		return true
	default:
		return false
	}
}

// Defines values for LicenseStateResponseStatus.
const (
	Active    LicenseStateResponseStatus = "active"
	Expired   LicenseStateResponseStatus = "expired"
	Grace     LicenseStateResponseStatus = "grace"
	Invalid   LicenseStateResponseStatus = "invalid"
	NoLicense LicenseStateResponseStatus = "no_license"
)

// Valid indicates whether the value is a known member of the LicenseStateResponseStatus enum.
func (e LicenseStateResponseStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Expired:
		return true
	case Grace:
		return true
	case Invalid:
		return true
	case NoLicense:
		return true
	default:
		return false
	}
}

// Defines values for LicenseStateResponseTier.
const (
	Enterprise    LicenseStateResponseTier = "enterprise"
	Free          LicenseStateResponseTier = "free"
	OpenwatchPlus LicenseStateResponseTier = "openwatch_plus"
)

// Valid indicates whether the value is a known member of the LicenseStateResponseTier enum.
func (e LicenseStateResponseTier) Valid() bool {
	switch e {
	case Enterprise:
		return true
	case Free:
		return true
	case OpenwatchPlus:
		return true
	default:
		return false
	}
}

// AdminRolesResponse defines model for AdminRolesResponse.
type AdminRolesResponse struct {
	Roles []RoleEntry `json:"roles"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action        string                  `json:"action"`
	ActorId       *string                 `json:"actor_id,omitempty"`
	ActorType     string                  `json:"actor_type"`
	CorrelationId string                  `json:"correlation_id"`
	Detail        *map[string]interface{} `json:"detail,omitempty"`
	Id            openapi_types.UUID      `json:"id"`
	OccurredAt    time.Time               `json:"occurred_at"`
	RecordedAt    *time.Time              `json:"recorded_at,omitempty"`
	Redactions    *[]string               `json:"redactions,omitempty"`
	ResourceId    *string                 `json:"resource_id,omitempty"`
	ResourceType  *string                 `json:"resource_type,omitempty"`
	Severity      *string                 `json:"severity,omitempty"`
}

// AuditEventsPage defines model for AuditEventsPage.
type AuditEventsPage struct {
	Items []AuditEvent `json:"items"`

	// NextCursor Opaque cursor; pass as ?cursor= to fetch the next page
	NextCursor *string `json:"next_cursor"`
}

// AuthLoginRequest defines model for AuthLoginRequest.
type AuthLoginRequest struct {
	Otp      *string `json:"otp,omitempty"`
	Password string  `json:"password"`
	Username string  `json:"username"`
}

// AuthLoginResponse defines model for AuthLoginResponse.
type AuthLoginResponse struct {
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	User         AuthMeResponse `json:"user"`
}

// AuthMFAEnrollResponse defines model for AuthMFAEnrollResponse.
type AuthMFAEnrollResponse struct {
	ProvisioningUri string `json:"provisioning_uri"`
}

// AuthMFAVerifyRequest defines model for AuthMFAVerifyRequest.
type AuthMFAVerifyRequest struct {
	Otp string `json:"otp"`
}

// AuthMePermissionsResponse defines model for AuthMePermissionsResponse.
type AuthMePermissionsResponse struct {
	Identity struct {
		Id          string `json:"id"`
		IsAnonymous bool   `json:"is_anonymous"`
		Role        string `json:"role"`
	} `json:"identity"`
	Permissions []string `json:"permissions"`
}

// AuthMeResponse defines model for AuthMeResponse.
type AuthMeResponse struct {
	Email    string             `json:"email"`
	Id       openapi_types.UUID `json:"id"`
	IsAdmin  bool               `json:"is_admin"`
	Role     string             `json:"role"`
	Username string             `json:"username"`
}

// AuthPasswordChangeRequest defines model for AuthPasswordChangeRequest.
type AuthPasswordChangeRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// AuthRefreshRequest defines model for AuthRefreshRequest.
type AuthRefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// CategoryEntry defines model for CategoryEntry.
type CategoryEntry struct {
	Description string `json:"description"`
	Id          string `json:"id"`
}

// CredentialCreateRequest defines model for CredentialCreateRequest.
type CredentialCreateRequest struct {
	AuthMethod           CredentialCreateRequestAuthMethod `json:"auth_method"`
	Description          *string                           `json:"description,omitempty"`
	IsDefault            *bool                             `json:"is_default,omitempty"`
	Name                 string                            `json:"name"`
	Password             *string                           `json:"password,omitempty"`
	PrivateKey           *string                           `json:"private_key,omitempty"`
	PrivateKeyPassphrase *string                           `json:"private_key_passphrase,omitempty"`
	Scope                CredentialCreateRequestScope      `json:"scope"`
	ScopeId              *openapi_types.UUID               `json:"scope_id,omitempty"`
	Username             string                            `json:"username"`
}

// CredentialCreateRequestAuthMethod defines model for CredentialCreateRequest.AuthMethod.
type CredentialCreateRequestAuthMethod string

// CredentialCreateRequestScope defines model for CredentialCreateRequest.Scope.
type CredentialCreateRequestScope string

// CredentialListResponse defines model for CredentialListResponse.
type CredentialListResponse struct {
	Credentials []CredentialResponse `json:"credentials"`
}

// CredentialResponse defines model for CredentialResponse.
type CredentialResponse struct {
	AuthMethod        CredentialResponseAuthMethod `json:"auth_method"`
	CreatedAt         *time.Time                   `json:"created_at,omitempty"`
	CreatedBy         *openapi_types.UUID          `json:"created_by,omitempty"`
	Description       *string                      `json:"description,omitempty"`
	Id                openapi_types.UUID           `json:"id"`
	IsActive          bool                         `json:"is_active"`
	IsDefault         bool                         `json:"is_default"`
	Name              string                       `json:"name"`
	Scope             CredentialResponseScope      `json:"scope"`
	ScopeId           *openapi_types.UUID          `json:"scope_id,omitempty"`
	SshKeyBits        *int                         `json:"ssh_key_bits,omitempty"`
	SshKeyComment     *string                      `json:"ssh_key_comment,omitempty"`
	SshKeyFingerprint *string                      `json:"ssh_key_fingerprint,omitempty"`
	SshKeyType        *string                      `json:"ssh_key_type,omitempty"`
	UpdatedAt         *time.Time                   `json:"updated_at,omitempty"`
	Username          string                       `json:"username"`
}

// CredentialResponseAuthMethod defines model for CredentialResponse.AuthMethod.
type CredentialResponseAuthMethod string

// CredentialResponseScope defines model for CredentialResponse.Scope.
type CredentialResponseScope string

// CustomRoleCreateRequest defines model for CustomRoleCreateRequest.
type CustomRoleCreateRequest struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	Permissions []string `json:"permissions"`
}

// CustomRoleResponse defines model for CustomRoleResponse.
type CustomRoleResponse struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	IsBuiltIn   bool     `json:"is_built_in"`
	Permissions []string `json:"permissions"`
}

// EchoRequest defines model for EchoRequest.
type EchoRequest struct {
	Message string `json:"message"`
}

// EchoResponse defines model for EchoResponse.
type EchoResponse struct {
	AuditEventId  *openapi_types.UUID `json:"audit_event_id,omitempty"`
	CorrelationId string              `json:"correlation_id"`
	Echoed        string              `json:"echoed"`
}

// EnqueueTestJobResponse defines model for EnqueueTestJobResponse.
type EnqueueTestJobResponse struct {
	CorrelationId string             `json:"correlation_id"`
	JobId         openapi_types.UUID `json:"job_id"`
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Code          string                  `json:"code"`
		CorrelationId *string                 `json:"correlation_id,omitempty"`
		Detail        *map[string]interface{} `json:"detail,omitempty"`
		Fault         ErrorEnvelopeErrorFault `json:"fault"`
		HumanMessage  string                  `json:"human_message"`
		Retryable     bool                    `json:"retryable"`
	} `json:"error"`
}

// ErrorEnvelopeErrorFault defines model for ErrorEnvelope.Error.Fault.
type ErrorEnvelopeErrorFault string

// EvaluateAlertRequest defines model for EvaluateAlertRequest.
type EvaluateAlertRequest struct {
	Score int `json:"score"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	DbConnected bool                 `json:"db_connected"`
	Status      HealthResponseStatus `json:"status"`
	Version     string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HostCreateRequest defines model for HostCreateRequest.
type HostCreateRequest struct {
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment *string             `json:"environment,omitempty"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	Hostname    string              `json:"hostname"`
	IpAddress   string              `json:"ip_address"`
	Port        *int                `json:"port,omitempty"`
	Tags        *[]string           `json:"tags,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// HostListResponse defines model for HostListResponse.
type HostListResponse struct {
	Hosts []HostResponse `json:"hosts"`
}

// HostResponse defines model for HostResponse.
type HostResponse struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	CreatedBy   *openapi_types.UUID `json:"created_by,omitempty"`
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment string              `json:"environment"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	Hostname    string              `json:"hostname"`
	Id          openapi_types.UUID  `json:"id"`
	IpAddress   string              `json:"ip_address"`
	Port        int                 `json:"port"`
	Tags        *[]string           `json:"tags,omitempty"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// HostUpdateRequest defines model for HostUpdateRequest.
type HostUpdateRequest struct {
	Description *string             `json:"description,omitempty"`
	DisplayName *string             `json:"display_name,omitempty"`
	Environment *string             `json:"environment,omitempty"`
	GroupId     *openapi_types.UUID `json:"group_id,omitempty"`
	IpAddress   *string             `json:"ip_address,omitempty"`
	Port        *int                `json:"port,omitempty"`
	Tags        *[]string           `json:"tags,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// LicenseStateResponse defines model for LicenseStateResponse.
type LicenseStateResponse struct {
	CustomerId    *string                    `json:"customer_id,omitempty"`
	ExpiresAt     *time.Time                 `json:"expires_at,omitempty"`
	Features      []string                   `json:"features"`
	InGracePeriod *bool                      `json:"in_grace_period,omitempty"`
	Status        LicenseStateResponseStatus `json:"status"`
	Tier          LicenseStateResponseTier   `json:"tier"`
	UsingPrevKey  *bool                      `json:"using_prev_key,omitempty"`
}

// LicenseStateResponseStatus defines model for LicenseStateResponse.Status.
type LicenseStateResponseStatus string

// LicenseStateResponseTier defines model for LicenseStateResponse.Tier.
type LicenseStateResponseTier string

// LicenseVerifyRequest defines model for LicenseVerifyRequest.
type LicenseVerifyRequest struct {
	LicenseJwt string `json:"license_jwt"`
}

// LicenseVerifyResponse defines model for LicenseVerifyResponse.
type LicenseVerifyResponse struct {
	ExpiresAt    *time.Time `json:"expires_at,omitempty"`
	Features     *[]string  `json:"features,omitempty"`
	IsValid      bool       `json:"is_valid"`
	Tier         *string    `json:"tier,omitempty"`
	VerifyResult string     `json:"verify_result"`
	Warnings     *[]string  `json:"warnings,omitempty"`
}

// PermissionEntry defines model for PermissionEntry.
type PermissionEntry struct {
	Category     string  `json:"category"`
	Dangerous    bool    `json:"dangerous"`
	Description  string  `json:"description"`
	Id           string  `json:"id"`
	LicenseGated *string `json:"license_gated,omitempty"`
}

// PermissionsRegistryResponse defines model for PermissionsRegistryResponse.
type PermissionsRegistryResponse struct {
	Categories  []CategoryEntry   `json:"categories"`
	Permissions []PermissionEntry `json:"permissions"`
	Roles       []RoleEntry       `json:"roles"`
}

// PoliciesReloadResponse defines model for PoliciesReloadResponse.
type PoliciesReloadResponse struct {
	Outcomes map[string]string `json:"outcomes"`
}

// PolicyDecisionResponse defines model for PolicyDecisionResponse.
type PolicyDecisionResponse struct {
	Detail        *map[string]interface{} `json:"detail,omitempty"`
	HumanMessage  *string                 `json:"human_message,omitempty"`
	Outcome       string                  `json:"outcome"`
	PolicyType    string                  `json:"policy_type"`
	PolicyVersion string                  `json:"policy_version"`
	Reason        string                  `json:"reason"`
}

// RoleEntry defines model for RoleEntry.
type RoleEntry struct {
	Description string   `json:"description"`
	Id          string   `json:"id"`
	IsBuiltIn   bool     `json:"is_built_in"`
	Permissions []string `json:"permissions"`
}

// UserCreateRequest defines model for UserCreateRequest.
type UserCreateRequest struct {
	Email    string `json:"email"`
	IsAdmin  *bool  `json:"is_admin,omitempty"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt            *time.Time         `json:"created_at,omitempty"`
	Email                string             `json:"email"`
	Id                   openapi_types.UUID `json:"id"`
	IsAdmin              bool               `json:"is_admin"`
	LastPasswordChangeAt *time.Time         `json:"last_password_change_at,omitempty"`
	UpdatedAt            *time.Time         `json:"updated_at,omitempty"`
	Username             string             `json:"username"`
}

// UserRoleAssignRequest defines model for UserRoleAssignRequest.
type UserRoleAssignRequest struct {
	RoleId string `json:"role_id"`
}

// UsersListResponse defines model for UsersListResponse.
type UsersListResponse struct {
	Users []UserResponse `json:"users"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorEnvelope

// MethodNotAllowed defines model for MethodNotAllowed.
type MethodNotAllowed = ErrorEnvelope

// GetAdminHostsParams defines parameters for GetAdminHosts.
type GetAdminHostsParams struct {
	Environment *string `form:"environment,omitempty" json:"environment,omitempty"`
	Tag         *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// GetAuditEventsParams defines parameters for GetAuditEvents.
type GetAuditEventsParams struct {
	Action        *string    `form:"action,omitempty" json:"action,omitempty"`
	CorrelationId *string    `form:"correlation_id,omitempty" json:"correlation_id,omitempty"`
	ActorType     *string    `form:"actor_type,omitempty" json:"actor_type,omitempty"`
	Since         *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Until         *time.Time `form:"until,omitempty" json:"until,omitempty"`
	Cursor        *string    `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit         *int       `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostDiagnosticsEchoParams defines parameters for PostDiagnosticsEcho.
type PostDiagnosticsEchoParams struct {
	IdempotencyKey string  `json:"Idempotency-Key"`
	XCorrelationId *string `json:"X-Correlation-Id,omitempty"`
}

// PostDiagnosticsPremiumEchoParams defines parameters for PostDiagnosticsPremiumEcho.
type PostDiagnosticsPremiumEchoParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireHostReadParams defines parameters for PostDiagnosticsRequireHostRead.
type PostDiagnosticsRequireHostReadParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireHostWriteParams defines parameters for PostDiagnosticsRequireHostWrite.
type PostDiagnosticsRequireHostWriteParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostDiagnosticsRequireRemediationExecuteParams defines parameters for PostDiagnosticsRequireRemediationExecute.
type PostDiagnosticsRequireRemediationExecuteParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PostAdminCredentialsJSONRequestBody defines body for PostAdminCredentials for application/json ContentType.
type PostAdminCredentialsJSONRequestBody = CredentialCreateRequest

// PostAdminHostsJSONRequestBody defines body for PostAdminHosts for application/json ContentType.
type PostAdminHostsJSONRequestBody = HostCreateRequest

// PatchAdminHostByIDJSONRequestBody defines body for PatchAdminHostByID for application/json ContentType.
type PatchAdminHostByIDJSONRequestBody = HostUpdateRequest

// PostAdminLicenseVerifyJSONRequestBody defines body for PostAdminLicenseVerify for application/json ContentType.
type PostAdminLicenseVerifyJSONRequestBody = LicenseVerifyRequest

// PostAdminRolesCreateJSONRequestBody defines body for PostAdminRolesCreate for application/json ContentType.
type PostAdminRolesCreateJSONRequestBody = CustomRoleCreateRequest

// PostAdminUsersJSONRequestBody defines body for PostAdminUsers for application/json ContentType.
type PostAdminUsersJSONRequestBody = UserCreateRequest

// PostAdminUserRolesAssignJSONRequestBody defines body for PostAdminUserRolesAssign for application/json ContentType.
type PostAdminUserRolesAssignJSONRequestBody = UserRoleAssignRequest

// PostAdminUserRolesUnassignJSONRequestBody defines body for PostAdminUserRolesUnassign for application/json ContentType.
type PostAdminUserRolesUnassignJSONRequestBody = UserRoleAssignRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = AuthLoginRequest

// PostAuthMFAVerifyJSONRequestBody defines body for PostAuthMFAVerify for application/json ContentType.
type PostAuthMFAVerifyJSONRequestBody = AuthMFAVerifyRequest

// PostAuthPasswordChangeJSONRequestBody defines body for PostAuthPasswordChange for application/json ContentType.
type PostAuthPasswordChangeJSONRequestBody = AuthPasswordChangeRequest

// PostAuthRefreshJSONRequestBody defines body for PostAuthRefresh for application/json ContentType.
type PostAuthRefreshJSONRequestBody = AuthRefreshRequest

// PostDiagnosticsEchoJSONRequestBody defines body for PostDiagnosticsEcho for application/json ContentType.
type PostDiagnosticsEchoJSONRequestBody = EchoRequest

// PostDiagnosticsEvaluateAlertJSONRequestBody defines body for PostDiagnosticsEvaluateAlert for application/json ContentType.
type PostDiagnosticsEvaluateAlertJSONRequestBody = EvaluateAlertRequest

// PostDiagnosticsPremiumEchoJSONRequestBody defines body for PostDiagnosticsPremiumEcho for application/json ContentType.
type PostDiagnosticsPremiumEchoJSONRequestBody = EchoRequest

// PostDiagnosticsRequireHostReadJSONRequestBody defines body for PostDiagnosticsRequireHostRead for application/json ContentType.
type PostDiagnosticsRequireHostReadJSONRequestBody = EchoRequest

// PostDiagnosticsRequireHostWriteJSONRequestBody defines body for PostDiagnosticsRequireHostWrite for application/json ContentType.
type PostDiagnosticsRequireHostWriteJSONRequestBody = EchoRequest

// PostDiagnosticsRequireRemediationExecuteJSONRequestBody defines body for PostDiagnosticsRequireRemediationExecute for application/json ContentType.
type PostDiagnosticsRequireRemediationExecuteJSONRequestBody = EchoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List credentials (metadata only)
	// (GET /api/v1/admin/credentials)
	GetAdminCredentials(w http.ResponseWriter, r *http.Request)
	// Create a credential
	// (POST /api/v1/admin/credentials)
	PostAdminCredentials(w http.ResponseWriter, r *http.Request)
	// Soft-delete a credential
	// (DELETE /api/v1/admin/credentials/{id})
	DeleteAdminCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a credential's metadata
	// (GET /api/v1/admin/credentials/{id})
	GetAdminCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List hosts
	// (GET /api/v1/admin/hosts)
	GetAdminHosts(w http.ResponseWriter, r *http.Request, params GetAdminHostsParams)
	// Create a host
	// (POST /api/v1/admin/hosts)
	PostAdminHosts(w http.ResponseWriter, r *http.Request)
	// Resolve the credential that will be used for a host
	// (POST /api/v1/admin/hosts/{host_id}/credentials:resolve)
	PostAdminHostCredentialsResolve(w http.ResponseWriter, r *http.Request, hostId openapi_types.UUID)
	// Soft-delete a host
	// (DELETE /api/v1/admin/hosts/{id})
	DeleteAdminHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a host
	// (GET /api/v1/admin/hosts/{id})
	GetAdminHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update mutable host fields
	// (PATCH /api/v1/admin/hosts/{id})
	PatchAdminHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Dry-run validate a JWT license without installing it
	// (POST /api/v1/admin/license:verify)
	PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request)
	// Reload signed policy files from the configured directory
	// (POST /api/v1/admin/policies:reload)
	PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request)
	// List built-in roles
	// (GET /api/v1/admin/roles)
	GetAdminRoles(w http.ResponseWriter, r *http.Request)
	// Create a custom role
	// (POST /api/v1/admin/roles:create)
	PostAdminRolesCreate(w http.ResponseWriter, r *http.Request)
	// List users
	// (GET /api/v1/admin/users)
	GetAdminUsers(w http.ResponseWriter, r *http.Request)
	// Create a user
	// (POST /api/v1/admin/users)
	PostAdminUsers(w http.ResponseWriter, r *http.Request)
	// Soft-delete a user
	// (DELETE /api/v1/admin/users/{id})
	DeleteAdminUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Fetch a user
	// (GET /api/v1/admin/users/{id})
	GetAdminUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Assign a role to a user
	// (POST /api/v1/admin/users/{id}/roles:assign)
	PostAdminUserRolesAssign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove a role from a user
	// (POST /api/v1/admin/users/{id}/roles:unassign)
	PostAdminUserRolesUnassign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List audit events (cursor-paginated, newest first)
	// (GET /api/v1/audit/events)
	GetAuditEvents(w http.ResponseWriter, r *http.Request, params GetAuditEventsParams)
	// Username/password login with optional TOTP
	// (POST /api/v1/auth/login)
	PostAuthLogin(w http.ResponseWriter, r *http.Request)
	// Revoke the calling session
	// (POST /api/v1/auth/logout)
	PostAuthLogout(w http.ResponseWriter, r *http.Request)
	// Return the calling identity
	// (GET /api/v1/auth/me)
	GetAuthMe(w http.ResponseWriter, r *http.Request)
	// Effective permissions for the calling identity
	// (GET /api/v1/auth/me/permissions)
	GetAuthMePermissions(w http.ResponseWriter, r *http.Request)
	// Enroll the calling user in TOTP MFA
	// (POST /api/v1/auth/mfa:enroll)
	PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request)
	// Confirm an enrolled MFA secret by verifying a generated OTP
	// (POST /api/v1/auth/mfa:verify)
	PostAuthMFAVerify(w http.ResponseWriter, r *http.Request)
	// Change the calling user's password
	// (POST /api/v1/auth/password:change)
	PostAuthPasswordChange(w http.ResponseWriter, r *http.Request)
	// Full RBAC registry (categories, permissions, built-in roles)
	// (GET /api/v1/auth/permissions:registry)
	GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request)
	// Rotate the refresh token; mint a new access+refresh pair
	// (POST /api/v1/auth/refresh)
	PostAuthRefresh(w http.ResponseWriter, r *http.Request)
	// Echo the request message; exercises idempotency + audit
	// (POST /api/v1/diagnostics:echo)
	PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsEchoParams)
	// Stage-0 queue demo; enqueues a no-op job processed by the in-process worker
	// (POST /api/v1/diagnostics:enqueue-test-job)
	PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request)
	// Stage-0 policy demo; evaluates the alert_thresholds policy
	// (POST /api/v1/diagnostics:evaluate-alert)
	PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request)
	// License-gated echo; requires premium_diagnostics feature
	// (POST /api/v1/diagnostics:premium-echo)
	PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsPremiumEchoParams)
	// Stage-0 RBAC demo; requires host:read permission
	// (POST /api/v1/diagnostics:require-host-read)
	PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostReadParams)
	// Stage-0 RBAC demo; requires host:write permission
	// (POST /api/v1/diagnostics:require-host-write)
	PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostWriteParams)
	// Stage-0 RBAC+license demo; requires remediation:execute + remediation_execution feature
	// (POST /api/v1/diagnostics:require-remediation-execute)
	PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireRemediationExecuteParams)
	// Liveness + readiness probe (anonymous)
	// (GET /api/v1/health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Get the current license state (tier, features, quotas, status)
	// (GET /api/v1/license)
	GetLicense(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List credentials (metadata only)
// (GET /api/v1/admin/credentials)
func (_ Unimplemented) GetAdminCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a credential
// (POST /api/v1/admin/credentials)
func (_ Unimplemented) PostAdminCredentials(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a credential
// (DELETE /api/v1/admin/credentials/{id})
func (_ Unimplemented) DeleteAdminCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a credential's metadata
// (GET /api/v1/admin/credentials/{id})
func (_ Unimplemented) GetAdminCredentialByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List hosts
// (GET /api/v1/admin/hosts)
func (_ Unimplemented) GetAdminHosts(w http.ResponseWriter, r *http.Request, params GetAdminHostsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a host
// (POST /api/v1/admin/hosts)
func (_ Unimplemented) PostAdminHosts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Resolve the credential that will be used for a host
// (POST /api/v1/admin/hosts/{host_id}/credentials:resolve)
func (_ Unimplemented) PostAdminHostCredentialsResolve(w http.ResponseWriter, r *http.Request, hostId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a host
// (DELETE /api/v1/admin/hosts/{id})
func (_ Unimplemented) DeleteAdminHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a host
// (GET /api/v1/admin/hosts/{id})
func (_ Unimplemented) GetAdminHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update mutable host fields
// (PATCH /api/v1/admin/hosts/{id})
func (_ Unimplemented) PatchAdminHostByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Dry-run validate a JWT license without installing it
// (POST /api/v1/admin/license:verify)
func (_ Unimplemented) PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reload signed policy files from the configured directory
// (POST /api/v1/admin/policies:reload)
func (_ Unimplemented) PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List built-in roles
// (GET /api/v1/admin/roles)
func (_ Unimplemented) GetAdminRoles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a custom role
// (POST /api/v1/admin/roles:create)
func (_ Unimplemented) PostAdminRolesCreate(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /api/v1/admin/users)
func (_ Unimplemented) GetAdminUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a user
// (POST /api/v1/admin/users)
func (_ Unimplemented) PostAdminUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a user
// (DELETE /api/v1/admin/users/{id})
func (_ Unimplemented) DeleteAdminUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fetch a user
// (GET /api/v1/admin/users/{id})
func (_ Unimplemented) GetAdminUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign a role to a user
// (POST /api/v1/admin/users/{id}/roles:assign)
func (_ Unimplemented) PostAdminUserRolesAssign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a role from a user
// (POST /api/v1/admin/users/{id}/roles:unassign)
func (_ Unimplemented) PostAdminUserRolesUnassign(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List audit events (cursor-paginated, newest first)
// (GET /api/v1/audit/events)
func (_ Unimplemented) GetAuditEvents(w http.ResponseWriter, r *http.Request, params GetAuditEventsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Username/password login with optional TOTP
// (POST /api/v1/auth/login)
func (_ Unimplemented) PostAuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke the calling session
// (POST /api/v1/auth/logout)
func (_ Unimplemented) PostAuthLogout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Return the calling identity
// (GET /api/v1/auth/me)
func (_ Unimplemented) GetAuthMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Effective permissions for the calling identity
// (GET /api/v1/auth/me/permissions)
func (_ Unimplemented) GetAuthMePermissions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Enroll the calling user in TOTP MFA
// (POST /api/v1/auth/mfa:enroll)
func (_ Unimplemented) PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm an enrolled MFA secret by verifying a generated OTP
// (POST /api/v1/auth/mfa:verify)
func (_ Unimplemented) PostAuthMFAVerify(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change the calling user's password
// (POST /api/v1/auth/password:change)
func (_ Unimplemented) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Full RBAC registry (categories, permissions, built-in roles)
// (GET /api/v1/auth/permissions:registry)
func (_ Unimplemented) GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotate the refresh token; mint a new access+refresh pair
// (POST /api/v1/auth/refresh)
func (_ Unimplemented) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Echo the request message; exercises idempotency + audit
// (POST /api/v1/diagnostics:echo)
func (_ Unimplemented) PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsEchoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 queue demo; enqueues a no-op job processed by the in-process worker
// (POST /api/v1/diagnostics:enqueue-test-job)
func (_ Unimplemented) PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 policy demo; evaluates the alert_thresholds policy
// (POST /api/v1/diagnostics:evaluate-alert)
func (_ Unimplemented) PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// License-gated echo; requires premium_diagnostics feature
// (POST /api/v1/diagnostics:premium-echo)
func (_ Unimplemented) PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request, params PostDiagnosticsPremiumEchoParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC demo; requires host:read permission
// (POST /api/v1/diagnostics:require-host-read)
func (_ Unimplemented) PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostReadParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC demo; requires host:write permission
// (POST /api/v1/diagnostics:require-host-write)
func (_ Unimplemented) PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireHostWriteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Stage-0 RBAC+license demo; requires remediation:execute + remediation_execution feature
// (POST /api/v1/diagnostics:require-remediation-execute)
func (_ Unimplemented) PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request, params PostDiagnosticsRequireRemediationExecuteParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness + readiness probe (anonymous)
// (GET /api/v1/health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the current license state (tier, features, quotas, status)
// (GET /api/v1/license)
func (_ Unimplemented) GetLicense(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAdminCredentials operation middleware
func (siw *ServerInterfaceWrapper) GetAdminCredentials(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminCredentials operation middleware
func (siw *ServerInterfaceWrapper) PostAdminCredentials(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminCredentials(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminCredentialByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminCredentialByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminCredentialByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminCredentialByID operation middleware
func (siw *ServerInterfaceWrapper) GetAdminCredentialByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminCredentialByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminHosts operation middleware
func (siw *ServerInterfaceWrapper) GetAdminHosts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminHostsParams

	// ------------- Optional query parameter "environment" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "environment", r.URL.Query(), &params.Environment, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "environment"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "environment", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", r.URL.Query(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tag"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminHosts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminHosts operation middleware
func (siw *ServerInterfaceWrapper) PostAdminHosts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminHosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminHostCredentialsResolve operation middleware
func (siw *ServerInterfaceWrapper) PostAdminHostCredentialsResolve(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "host_id" -------------
	var hostId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "host_id", chi.URLParam(r, "host_id"), &hostId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "host_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminHostCredentialsResolve(w, r, hostId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminHostByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminHostByID operation middleware
func (siw *ServerInterfaceWrapper) GetAdminHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchAdminHostByID operation middleware
func (siw *ServerInterfaceWrapper) PatchAdminHostByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchAdminHostByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminLicenseVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAdminLicenseVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminLicenseVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminPoliciesReload operation middleware
func (siw *ServerInterfaceWrapper) PostAdminPoliciesReload(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminPoliciesReload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminRoles operation middleware
func (siw *ServerInterfaceWrapper) GetAdminRoles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminRoles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminRolesCreate operation middleware
func (siw *ServerInterfaceWrapper) PostAdminRolesCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminRolesCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminUsers operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdminUserByID operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminUserByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdminUserByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminUserByID operation middleware
func (siw *ServerInterfaceWrapper) GetAdminUserByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminUserByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminUserRolesAssign operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserRolesAssign(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminUserRolesAssign(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAdminUserRolesUnassign operation middleware
func (siw *ServerInterfaceWrapper) PostAdminUserRolesUnassign(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAdminUserRolesUnassign(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuditEvents operation middleware
func (siw *ServerInterfaceWrapper) GetAuditEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuditEventsParams

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "action", r.URL.Query(), &params.Action, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "action"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "correlation_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "correlation_id", r.URL.Query(), &params.CorrelationId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "correlation_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "correlation_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "actor_type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "actor_type", r.URL.Query(), &params.ActorType, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "actor_type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actor_type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "until" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "until", r.URL.Query(), &params.Until, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "until"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "until", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuditEvents(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthLogout operation middleware
func (siw *ServerInterfaceWrapper) PostAuthLogout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthLogout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMe operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMePermissions operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMePermissions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMePermissions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMFAEnroll operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMFAEnroll(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMFAEnroll(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthMFAVerify operation middleware
func (siw *ServerInterfaceWrapper) PostAuthMFAVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthMFAVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthPasswordChange operation middleware
func (siw *ServerInterfaceWrapper) PostAuthPasswordChange(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthPasswordChange(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthPermissionsRegistry operation middleware
func (siw *ServerInterfaceWrapper) GetAuthPermissionsRegistry(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthPermissionsRegistry(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostAuthRefresh operation middleware
func (siw *ServerInterfaceWrapper) PostAuthRefresh(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostAuthRefresh(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEcho operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEcho(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsEchoParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	// ------------- Optional header parameter "X-Correlation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Correlation-Id")]; found {
		var XCorrelationId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Correlation-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Correlation-Id", valueList[0], &XCorrelationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Correlation-Id", Err: err})
			return
		}

		params.XCorrelationId = &XCorrelationId

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEcho(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEnqueueTestJob operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEnqueueTestJob(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEnqueueTestJob(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsEvaluateAlert operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsEvaluateAlert(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsEvaluateAlert(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsPremiumEcho operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsPremiumEcho(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsPremiumEchoParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsPremiumEcho(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireHostRead operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireHostRead(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireHostReadParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireHostRead(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireHostWrite operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireHostWrite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireHostWriteParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireHostWrite(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDiagnosticsRequireRemediationExecute operation middleware
func (siw *ServerInterfaceWrapper) PostDiagnosticsRequireRemediationExecute(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params PostDiagnosticsRequireRemediationExecuteParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDiagnosticsRequireRemediationExecute(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLicense operation middleware
func (siw *ServerInterfaceWrapper) GetLicense(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLicense(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/credentials", wrapper.GetAdminCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/credentials", wrapper.PostAdminCredentials)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/admin/credentials/{id}", wrapper.DeleteAdminCredentialByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/credentials/{id}", wrapper.GetAdminCredentialByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/hosts", wrapper.GetAdminHosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/hosts", wrapper.PostAdminHosts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/hosts/{host_id}/credentials:resolve", wrapper.PostAdminHostCredentialsResolve)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/admin/hosts/{id}", wrapper.DeleteAdminHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/hosts/{id}", wrapper.GetAdminHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/admin/hosts/{id}", wrapper.PatchAdminHostByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/license:verify", wrapper.PostAdminLicenseVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/policies:reload", wrapper.PostAdminPoliciesReload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/roles", wrapper.GetAdminRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/roles:create", wrapper.PostAdminRolesCreate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/users", wrapper.GetAdminUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/users", wrapper.PostAdminUsers)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/admin/users/{id}", wrapper.DeleteAdminUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/users/{id}", wrapper.GetAdminUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/users/{id}/roles:assign", wrapper.PostAdminUserRolesAssign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/users/{id}/roles:unassign", wrapper.PostAdminUserRolesUnassign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/audit/events", wrapper.GetAuditEvents)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.PostAuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.PostAuthLogout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me", wrapper.GetAuthMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/me/permissions", wrapper.GetAuthMePermissions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa:enroll", wrapper.PostAuthMFAEnroll)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa:verify", wrapper.PostAuthMFAVerify)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password:change", wrapper.PostAuthPasswordChange)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/auth/permissions:registry", wrapper.GetAuthPermissionsRegistry)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/refresh", wrapper.PostAuthRefresh)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:echo", wrapper.PostDiagnosticsEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:enqueue-test-job", wrapper.PostDiagnosticsEnqueueTestJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:evaluate-alert", wrapper.PostDiagnosticsEvaluateAlert)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:premium-echo", wrapper.PostDiagnosticsPremiumEcho)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-host-read", wrapper.PostDiagnosticsRequireHostRead)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-host-write", wrapper.PostDiagnosticsRequireHostWrite)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/diagnostics:require-remediation-execute", wrapper.PostDiagnosticsRequireRemediationExecute)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/license", wrapper.GetLicense)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F17bxs5kv8qRN8Ca2OkWM5jsKtgccg4nk3mkhnDSXYOmM0JVHdJYtxNdki2HF1g4D7EfcL7JAc++k12",
	"t7zWY3bzz4wj8VGs+rGqWCyWvgYhS1JGgUoRTL8GHETKqAD9jx9wdA2fMxBS/StkVALVf+I0jUmIJWH0",
	"7JNgVH0mwhUkWP31Bw6LYBr821k59Jn5Vpxdcs74JV1DzFII7u7uRkEEIuQkVYMF0+BvOCaRHnmEUrwk",
	"1P7NOCIRJCmTQMMNAjVOcDcK3oJcsehnJl/EMbuFaH+U/soZXaJX799foUQTEag2trsa/UWUEHrNYhDX",
	"lqvq05SzFLgkhsVcfa3+IBIS0UeTGuySSr5RK5ebFIJpgDnHGz01h88Z4YoFv9lxPxat2PwThFJ1e5FF",
	"RF6uLX/q1ODQrO1r3k1ITuhSdcOhZHxGNH9pFsd4HkMwlTyDka+x+dgxVsg4h1gLxY7YahKBxCTWNEUR",
	"US1xfFWhtTZxuTgz2oLxBMtgGmQZiQIHfSwMM84hmmFZax9hCWNJEnB14hAyHm3dKTJMrQu51a4uTNVP",
	"sIyHMJTjRfuc6b09BKyBE7lxkNPAkuZhQ2ajHCs1Ydc5240+cYWXjg1RsGjQhqiA2cFECl/kLMy4YFwN",
	"VN++v6T4cwbIfP0cpVgIhAX6d/PBX5BkaAEyXCG5AqRGUupILbGHs03m6WXUaXEzRq7esCWhFY1b5wyT",
	"qfpfgr+8AbqUq2D6/ShICK38qyVktapbxqNGx8fP6l3PHV0zAZziBLbu2mBAMU6Fmh4G+JQlDkMQYibZ",
	"DbiVFIcFB7HqaKGo6QeVXL2FgozmgmpUNOe0M/gW+PbHF5eUszj2LzLlbE0EYZTQ5SzjpH9/tnp0zP43",
	"4GSxeUCMNWhRA3inhyvgCRGK1A6TSCKg0iqm5jdOmRIxw5TRTcKyqnKdMxYDphoXLIaBek43bYzpWlBa",
	"LmUbzd6a0q61PqCfg362QWINZps/w4yiWrLyWLZiYV1PDOBvRR0Yimss1/P7Vn9l1cfFCtMleDGsDRCV",
	"s5ru69Z1FG6HN2+sqjVdYzjfaq6N3vAuo0+XNR2+WnPXpBdYwpLxjXEgW/PVrKMXRQMkXB3ISQcHjXoc",
	"X3DA0i9InMnVzLrWCuA0S9QkQqxmN7Cp2pNRMGdyVZmt6kjWllXRbOeTx0/d2yCCBc5i6d4I97KJdUvc",
	"/pKTNZagl9XzvQZWuuJYuLejCJlxAAt2bYSEJBgFKyakk0W6y8ytJXrdyIdyEwzdlr01NVGFQTee3hAh",
	"/QoyLNoN9y/LsUt3oEelV6fpJrfD0XkI5Id6d213XMn7zDeDTMYwnTHI8oSSrMG944buyIPvBSuf2ZzI",
	"qi9AqIQl8GqLkCWJPYF7R1kQugSectLTznvMztJoawBsac2H7dqaCKvidu6PTEiWXLMYesyDX7MP0cdG",
	"xCmWErg6Dv7Xb3j83x/VfybjP88+fj0fff/k7g8uFg32/BJCX5svz3vdwIbd7HcHSzb51ci9TLqWzzwj",
	"sZz5fMGH8n1bi67O3M+Cy3DFvOhIQAgbYGjZ/G3sUj6OnwC/Eo+InMFaOYcDFeGAwBiEKwYDXDHbrjWm",
	"cx30cwYZvAchf2LzDgvaT94nNh+22Aa5tt8wcmuR2fZBSIeGHcRH+45GFjYrtz9hTJTWHwUC+Bq4wjiL",
	"SagsOnxRigjHTqu0yhJMZxVIOyIfkm+McWrv2KaHojiRU1ft2pyozfwmyDSrnTJa4zjDEl7EwKV3k4qQ",
	"8XyLkkTx6Hwy0fvT/GsyatnQttvI3ZvzFeBYnbK8ynE+CxmlEMradqqoOSGxNBGFXH4rPeZG660lxxFE",
	"TnGtgQu3zm1Sb2YY1YkpB3Cuiwl5b8voOfNERKQx3sx8jnxbC9E14YzmPkw1XuQaf8lZlt7Xq1K+2j0P",
	"XSSd4SjiIISDyr4DG+OyBs3vnz178qwCzvORw8GTeFm3iX2sacasu85T3WAq+FRbtw9C3WclNdbwU5Ia",
	"b/D5yAztI6vz+Hbo40xzm/Rti93tg3uftGobwov5AbjuB/LuTx9uxNtl1KXhw9sHTeXRatIeHfUP4emf",
	"Xjm2BP6GhEAFvJNa5F5Fo09WwL0e+JeUcBBdwO7l/QKwzDhsuaUInS05DmGWAidssNdiD9sKLjjUgXe9",
	"Ag0SNosNU9QeomscE7dLI4m5N8vHXHDQ170p0Fssw9UsjbUjA1TqmIUA5zCZIHQ5SzmsG7FOn6+q5x2V",
	"jlLBuI9++fbccdkFzz7dyn49U208YErv5czeMOMZpsSQmBkpO8GTi7mXmLVe8IyDqIflyha3mFNCl/8Q",
	"uU2ln9PenN8lmfKu0XPhEdr7ELepx3QJ3HuheM/ISo6mJZYw9DqlILMZLClJ7F6+uIYlEZJ3wNPOQbZI",
	"RarfJjmUlS9I1DVoU2auxJgdJUxVWFCnfdSRS3WlTu8ExDXEDEd+/rJMhiyxYSFnBMGv/T1H72JIL12b",
	"lxDqtICuAOG94hr94QhLncfJVMT5w9b2e/8hWjECiyHn65yM+qStKYoBXbwsIfT7j6/WcV2lw7XyDwJ4",
	"T6ShSDroOJg/2TrXYGDW0p/2k7WUpyl03ugrXj3s2XXH+RwxFmXOwizUKRXbndV2f75zCKEzSUQLgcXw",
	"Qgiy9CfSKX1unfttIJF3880sukMqajHDDVcNT3073QztiNbqM8OCtZMf30m8BDRBtzi+IXQ5FjcQg2QU",
	"iYwvcAjo//7nf5FccQAENEoZoVIgucISwRfgIRGA5Ar+ThcsoyZbGwmJwxt0Uommj6oZ2yOk70NGJnMb",
	"gQ3fnz76u1JMkkjlAwa/pEB/VecJdGJJPK2EQ6fB5NH5o8kYx+kKPzrXhiYFilMSTIMnjyaPnuhtKlea",
	"vWc4JWfr8zONl7PG7f8SNDCUgDStr6NgGvwVpM7Zvqi0HdVT4h9PJg+WYe5JXHCkmpctUQISR1hiFBOh",
	"ofd08mR/Oe8XOI6BoxiHNwKVLJ1ywDb9PUsSrGxloNZUaSLQSUE6o/FGyfXLOEfxuLRMwTRoDawstnAI",
	"7IoJt8T0zv+BRZsdCKtuEu/qm1F5THctzJzvgIyBeLGmxyBlcph3HDawgHS2wAitmJCIMom09jBPO2yL",
	"d+9eoRvYGGr/vD9q32axJGkMyGSIIJusIBqYNqJHuILrYTC+5USaTGKvVjr7SqI7o6ljkNAG+0v9eQPu",
	"P2xev9RKj+MEpLYwv30NlNHXijBPzZja5NYaTkcV7vXd1n5sYfpp26oYCiN0UmR4/GWBYwGnRp5P96in",
	"yg1QAK0hy3dsIceG1/cQqBXS3WioJTmcoCaHUz65xj9G+f+oH3dUJf9HURK8hXFqberi8qwTGq90Kzci",
	"PmegAz4WEtU7gioWWv6qu7vEy85uu4RM66rRISzV5gjcGSU2ryOzstLyoaLSuddZySW/CzelnR2wZwel",
	"fhfsEfbhnRK0wCTOOKCTOY5QfpE4QiQdoZRxdU6R4aPTvTsirywlCMcKTRsEX4iQAhGKqlrA45botNYe",
	"kPpcEY3ws6/qfzMS3VVdkykHwWKTnjsA2xVn/Np2HGL47My/c+tnVxxV7MrhzODPrEoGXmOiL1vQgnHj",
	"hTPe8HgbyLKr0W8gKyPpSMAtiWM0B5QJiPSIvfgbaDq38YQV3o7TBzbERzMskQC5fxf4Ve2U1en8DlEb",
	"Ax3ew8pjslczdlwizf3ZIcIsHBUsw5VDm6uPDyPO3XhE9SyfQR7RfqGEbDT9CDyi40K1kRxKMqkNlzZa",
	"CwJxJO7r59g7+KnJIBjg0tRSPHbktjszV/aMU3cqiwszqoWdA5kMDHQiMv0sXnkUamNHOZxOGwJ9yTdj",
	"nlG0NsBT5uenX98jKxV0S+SKZRIRKiSOY0KXiEiHFFN78z7l+up9gBjrd/W7jOt7sgIcnLwCPlbcQmYV",
	"qLjUP+hB2NyO55xtOoSaUEGWFCLbEi1IDAItOEuMo8jogiwzDhGKCIdQmuwV325tT1cXdZHx0el46Do7",
	"u5Sqo5qPy/1nMRxBLEPxzBvL0Jf+Y0IRtzzzSaY+ikMqU3OQH7D7NOPMOXVXFzSed4P7vqBpv8tzCUu3",
	"0gI4WDCkTLZCGb2h7JbuPdqhdwuJkMQ3QL13LSWv+rDqs/nF3XunCtGX+LtUIe0sAQdPVKMj0CCKZV4N",
	"kllO+YRR6dwbDS25/vA6oZ3BtGdtUE/j8Aj7CKKhjBe2vHoKOCj4ys3sUAq6ylIPADu1wTZBJiWlYwwy",
	"7f2opuE6LKY0READY0qHZf9kr8rguESax5SGCNPjJ5abzbqMWCfnDXAZ82w+YdL5fschKHde4iBT5Nj8",
	"2mkyXDyA0fhgXEXjupImYMwKETZfS9aPHe23WUwMQE9Gt8fPh7zPNwRVEMQhYWudrJMnacrT1mFfNcml",
	"qc/395dnFhF5pqthdHviZYHQYckRRR3SrfMiWiVNtx6hVvp0696C0LDecUgWtW+0jEqdIf0wo9lKpfdY",
	"VUwSUk9TKYo3PZuMyhejj2uVHhzvRXdqi5t1aF3nY7wExBYmbxlZ5Jbq1jV6Qe5ZpXS24/xUHRKdGF6P",
	"bbVriEaIwi3oQDcXdlOW20iuzmK2JH0aMK+muqOTVatc7Z6D1e1qsQ4J6gZIR6Yhgug50sURBSJCZLnp",
	"PN+f6Xxtk1yrSdGMo7c/vkAF4zRYIMxMZebfPtbuQuxziLP82QbSQNAxc8RS83wLvf/l/ZUTMiyTgzCj",
	"2g2xIu/ABI84rNkNtAPF6lMTD7aBfGE6tIkzD0L8FkGu3kKwYzC97YzXvc7rtO4bMz8zZHOnLbcZR3PA",
	"3JbCqfJbZpzW+F0Ul3Uw/Kzxxqyb+Vf195C7lYOrSHB3+NJEy2rsuFwsQGcgo8pCdZbKQA4t8BR0peb+",
	"PVMUdd45b1rVo118qVSDRh+uXyOukWFzdNTq1QLVukMsGUc4TZu803PUGKWcPkSoVi5KYbkZNuhKtVqH",
	"eofGqVXr+r7OslLPemHkACZDTa5Ynr+PYBxxSGO8aenbC0YXhCcIU2RwC5G2LAJCDhLNN2YRGyVNjJZA",
	"lWAgQk5rkRuYqXkX2C/RemnmHYrVXQP6vrLNRztY+sXPcIsKa87hky4ApoRl68LtG28Xpph1SdMtZ/Yp",
	"ZAVqmvct/fBHUXRzIKrUwlNu6xH02R1HCYOdXtt3VExwJnpakhohsyyO0fUPLy5Qvkx0UtYWGFXN0ahx",
	"E+vw9G1V7/4NaKuJ73DnNeqVH6O/r3aTdvFRigk/lJtvGWUpsZp7hGzRnZHR4Tpp9iTEIsQRWBcaSU6W",
	"S+AQnXaeA66ZxNLsP16d6zlKCJUIq+MjMr9S8V3eQDGkBq+I4CVlQpJQTCFcsW6IvSxbX6rG7sjMCnCk",
	"g0M2FPC6fP47/g/YdAbWao/1n/U+1vfM+J/jizKoM34d9b97efjNUi1Lu+ddUitI64Cm+r48D98rmKG6",
	"POvv0vpZrn2nFjSwl285fVaOyGIB2s7NleAb3q/ikdlbesnI1jl5Xjx9F7VfIvvORHP8m8sU1x1LEHL8",
	"ic2Hb7RaVd625Xv8cMx01/91cPUnNteaJZUQPUe3jN8ANw8BIo5JM4VDP+EfT5AeHUWQsOfIskMoNcXG",
	"LEWf2BylnCltZVwfxXtCx/YzO4mfvbbQ7BjHwOVw5lbr0+7Iajpr4O5ZI3gqAbnOjeb+P7JNPaJM81Za",
	"lnaBwhwr1TJncqXsDYsjUfiwHsmlHBKSJeOtrM+V6XQURuhf037kuvzx/nS5zUxGEQOh76oJDeMsAmQh",
	"NKvACtkyea2wux5irCuvIQW553nQVXQOU7vpyj+cBo4uXqDb7uMVE3Ksr8mHov3a9DQvCHTS8jfEHwLx",
	"ylPX6UlGsRVvaE6P88Vyrqz1MdSo6gLrRZ/KSXTYc6Eh6DYpV/eA96+64zd8Hw++tSiPAeCuPMBehOtO",
	"W0C8nSvowjiHBCJiDpfwBcJse7Bfl0Nc2hG+of5f3Y+p4GpmcKU98IO+IClJmuZQ9+/B7/L3W4296BgF",
	"fedebp/H5eZRRyKSZwH5/ja/5dEVgza/ILLLkHPjN0ocMnkHfE1CQESg/MdH7kbBs33CokJC/qsniHGU",
	"0aKeQGe08g1ZA1UHeSV3HBH9d8rZHNBJ8ROr9dB3XpK8QzZviqrlu34PWa8W37GrhWrY2CN/BWnuSey9",
	"Slxti04kAT7KgS9G6HPGJBYjZMqdn5rZzG8FGcvQzG8JcYwi0LKz1YEyHivjIWUqpmdnsWqhDdyfnj59",
	"Etx9vPv/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
