# OpenWatch RPM Package Specification
# Enterprise SCAP compliance scanning platform

%global commit %(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

Name:           openwatch
Version:        1.2.1
Release:        1%{?dist}
Summary:        Enterprise SCAP compliance scanning and remediation platform
License:        Apache-2.0
URL:            https://github.com/hanalyx/openwatch
Source0:        %{name}-%{version}.tar.gz

# Architecture requirements
BuildArch:      x86_64
ExclusiveArch:  x86_64 aarch64

# Build requirements
BuildRequires:  golang >= 1.21
BuildRequires:  git
BuildRequires:  make

# Runtime requirements - Prefer Podman for RHEL-based systems
Requires:       podman >= 4.0
Requires:       podman-compose >= 1.0

# System requirements
Requires:       openscap-scanner >= 1.3.0
Requires:       openssh-clients
Requires:       systemd
Requires:       shadow-utils
Requires:       policycoreutils
Requires:       policycoreutils-python-utils
Requires:       selinux-policy-devel

# Optional security enhancements
Recommends:     podman >= 4.0
Recommends:     fapolicyd
Recommends:     aide

%description
OpenWatch is an enterprise-grade SCAP (Security Content Automation Protocol) 
compliance scanning and remediation platform. It provides automated security 
compliance monitoring, vulnerability assessment, and remediation capabilities 
for enterprise Linux environments.

Key features:
- SCAP-compliant security scanning
- Multi-host fleet management
- Automated remediation workflows  
- Real-time compliance dashboards
- Role-based access control
- Audit logging and reporting
- Container-based deployment

Supports RHEL 8+, Oracle Linux 8+, and other enterprise Linux distributions.

%prep
%autosetup -n %{name}-%{version}

%build
# Build owadm CLI tool
export CGO_ENABLED=0
export GOOS=linux

# Set build-time variables and correct architecture
if [ "%{_arch}" = "x86_64" ]; then
    export GOARCH=amd64
else
    export GOARCH=%{_arch}
fi

export BUILD_TIME=$(date -u '+%%Y-%%m-%%d_%%H:%%M:%%S')
export LDFLAGS="-s -w -X github.com/hanalyx/openwatch/internal/owadm/cmd.Version=%{version} -X github.com/hanalyx/openwatch/internal/owadm/cmd.Commit=%{commit} -X github.com/hanalyx/openwatch/internal/owadm/cmd.BuildTime=$BUILD_TIME"

go build -ldflags "$LDFLAGS" -o bin/owadm cmd/owadm/main.go

# Build SELinux policy if tools are available
if command -v make >/dev/null 2>&1 && [ -f /usr/share/selinux/devel/Makefile ]; then
    cd packaging/selinux
    make -f /usr/share/selinux/devel/Makefile openwatch.pp
    cd ../..
fi

%install
# Create directory structure
install -d %{buildroot}%{_bindir}
install -d %{buildroot}%{_sysconfdir}/openwatch
install -d %{buildroot}%{_sysconfdir}/openwatch/ssh
install -d %{buildroot}%{_datadir}/openwatch
install -d %{buildroot}%{_datadir}/openwatch/compose
install -d %{buildroot}%{_datadir}/openwatch/scripts
install -d %{buildroot}/lib/systemd/system
install -d %{buildroot}%{_localstatedir}/lib/openwatch
install -d %{buildroot}%{_localstatedir}/log/openwatch
install -d %{buildroot}%{_localstatedir}/cache/openwatch

# Install owadm binary
install -m 0755 bin/owadm %{buildroot}%{_bindir}/owadm

# Install container orchestration files
install -m 0644 docker-compose.yml %{buildroot}%{_datadir}/openwatch/compose/docker-compose.yml
install -m 0644 podman-compose.yml %{buildroot}%{_datadir}/openwatch/compose/podman-compose.yml

# Install configuration templates
cat > %{buildroot}%{_sysconfdir}/openwatch/ow.yml << 'EOF'
# OpenWatch Configuration
# Generated by RPM package installation

runtime:
  engine: "podman"              # podman (default), docker, auto
  rootless: true                # Use rootless containers (recommended)
  compose_file: "/usr/share/openwatch/compose/podman-compose.yml"
  compose_command: "podman-compose"  # podman-compose or podman compose or docker-compose
  
database:
  host: "localhost"
  port: 5432
  name: "openwatch"
  user: "openwatch"
  ssl_mode: "require"
  # Password loaded from secrets.env
  
web:
  port: 3001
  bind_address: "0.0.0.0"
  ssl:
    enabled: false              # Set to true for production
    cert_path: "/etc/ssl/certs/openwatch.crt"
    key_path: "/etc/ssl/private/openwatch.key"
    
scanning:
  ssh_key_path: "/etc/openwatch/ssh/openwatch_rsa"
  concurrent_scans: 5
  timeout: 300
  scap_content_dir: "/var/lib/openwatch/scap"
  results_dir: "/var/lib/openwatch/results"

logging:
  level: "INFO"
  file: "/var/log/openwatch/openwatch.log"
  audit_file: "/var/log/openwatch/audit.log"
  max_size: "100MB"
  max_age: 30
  
security:
  fips_mode: false              # Enable for FIPS 140-2 compliance
  audit_logging: true
  rate_limiting: true
  session_timeout: 3600
EOF

# Install secrets template (will be configured by admin)
cat > %{buildroot}%{_sysconfdir}/openwatch/secrets.env << 'EOF'
# OpenWatch Secrets Configuration
# IMPORTANT: Secure this file with chmod 600 and set proper ownership

# Database password
POSTGRES_PASSWORD=CHANGEME_SECURE_DB_PASSWORD

# Redis password
REDIS_PASSWORD=CHANGEME_SECURE_REDIS_PASSWORD

# Application secrets
SECRET_KEY=CHANGEME_64_CHAR_SECRET_KEY
MASTER_KEY=CHANGEME_32_CHAR_MASTER_KEY

# JWT signing keys (auto-generated by post-install script)
JWT_PRIVATE_KEY_PATH=/etc/openwatch/jwt_private.pem
JWT_PUBLIC_KEY_PATH=/etc/openwatch/jwt_public.pem
EOF

# Install systemd service files
cat > %{buildroot}/lib/systemd/system/openwatch.service << 'EOF'
[Unit]
Description=OpenWatch SCAP Compliance Platform
Documentation=https://github.com/hanalyx/openwatch
Requires=openwatch-db.service
After=network-online.target openwatch-db.service
Wants=network-online.target

[Service]
Type=forking
User=openwatch
Group=openwatch
EnvironmentFile=/etc/openwatch/secrets.env
ExecStartPre=/usr/bin/owadm validate-config
ExecStart=/usr/bin/owadm start --daemon
ExecStop=/usr/bin/owadm stop
ExecReload=/usr/bin/owadm restart
Restart=on-failure
RestartSec=10
KillMode=mixed
TimeoutStartSec=300
TimeoutStopSec=120

# Security settings
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/openwatch /var/log/openwatch /etc/openwatch
PrivateTmp=true
ProtectKernelTunables=true
ProtectControlGroups=true
RestrictRealtime=true
LockPersonality=true

[Install]
WantedBy=multi-user.target
EOF

cat > %{buildroot}/lib/systemd/system/openwatch-db.service << 'EOF'
[Unit]
Description=OpenWatch Database Container
Documentation=https://github.com/hanalyx/openwatch
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
User=openwatch
Group=openwatch
EnvironmentFile=/etc/openwatch/secrets.env
ExecStartPre=/usr/bin/owadm validate-config
ExecStart=/usr/bin/owadm start --daemon --service database
ExecStop=/usr/bin/owadm stop --service database
Restart=on-failure
RestartSec=5
TimeoutStartSec=60
TimeoutStopSec=30

# Security settings
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/openwatch
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

# Install SELinux policy files (if available)
install -d %{buildroot}%{_datadir}/selinux/packages
if [ -f packaging/selinux/openwatch.pp ]; then
    install -m 0644 packaging/selinux/openwatch.pp %{buildroot}%{_datadir}/selinux/packages/openwatch.pp
else
    # Create empty policy file as placeholder
    touch %{buildroot}%{_datadir}/selinux/packages/openwatch.pp
fi

# Install fapolicyd configuration scripts
install -m 0755 packaging/rpm/scripts/configure-fapolicyd.sh %{buildroot}%{_datadir}/openwatch/scripts/configure-fapolicyd.sh
install -m 0755 packaging/rpm/scripts/fapolicyd-troubleshoot.sh %{buildroot}%{_datadir}/openwatch/scripts/fapolicyd-troubleshoot.sh

# Install fapolicyd rules template
install -d %{buildroot}%{_datadir}/openwatch/templates
install -m 0644 packaging/rpm/templates/90-openwatch.rules %{buildroot}%{_datadir}/openwatch/templates/90-openwatch.rules

# Install helper scripts
cat > %{buildroot}%{_datadir}/openwatch/scripts/generate-secrets.sh << 'EOF'
#!/bin/bash
# OpenWatch Secret Generation Script

set -euo pipefail

SECRETS_FILE="/etc/openwatch/secrets.env"
CONFIG_DIR="/etc/openwatch"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}ℹ️  $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

log_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check prerequisites
check_prerequisites() {
    log_info "Checking prerequisites..."
    
    # Check if OpenSSL is installed
    if ! command -v openssl >/dev/null 2>&1; then
        log_error "OpenSSL is not installed!"
        echo ""
        echo "Please install OpenSSL first:"
        echo "  RHEL/Fedora/Oracle Linux: sudo dnf install openssl"
        echo "  Ubuntu/Debian:             sudo apt install openssl"
        echo "  SLES/openSUSE:             sudo zypper install openssl"
        echo ""
        exit 1
    fi
    
    # Check OpenSSL version
    local openssl_version
    openssl_version=$(openssl version | cut -d' ' -f2)
    log_info "OpenSSL version: $openssl_version"
    
    # Check if we have required tools
    local missing_tools=()
    for tool in sed chown chmod; do
        if ! command -v "$tool" >/dev/null 2>&1; then
            missing_tools+=("$tool")
        fi
    done
    
    if [ ${#missing_tools[@]} -gt 0 ]; then
        log_error "Missing required tools: ${missing_tools[*]}"
        exit 1
    fi
    
    log_info "Prerequisites check passed"
}

# Generate secure random passwords
generate_password() {
    # Try different methods based on what's available
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
    elif [ -f /dev/urandom ]; then
        tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
    else
        log_error "Cannot generate secure random passwords - no entropy source available"
        exit 1
    fi
}

# Generate JWT key pair with compatibility
generate_jwt_keys() {
    local private_key="$CONFIG_DIR/jwt_private.pem"
    local public_key="$CONFIG_DIR/jwt_public.pem"
    
    log_info "Generating JWT key pair..."
    
    # Try modern OpenSSL syntax first, fall back to older syntax
    if openssl genpkey -algorithm RSA -out "$private_key" -pkeyopt rsa_keygen_bits:2048 2>/dev/null; then
        log_info "Generated private key using modern OpenSSL"
    elif openssl genrsa -out "$private_key" 2048 2>/dev/null; then
        log_info "Generated private key using legacy OpenSSL"
    else
        log_error "Failed to generate RSA private key"
        log_info "Trying alternative method..."
        
        # Alternative method for very old OpenSSL versions
        if ! openssl genrsa 2048 > "$private_key" 2>/dev/null; then
            log_error "All RSA key generation methods failed"
            exit 1
        fi
        log_info "Generated private key using alternative method"
    fi
    
    # Extract public key (try different methods)
    if openssl pkey -in "$private_key" -pubout -out "$public_key" 2>/dev/null; then
        log_info "Extracted public key using modern OpenSSL"
    elif openssl rsa -in "$private_key" -pubout -out "$public_key" 2>/dev/null; then
        log_info "Extracted public key using legacy OpenSSL"
    else
        log_error "Failed to extract public key from private key"
        exit 1
    fi
    
    # Set proper permissions
    chmod 600 "$private_key"
    chmod 644 "$public_key"
    
    # Only change ownership if openwatch user exists
    if id "openwatch" >/dev/null 2>&1; then
        chown openwatch:openwatch "$private_key" "$public_key"
    else
        log_warning "openwatch user not found - keeping root ownership"
    fi
    
    log_info "JWT keys generated successfully"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

# Check if secrets file exists
if [ ! -f "$SECRETS_FILE" ]; then
    log_error "Secrets file not found: $SECRETS_FILE"
    log_info "Please ensure OpenWatch is properly installed"
    exit 1
fi

echo "🔐 OpenWatch Secret Generation Script"
echo "====================================="

check_prerequisites

log_info "Generating OpenWatch secrets..."

# Generate secrets with error handling
log_info "Generating database password..."
DB_PASSWORD=$(generate_password)

log_info "Generating Redis password..."
REDIS_PASSWORD=$(generate_password)

log_info "Generating application secret key..."
if command -v openssl >/dev/null 2>&1; then
    SECRET_KEY=$(openssl rand -base64 48 | tr -d "=+/" | cut -c1-64)
else
    SECRET_KEY=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64)
fi

log_info "Generating master key..."
MASTER_KEY=$(generate_password)

# Backup original secrets file
cp "$SECRETS_FILE" "$SECRETS_FILE.backup.$(date +%%Y%%m%%d_%%H%%M%%S)"
log_info "Backed up original secrets file"

# Update secrets file
log_info "Updating secrets file..."
sed -i "s/CHANGEME_SECURE_DB_PASSWORD/$DB_PASSWORD/" "$SECRETS_FILE"
sed -i "s/CHANGEME_SECURE_REDIS_PASSWORD/$REDIS_PASSWORD/" "$SECRETS_FILE"
sed -i "s/CHANGEME_64_CHAR_SECRET_KEY/$SECRET_KEY/" "$SECRETS_FILE"
sed -i "s/CHANGEME_32_CHAR_MASTER_KEY/$MASTER_KEY/" "$SECRETS_FILE"

# Generate JWT keys
generate_jwt_keys

# Secure the secrets file
chmod 600 "$SECRETS_FILE"
if id "openwatch" >/dev/null 2>&1; then
    chown openwatch:openwatch "$SECRETS_FILE"
else
    log_warning "openwatch user not found - keeping root ownership"
fi

echo ""
echo "✅ Secrets generated successfully!"
echo ""
echo "📁 Files created/updated:"
echo "  • $SECRETS_FILE"
echo "  • $CONFIG_DIR/jwt_private.pem"
echo "  • $CONFIG_DIR/jwt_public.pem"
echo ""
echo "⚠️  Next steps:"
echo "  1. Review and customize /etc/openwatch/ow.yml"
echo "  2. Generate SSH keys if needed: ssh-keygen -t rsa -f /etc/openwatch/ssh/openwatch_rsa"
echo "  3. Start OpenWatch: systemctl start openwatch"
echo ""
echo "🔐 Secrets stored securely with restricted permissions"
EOF

chmod +x %{buildroot}%{_datadir}/openwatch/scripts/generate-secrets.sh

%pre
# Create openwatch user and group
getent group openwatch >/dev/null || groupadd -r openwatch
getent passwd openwatch >/dev/null || \
    useradd -r -g openwatch -d /var/lib/openwatch -s /sbin/nologin \
    -c "OpenWatch service account" openwatch

# Add openwatch user to container groups if they exist
if getent group podman >/dev/null; then
    usermod -aG podman openwatch
fi
if getent group docker >/dev/null; then
    usermod -aG docker openwatch
fi

%post
# Set proper ownership and permissions
chown -R openwatch:openwatch /etc/openwatch
chown -R openwatch:openwatch /var/lib/openwatch
chown -R openwatch:openwatch /var/log/openwatch

# Set restrictive permissions on config directory
chmod 750 /etc/openwatch
chmod 700 /etc/openwatch/ssh
chmod 600 /etc/openwatch/secrets.env

# Generate initial secrets if they don't exist
if grep -q "CHANGEME" /etc/openwatch/secrets.env; then
    echo "Generating initial secrets..."
    /usr/share/openwatch/scripts/generate-secrets.sh
fi

# Check and configure SELinux policy for RHEL/Oracle Linux
check_and_configure_selinux() {
    # Check if SELinux tools are available
    if ! command -v semanage >/dev/null 2>&1; then
        echo "ℹ️  SELinux management tools not found - skipping SELinux policy installation"
        return 0
    fi
    
    # Check if SELinux is installed and enabled
    if ! command -v getenforce >/dev/null 2>&1; then
        echo "ℹ️  SELinux not installed - skipping SELinux policy installation"
        return 0
    fi
    
    local selinux_status
    selinux_status=$(getenforce 2>/dev/null || echo "Disabled")
    
    if [ "$selinux_status" = "Disabled" ]; then
        echo "ℹ️  SELinux is disabled - skipping SELinux policy installation"
        return 0
    fi
    
    echo "Installing OpenWatch SELinux policy (SELinux status: $selinux_status)..."
    
    # Install policy module only if the file exists and is valid
    if [ -f /usr/share/selinux/packages/openwatch.pp ] && [ -s /usr/share/selinux/packages/openwatch.pp ]; then
        if semodule -i /usr/share/selinux/packages/openwatch.pp 2>/dev/null; then
            echo "✅ SELinux policy module installed successfully"
        else
            echo "⚠️  SELinux policy installation failed - this is expected if policy wasn't built"
        fi
    else
        echo "⚠️  SELinux policy file not found or empty - skipping policy installation"
    fi
    
    # Apply file contexts regardless of policy installation
    echo "Applying SELinux file contexts..."
    if [ -d /etc/openwatch ]; then
        restorecon -R /etc/openwatch 2>/dev/null || true
    fi
    if [ -d /var/lib/openwatch ]; then
        restorecon -R /var/lib/openwatch 2>/dev/null || true
    fi
    if [ -d /var/log/openwatch ]; then
        restorecon -R /var/log/openwatch 2>/dev/null || true
    fi
    if [ -f /usr/bin/owadm ]; then
        restorecon /usr/bin/owadm 2>/dev/null || true
    fi
    
    echo "✅ SELinux contexts configured"
}

# Check and configure fapolicyd for OpenWatch
check_and_configure_fapolicyd() {
    # Check if fapolicyd is installed
    if ! command -v fapolicyd >/dev/null 2>&1; then
        echo "ℹ️  fapolicyd not installed - skipping fapolicyd configuration"
        return 0
    fi
    
    # Check if fapolicyd service exists
    if ! systemctl list-unit-files fapolicyd.service >/dev/null 2>&1; then
        echo "ℹ️  fapolicyd service not available - skipping fapolicyd configuration"
        return 0
    fi
    
    # Check if fapolicyd is enabled and running
    local fapolicyd_enabled=false
    local fapolicyd_active=false
    
    if systemctl is-enabled fapolicyd >/dev/null 2>&1; then
        fapolicyd_enabled=true
    fi
    
    if systemctl is-active --quiet fapolicyd 2>/dev/null; then
        fapolicyd_active=true
    fi
    
    if [ "$fapolicyd_enabled" = "false" ] && [ "$fapolicyd_active" = "false" ]; then
        echo "ℹ️  fapolicyd is not enabled or running - skipping automatic configuration"
        echo "ℹ️  To configure fapolicyd later: /usr/share/openwatch/scripts/configure-fapolicyd.sh configure"
        return 0
    fi
    
    echo "Configuring fapolicyd for OpenWatch (enabled: $fapolicyd_enabled, active: $fapolicyd_active)..."
    
    # Check if configuration script exists
    if [ -f /usr/share/openwatch/scripts/configure-fapolicyd.sh ]; then
        if /usr/share/openwatch/scripts/configure-fapolicyd.sh configure 2>/dev/null; then
            echo "✅ fapolicyd rules configured successfully"
        else
            echo "⚠️  fapolicyd configuration failed - manual configuration may be needed"
        fi
        echo "ℹ️  Troubleshooting: /usr/share/openwatch/scripts/fapolicyd-troubleshoot.sh"
    else
        echo "⚠️  fapolicyd configuration script not found"
    fi
}

# Run security configurations
check_and_configure_selinux
check_and_configure_fapolicyd

# Enable but don't start services (let admin control startup)
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
    systemctl enable openwatch.service openwatch-db.service
fi

echo ""
echo ""
echo "🎉 OpenWatch installed successfully!"
echo ""
echo "Next steps:"
echo "1. Review configuration: /etc/openwatch/ow.yml"
echo "2. Configure SSL certificates (recommended)"
echo "3. Start services: systemctl start openwatch"
echo "4. Check status: owadm status"
echo ""

# Show runtime environment info
echo "🔧 Runtime Configuration:"
echo "  • Container runtime: Podman (RHEL/Fedora optimized)"
echo "  • Compose command: podman-compose"
echo "  • Config file: /etc/openwatch/ow.yml"
echo ""

# Show security configuration status
echo "🛡️  Security Configuration Status:"
if command -v getenforce >/dev/null 2>&1 && [ "$(getenforce 2>/dev/null || echo Disabled)" != "Disabled" ]; then
    echo "  • SELinux: Enabled and configured"
else
    echo "  • SELinux: Not enabled"
fi

if command -v fapolicyd >/dev/null 2>&1 && systemctl is-enabled fapolicyd >/dev/null 2>&1; then
    echo "  • fapolicyd: Detected and configured"
    echo "    Troubleshooting: /usr/share/openwatch/scripts/fapolicyd-troubleshoot.sh"
else
    echo "  • fapolicyd: Not enabled"
fi
echo ""

echo "📖 Documentation: https://github.com/hanalyx/openwatch"
echo ""

%preun
if command -v systemctl >/dev/null 2>&1; then
    systemctl stop openwatch.service openwatch-db.service || true
    systemctl disable openwatch.service openwatch-db.service || true
fi

%postun
if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload || true
fi

# Clean up user on complete removal
if [ $1 -eq 0 ]; then
    # Remove openwatch user (but preserve data directories)
    userdel openwatch 2>/dev/null || true
    
    # Remove SELinux policy module
    if command -v semodule >/dev/null 2>&1; then
        semodule -r openwatch 2>/dev/null || true
        echo "Removed OpenWatch SELinux policy"
    fi
    
    # Clean up fapolicyd rules
    if command -v fapolicyd >/dev/null 2>&1 && [ -f /usr/share/openwatch/scripts/configure-fapolicyd.sh ]; then
        /usr/share/openwatch/scripts/configure-fapolicyd.sh cleanup
        echo "Removed OpenWatch fapolicyd rules"
    fi
fi

%files
# Main binary
%{_bindir}/owadm

# Configuration files
%dir %attr(750,openwatch,openwatch) %{_sysconfdir}/openwatch
%dir %attr(700,openwatch,openwatch) %{_sysconfdir}/openwatch/ssh
%config(noreplace) %attr(640,openwatch,openwatch) %{_sysconfdir}/openwatch/ow.yml
%config(noreplace) %attr(600,openwatch,openwatch) %{_sysconfdir}/openwatch/secrets.env

# Systemd service files
/lib/systemd/system/openwatch.service
/lib/systemd/system/openwatch-db.service

# Application data
%dir %attr(755,root,root) %{_datadir}/openwatch
%dir %attr(755,root,root) %{_datadir}/openwatch/compose
%dir %attr(755,root,root) %{_datadir}/openwatch/scripts
%dir %attr(755,root,root) %{_datadir}/openwatch/templates
%{_datadir}/openwatch/compose/docker-compose.yml
%{_datadir}/openwatch/compose/podman-compose.yml
%attr(755,root,root) %{_datadir}/openwatch/scripts/generate-secrets.sh
%attr(755,root,root) %{_datadir}/openwatch/scripts/configure-fapolicyd.sh
%attr(755,root,root) %{_datadir}/openwatch/scripts/fapolicyd-troubleshoot.sh
%{_datadir}/openwatch/templates/90-openwatch.rules

# SELinux policy files
%{_datadir}/selinux/packages/openwatch.pp

# Runtime directories
%dir %attr(755,openwatch,openwatch) %{_localstatedir}/lib/openwatch
%dir %attr(755,openwatch,openwatch) %{_localstatedir}/log/openwatch
%dir %attr(755,openwatch,openwatch) %{_localstatedir}/cache/openwatch

%changelog
* Wed Sep 18 2024 OpenWatch Team <admin@hanalyx.com> - 1.2.1-1
- Update to version 1.2.1
- Add fapolicyd integration for application whitelisting
- Include comprehensive fapolicyd rules for all OpenWatch components
- Add fapolicyd troubleshooting and diagnostic tools
- Automatic fapolicyd configuration during package installation
- Enhanced security for RHEL/Oracle Linux deployments

* Tue Sep 17 2024 OpenWatch Team <admin@hanalyx.com> - 1.0.0-1
- Initial RPM package for OpenWatch
- Support for RHEL 8+, Oracle Linux 8+
- Container runtime abstraction (Podman/Docker)
- Enterprise security defaults
- SELinux integration
- Systemd service management
- Automated secret generation
- FIPS compliance ready