//go:build ignore

// gen-audit-events reads audit/events.yaml and emits
// internal/audit/events.gen.go: typed Code constants and a Metadata map.
//
// Run via `make generate-audit` (or `go run scripts/gen-audit-events.go`).
//
// Per specs/system/audit-emission.spec.yaml AC-1, AC-2, AC-3.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

const (
	inputPath  = "audit/events.yaml"
	outputPath = "internal/audit/events.gen.go"
)

type registry struct {
	Version    int        `yaml:"version"`
	Categories []category `yaml:"categories"`
	Events     []event    `yaml:"events"`
	Deprecated []event    `yaml:"deprecated_events"`
}

type category struct {
	ID          string `yaml:"id"`
	Description string `yaml:"description"`
}

type event struct {
	Code         string                 `yaml:"code"`
	Severity     string                 `yaml:"severity"`
	Description  string                 `yaml:"description"`
	ActorTypes   []string               `yaml:"actor_types"`
	DetailSchema map[string]interface{} `yaml:"detail_schema"`
}

const fileTpl = `// Code generated by scripts/gen-audit-events.go from audit/events.yaml.
// DO NOT EDIT. Re-run via: make generate-audit
//
// Source-of-truth registry: audit/events.yaml
// Behavioral contract:      specs/system/audit-emission.spec.yaml AC-1..AC-3

package audit

// Code is a stable, dotted-hierarchy audit event identifier.
// e.g., auth.login.success, host.created.
type Code string

// Severity grades the operational importance of an event.
type Severity string

const (
	SeverityInfo     Severity = "info"
	SeverityWarning  Severity = "warning"
	SeverityError    Severity = "error"
	SeverityCritical Severity = "critical"
)

// Event constants. Hand-typed event-string literals are forbidden by lint;
// use these constants.
const (
{{- range .Events }}
	// {{ .Description }}
	{{ .GoConst }} Code = "{{ .Code }}"
{{- end }}
)

// EventMeta is the per-event metadata derived from events.yaml.
type EventMeta struct {
	Code        Code
	Category    string
	Severity    Severity
	Description string
	ActorTypes  []string
}

// Metadata maps every active event code to its registry entry.
var Metadata = map[Code]EventMeta{
{{- range .Events }}
	{{ .GoConst }}: {
		Code:        {{ .GoConst }},
		Category:    "{{ .Category }}",
		Severity:    Severity{{ .GoSeverity }},
		Description: ` + "`" + `{{ .Description }}` + "`" + `,
		ActorTypes:  {{ .GoActorTypes }},
	},
{{- end }}
}

// AllCodes returns every active event code in declaration order.
func AllCodes() []Code {
	out := make([]Code, 0, len(codeOrder))
	out = append(out, codeOrder...)
	return out
}

var codeOrder = []Code{
{{- range .Events }}
	{{ .GoConst }},
{{- end }}
}
`

// emitContext is the data passed to the template. Each event is enriched
// with derived fields the template needs.
type emitContext struct {
	Events []emitEvent
}

type emitEvent struct {
	Code         string
	GoConst      string // PascalCase identifier
	Category     string // first dotted segment
	Severity     string // raw severity from yaml
	GoSeverity   string // PascalCase severity for Severity<X> reference
	Description  string
	ActorTypes   []string
	GoActorTypes string // Go source: nil or []string{"..."}
}

func main() {
	raw, err := os.ReadFile(inputPath)
	check(err, "read input")

	var reg registry
	check(yaml.Unmarshal(raw, &reg), "parse yaml")

	if len(reg.Events) == 0 {
		fail("no events in registry")
	}

	ec := emitContext{
		Events: make([]emitEvent, 0, len(reg.Events)),
	}
	for _, e := range reg.Events {
		ec.Events = append(ec.Events, enrich(e))
	}

	// Stable order: yaml's natural order is preserved, which is meaningful
	// (grouped by category). Sort would scramble that. Leave as-is.

	tpl, err := template.New("events").Parse(fileTpl)
	check(err, "parse template")

	var buf bytes.Buffer
	check(tpl.Execute(&buf, ec), "execute template")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Help debugging: write the unformatted output to stderr so the
		// caller can see what gofmt rejected.
		fmt.Fprintf(os.Stderr, "%s\n---\n", buf.String())
		check(err, "gofmt")
	}

	check(os.WriteFile(outputPath, formatted, 0o644), "write output")
	fmt.Printf("wrote %s (%d events)\n", outputPath, len(ec.Events))
}

// enrich derives template-friendly fields from a parsed event.
func enrich(e event) emitEvent {
	categoryID := strings.SplitN(e.Code, ".", 2)[0]

	return emitEvent{
		Code:         e.Code,
		GoConst:      toPascal(e.Code),
		Category:     categoryID,
		Severity:     e.Severity,
		GoSeverity:   toPascalSeverity(e.Severity),
		Description:  cleanDescription(e.Description),
		ActorTypes:   e.ActorTypes,
		GoActorTypes: actorTypesLiteral(e.ActorTypes),
	}
}

// toPascal converts an audit code like "auth.login.success" to a Go
// identifier "AuthLoginSuccess".
func toPascal(code string) string {
	parts := strings.FieldsFunc(code, func(r rune) bool {
		return r == '.' || r == '_'
	})
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]))
		b.WriteString(p[1:])
	}
	return b.String()
}

// toPascalSeverity converts "info" → "Info" so the template can write
// "SeverityInfo" by composition.
func toPascalSeverity(s string) string {
	if s == "" {
		return "Info"
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// cleanDescription folds a multi-line description into a single line so
// it lives cleanly inside a backtick-quoted string literal.
func cleanDescription(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return ""
	}
	// Collapse newlines and runs of whitespace to single spaces.
	fields := strings.Fields(s)
	return strings.Join(fields, " ")
}

// actorTypesLiteral renders []string{"user","system"} as a Go literal.
func actorTypesLiteral(at []string) string {
	if len(at) == 0 {
		return "nil"
	}
	quoted := make([]string, len(at))
	for i, s := range at {
		quoted[i] = `"` + s + `"`
	}
	// Sort for deterministic output (yaml may reorder list members).
	sort.Strings(quoted)
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}

func check(err error, what string) {
	if err != nil {
		fail("%s: %v", what, err)
	}
}

func fail(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "gen-audit-events: "+format+"\n", args...)
	os.Exit(1)
}
