// Code generated by scripts/gen-rbac.go from auth/permissions.yaml.
// DO NOT EDIT. Re-run via: make generate-rbac

package auth

// Permission is a stable, resource:action identifier.
type Permission string

// Permission constants. Hand-typed permission strings are forbidden by
// lint; use these constants in handler middleware and tests.
const (
	// View own profile, sessions, MFA status
	AuthRead Permission = "auth:read"
	// Change own password, manage own MFA, revoke own sessions
	AuthWrite Permission = "auth:write"
	// List users, view user details
	UserRead Permission = "user:read"
	// Create or update user records (excluding role assignment)
	UserWrite Permission = "user:write"
	// Delete user accounts
	UserDelete Permission = "user:delete"
	// View host details, list hosts, view host audit history
	HostRead Permission = "host:read"
	// Create, update, bulk-import hosts
	HostWrite Permission = "host:write"
	// Delete a host record and its scan history pointer
	HostDelete Permission = "host:delete"
	// Trigger an on-demand SSH/ping connectivity check
	HostConnectivityCheck Permission = "host:connectivity_check"
	// Trigger an on-demand server-intelligence collection
	HostIntelligenceRefresh Permission = "host:intelligence_refresh"
	// List credentials (metadata only — secrets never returned), resolve credential for a host
	CredentialRead Permission = "credential:read"
	// Create credentials (system or host scope), set is_default
	CredentialWrite Permission = "credential:write"
	// Soft-delete credentials (set is_active=false)
	CredentialDelete Permission = "credential:delete"
	// View scans, scan sessions, and scan results
	ScanRead Permission = "scan:read"
	// Queue or start a scan against a host or fleet
	ScanExecute Permission = "scan:execute"
	// Cancel a running or queued scan
	ScanCancel Permission = "scan:cancel"
	// List and view scan templates
	ScanTemplateRead Permission = "scan_template:read"
	// Create or update scan templates
	ScanTemplateWrite Permission = "scan_template:write"
	// Delete a scan template (does not affect historical scans)
	ScanTemplateDelete Permission = "scan_template:delete"
	// View compliance state, drift detection results, posture queries
	ComplianceRead Permission = "compliance:read"
	// View compliance baselines
	BaselineRead Permission = "baseline:read"
	// Establish or update a compliance baseline
	BaselineWrite Permission = "baseline:write"
	// Clear an existing baseline (resets drift detection)
	BaselineDelete Permission = "baseline:delete"
	// View exception requests and active exceptions
	ExceptionRead Permission = "exception:read"
	// Submit a new exception request
	ExceptionRequest Permission = "exception:request"
	// Add comments to exception requests
	ExceptionComment Permission = "exception:comment"
	// Approve or reject exception requests
	ExceptionApprove Permission = "exception:approve"
	// Revoke an active exception before its expiry
	ExceptionRevoke Permission = "exception:revoke"
	// View alerts and alert history
	AlertRead Permission = "alert:read"
	// Acknowledge an alert (suppresses repeat notifications)
	AlertAcknowledge Permission = "alert:acknowledge"
	// Mark an alert as resolved
	AlertResolve Permission = "alert:resolve"
	// Create or modify alert thresholds
	AlertWrite Permission = "alert:write"
	// View notification channels and delivery history
	NotificationRead Permission = "notification:read"
	// Create or update notification channels
	NotificationWrite Permission = "notification:write"
	// Delete notification channels
	NotificationDelete Permission = "notification:delete"
	// Send a test notification through a channel
	NotificationTest Permission = "notification:test"
	// View license status, features, quotas, and history
	LicenseRead Permission = "license:read"
	// Install or replace the active license file
	LicenseInstall Permission = "license:install"
	// Mark the current license as revoked (forces Free tier)
	LicenseRevoke Permission = "license:revoke"
	// View active policies, policy_history, and reload outcomes
	PolicyRead Permission = "policy:read"
	// Trigger a policy reload (SIGHUP equivalent via API)
	PolicyReload Permission = "policy:reload"
	// Install a new policy version (writes a signed file)
	PolicyInstall Permission = "policy:install"
	// View remediation requests and history
	RemediationRead Permission = "remediation:read"
	// Submit a remediation request
	RemediationRequest Permission = "remediation:request"
	// Approve or reject remediation requests
	RemediationApprove Permission = "remediation:approve"
	// Execute an approved remediation against hosts
	RemediationExecute Permission = "remediation:execute"
	// Roll back a previously executed remediation
	RemediationRollback Permission = "remediation:rollback"
	// View configured plugins and webhook endpoints
	IntegrationRead Permission = "integration:read"
	// Configure plugins and webhook endpoints
	IntegrationWrite Permission = "integration:write"
	// Manually invoke a plugin (out-of-band of the normal trigger)
	IntegrationExecute Permission = "integration:execute"
	// Query the audit log via filters or DSL
	AuditRead Permission = "audit:read"
	// Export the audit log to file (large extracts)
	AuditExport Permission = "audit:export"
	// View system health, version, and non-secret configuration
	SystemRead Permission = "system:read"
	// Modify runtime system configuration
	SystemConfigWrite Permission = "system:config_write"
	// View roles and built-in role definitions
	RoleRead Permission = "role:read"
	// Create or update custom roles (Stage 2)
	RoleWrite Permission = "role:write"
	// Assign roles to users
	RoleAssign Permission = "role:assign"
	// Manage users including role assignments
	AdminUserManage Permission = "admin:user_manage"
	// Create, update, delete custom roles; assign roles to users
	AdminRoleManage Permission = "admin:role_manage"
	// Modify audit/scan/log retention policies
	AdminRetentionPolicy Permission = "admin:retention_policy"
	// Configure SSO providers (OIDC, SAML)
	AdminSsoProvider Permission = "admin:sso_provider"
	// Modify high-impact system settings (TLS, listener, FIPS mode hint)
	AdminSystemSetting Permission = "admin:system_setting"
)

// PermissionMeta is the per-permission metadata from the registry.
type PermissionMeta struct {
	ID           Permission
	Category     string
	Description  string
	Dangerous    bool
	LicenseGated string // feature id from license/features.yaml; "" if not gated
}

// Permissions maps every active permission id to its registry entry.
var Permissions = map[Permission]PermissionMeta{
	AuthRead: {
		ID:           AuthRead,
		Category:     "auth",
		Description:  `View own profile, sessions, MFA status`,
		Dangerous:    false,
		LicenseGated: "",
	},
	AuthWrite: {
		ID:           AuthWrite,
		Category:     "auth",
		Description:  `Change own password, manage own MFA, revoke own sessions`,
		Dangerous:    false,
		LicenseGated: "",
	},
	UserRead: {
		ID:           UserRead,
		Category:     "user",
		Description:  `List users, view user details`,
		Dangerous:    false,
		LicenseGated: "",
	},
	UserWrite: {
		ID:           UserWrite,
		Category:     "user",
		Description:  `Create or update user records (excluding role assignment)`,
		Dangerous:    false,
		LicenseGated: "",
	},
	UserDelete: {
		ID:           UserDelete,
		Category:     "user",
		Description:  `Delete user accounts`,
		Dangerous:    true,
		LicenseGated: "",
	},
	HostRead: {
		ID:           HostRead,
		Category:     "host",
		Description:  `View host details, list hosts, view host audit history`,
		Dangerous:    false,
		LicenseGated: "",
	},
	HostWrite: {
		ID:           HostWrite,
		Category:     "host",
		Description:  `Create, update, bulk-import hosts`,
		Dangerous:    false,
		LicenseGated: "",
	},
	HostDelete: {
		ID:           HostDelete,
		Category:     "host",
		Description:  `Delete a host record and its scan history pointer`,
		Dangerous:    true,
		LicenseGated: "",
	},
	HostConnectivityCheck: {
		ID:           HostConnectivityCheck,
		Category:     "host",
		Description:  `Trigger an on-demand SSH/ping connectivity check`,
		Dangerous:    false,
		LicenseGated: "",
	},
	HostIntelligenceRefresh: {
		ID:           HostIntelligenceRefresh,
		Category:     "host",
		Description:  `Trigger an on-demand server-intelligence collection`,
		Dangerous:    false,
		LicenseGated: "",
	},
	CredentialRead: {
		ID:           CredentialRead,
		Category:     "credential",
		Description:  `List credentials (metadata only — secrets never returned), resolve credential for a host`,
		Dangerous:    false,
		LicenseGated: "",
	},
	CredentialWrite: {
		ID:           CredentialWrite,
		Category:     "credential",
		Description:  `Create credentials (system or host scope), set is_default`,
		Dangerous:    false,
		LicenseGated: "",
	},
	CredentialDelete: {
		ID:           CredentialDelete,
		Category:     "credential",
		Description:  `Soft-delete credentials (set is_active=false)`,
		Dangerous:    true,
		LicenseGated: "",
	},
	ScanRead: {
		ID:           ScanRead,
		Category:     "scan",
		Description:  `View scans, scan sessions, and scan results`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ScanExecute: {
		ID:           ScanExecute,
		Category:     "scan",
		Description:  `Queue or start a scan against a host or fleet`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ScanCancel: {
		ID:           ScanCancel,
		Category:     "scan",
		Description:  `Cancel a running or queued scan`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ScanTemplateRead: {
		ID:           ScanTemplateRead,
		Category:     "scan_template",
		Description:  `List and view scan templates`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ScanTemplateWrite: {
		ID:           ScanTemplateWrite,
		Category:     "scan_template",
		Description:  `Create or update scan templates`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ScanTemplateDelete: {
		ID:           ScanTemplateDelete,
		Category:     "scan_template",
		Description:  `Delete a scan template (does not affect historical scans)`,
		Dangerous:    true,
		LicenseGated: "",
	},
	ComplianceRead: {
		ID:           ComplianceRead,
		Category:     "compliance",
		Description:  `View compliance state, drift detection results, posture queries`,
		Dangerous:    false,
		LicenseGated: "",
	},
	BaselineRead: {
		ID:           BaselineRead,
		Category:     "baseline",
		Description:  `View compliance baselines`,
		Dangerous:    false,
		LicenseGated: "",
	},
	BaselineWrite: {
		ID:           BaselineWrite,
		Category:     "baseline",
		Description:  `Establish or update a compliance baseline`,
		Dangerous:    false,
		LicenseGated: "",
	},
	BaselineDelete: {
		ID:           BaselineDelete,
		Category:     "baseline",
		Description:  `Clear an existing baseline (resets drift detection)`,
		Dangerous:    true,
		LicenseGated: "",
	},
	ExceptionRead: {
		ID:           ExceptionRead,
		Category:     "exception",
		Description:  `View exception requests and active exceptions`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ExceptionRequest: {
		ID:           ExceptionRequest,
		Category:     "exception",
		Description:  `Submit a new exception request`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ExceptionComment: {
		ID:           ExceptionComment,
		Category:     "exception",
		Description:  `Add comments to exception requests`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ExceptionApprove: {
		ID:           ExceptionApprove,
		Category:     "exception",
		Description:  `Approve or reject exception requests`,
		Dangerous:    false,
		LicenseGated: "",
	},
	ExceptionRevoke: {
		ID:           ExceptionRevoke,
		Category:     "exception",
		Description:  `Revoke an active exception before its expiry`,
		Dangerous:    true,
		LicenseGated: "",
	},
	AlertRead: {
		ID:           AlertRead,
		Category:     "alert",
		Description:  `View alerts and alert history`,
		Dangerous:    false,
		LicenseGated: "",
	},
	AlertAcknowledge: {
		ID:           AlertAcknowledge,
		Category:     "alert",
		Description:  `Acknowledge an alert (suppresses repeat notifications)`,
		Dangerous:    false,
		LicenseGated: "",
	},
	AlertResolve: {
		ID:           AlertResolve,
		Category:     "alert",
		Description:  `Mark an alert as resolved`,
		Dangerous:    false,
		LicenseGated: "",
	},
	AlertWrite: {
		ID:           AlertWrite,
		Category:     "alert",
		Description:  `Create or modify alert thresholds`,
		Dangerous:    false,
		LicenseGated: "",
	},
	NotificationRead: {
		ID:           NotificationRead,
		Category:     "notification",
		Description:  `View notification channels and delivery history`,
		Dangerous:    false,
		LicenseGated: "",
	},
	NotificationWrite: {
		ID:           NotificationWrite,
		Category:     "notification",
		Description:  `Create or update notification channels`,
		Dangerous:    false,
		LicenseGated: "",
	},
	NotificationDelete: {
		ID:           NotificationDelete,
		Category:     "notification",
		Description:  `Delete notification channels`,
		Dangerous:    true,
		LicenseGated: "",
	},
	NotificationTest: {
		ID:           NotificationTest,
		Category:     "notification",
		Description:  `Send a test notification through a channel`,
		Dangerous:    false,
		LicenseGated: "",
	},
	LicenseRead: {
		ID:           LicenseRead,
		Category:     "license",
		Description:  `View license status, features, quotas, and history`,
		Dangerous:    false,
		LicenseGated: "",
	},
	LicenseInstall: {
		ID:           LicenseInstall,
		Category:     "license",
		Description:  `Install or replace the active license file`,
		Dangerous:    true,
		LicenseGated: "",
	},
	LicenseRevoke: {
		ID:           LicenseRevoke,
		Category:     "license",
		Description:  `Mark the current license as revoked (forces Free tier)`,
		Dangerous:    true,
		LicenseGated: "",
	},
	PolicyRead: {
		ID:           PolicyRead,
		Category:     "policy",
		Description:  `View active policies, policy_history, and reload outcomes`,
		Dangerous:    false,
		LicenseGated: "",
	},
	PolicyReload: {
		ID:           PolicyReload,
		Category:     "policy",
		Description:  `Trigger a policy reload (SIGHUP equivalent via API)`,
		Dangerous:    false,
		LicenseGated: "",
	},
	PolicyInstall: {
		ID:           PolicyInstall,
		Category:     "policy",
		Description:  `Install a new policy version (writes a signed file)`,
		Dangerous:    true,
		LicenseGated: "",
	},
	RemediationRead: {
		ID:           RemediationRead,
		Category:     "remediation",
		Description:  `View remediation requests and history`,
		Dangerous:    false,
		LicenseGated: "",
	},
	RemediationRequest: {
		ID:           RemediationRequest,
		Category:     "remediation",
		Description:  `Submit a remediation request`,
		Dangerous:    false,
		LicenseGated: "",
	},
	RemediationApprove: {
		ID:           RemediationApprove,
		Category:     "remediation",
		Description:  `Approve or reject remediation requests`,
		Dangerous:    false,
		LicenseGated: "",
	},
	RemediationExecute: {
		ID:           RemediationExecute,
		Category:     "remediation",
		Description:  `Execute an approved remediation against hosts`,
		Dangerous:    true,
		LicenseGated: "remediation_execution",
	},
	RemediationRollback: {
		ID:           RemediationRollback,
		Category:     "remediation",
		Description:  `Roll back a previously executed remediation`,
		Dangerous:    true,
		LicenseGated: "remediation_execution",
	},
	IntegrationRead: {
		ID:           IntegrationRead,
		Category:     "integration",
		Description:  `View configured plugins and webhook endpoints`,
		Dangerous:    false,
		LicenseGated: "",
	},
	IntegrationWrite: {
		ID:           IntegrationWrite,
		Category:     "integration",
		Description:  `Configure plugins and webhook endpoints`,
		Dangerous:    false,
		LicenseGated: "",
	},
	IntegrationExecute: {
		ID:           IntegrationExecute,
		Category:     "integration",
		Description:  `Manually invoke a plugin (out-of-band of the normal trigger)`,
		Dangerous:    false,
		LicenseGated: "",
	},
	AuditRead: {
		ID:           AuditRead,
		Category:     "audit",
		Description:  `Query the audit log via filters or DSL`,
		Dangerous:    false,
		LicenseGated: "",
	},
	AuditExport: {
		ID:           AuditExport,
		Category:     "audit",
		Description:  `Export the audit log to file (large extracts)`,
		Dangerous:    false,
		LicenseGated: "audit_export",
	},
	SystemRead: {
		ID:           SystemRead,
		Category:     "system",
		Description:  `View system health, version, and non-secret configuration`,
		Dangerous:    false,
		LicenseGated: "",
	},
	SystemConfigWrite: {
		ID:           SystemConfigWrite,
		Category:     "system",
		Description:  `Modify runtime system configuration`,
		Dangerous:    true,
		LicenseGated: "",
	},
	RoleRead: {
		ID:           RoleRead,
		Category:     "role",
		Description:  `View roles and built-in role definitions`,
		Dangerous:    false,
		LicenseGated: "",
	},
	RoleWrite: {
		ID:           RoleWrite,
		Category:     "role",
		Description:  `Create or update custom roles (Stage 2)`,
		Dangerous:    true,
		LicenseGated: "",
	},
	RoleAssign: {
		ID:           RoleAssign,
		Category:     "role",
		Description:  `Assign roles to users`,
		Dangerous:    true,
		LicenseGated: "",
	},
	AdminUserManage: {
		ID:           AdminUserManage,
		Category:     "admin",
		Description:  `Manage users including role assignments`,
		Dangerous:    true,
		LicenseGated: "",
	},
	AdminRoleManage: {
		ID:           AdminRoleManage,
		Category:     "admin",
		Description:  `Create, update, delete custom roles; assign roles to users`,
		Dangerous:    true,
		LicenseGated: "",
	},
	AdminRetentionPolicy: {
		ID:           AdminRetentionPolicy,
		Category:     "admin",
		Description:  `Modify audit/scan/log retention policies`,
		Dangerous:    true,
		LicenseGated: "",
	},
	AdminSsoProvider: {
		ID:           AdminSsoProvider,
		Category:     "admin",
		Description:  `Configure SSO providers (OIDC, SAML)`,
		Dangerous:    true,
		LicenseGated: "",
	},
	AdminSystemSetting: {
		ID:           AdminSystemSetting,
		Category:     "admin",
		Description:  `Modify high-impact system settings (TLS, listener, FIPS mode hint)`,
		Dangerous:    true,
		LicenseGated: "",
	},
}

// permissionOrder preserves declaration order from permissions.yaml.
var permissionOrder = []Permission{
	AuthRead,
	AuthWrite,
	UserRead,
	UserWrite,
	UserDelete,
	HostRead,
	HostWrite,
	HostDelete,
	HostConnectivityCheck,
	HostIntelligenceRefresh,
	CredentialRead,
	CredentialWrite,
	CredentialDelete,
	ScanRead,
	ScanExecute,
	ScanCancel,
	ScanTemplateRead,
	ScanTemplateWrite,
	ScanTemplateDelete,
	ComplianceRead,
	BaselineRead,
	BaselineWrite,
	BaselineDelete,
	ExceptionRead,
	ExceptionRequest,
	ExceptionComment,
	ExceptionApprove,
	ExceptionRevoke,
	AlertRead,
	AlertAcknowledge,
	AlertResolve,
	AlertWrite,
	NotificationRead,
	NotificationWrite,
	NotificationDelete,
	NotificationTest,
	LicenseRead,
	LicenseInstall,
	LicenseRevoke,
	PolicyRead,
	PolicyReload,
	PolicyInstall,
	RemediationRead,
	RemediationRequest,
	RemediationApprove,
	RemediationExecute,
	RemediationRollback,
	IntegrationRead,
	IntegrationWrite,
	IntegrationExecute,
	AuditRead,
	AuditExport,
	SystemRead,
	SystemConfigWrite,
	RoleRead,
	RoleWrite,
	RoleAssign,
	AdminUserManage,
	AdminRoleManage,
	AdminRetentionPolicy,
	AdminSsoProvider,
	AdminSystemSetting,
}

// AllPermissions returns every active permission id in registry order.
func AllPermissions() []Permission {
	out := make([]Permission, len(permissionOrder))
	copy(out, permissionOrder)
	return out
}

// IsKnown reports whether p is a registered (non-deprecated) permission.
func IsKnown(p Permission) bool {
	_, ok := Permissions[p]
	return ok
}

// IsDangerous reports whether p is registered with dangerous=true.
func IsDangerous(p Permission) bool {
	if m, ok := Permissions[p]; ok {
		return m.Dangerous
	}
	return false
}

// LicenseGate returns the feature id required for p, or "" if p is not
// license-gated. Empty string for unknown permissions.
func LicenseGate(p Permission) string {
	if m, ok := Permissions[p]; ok {
		return m.LicenseGated
	}
	return ""
}

// Categories returns the registered category ids in declaration order.
func Categories() []string {
	return categoryOrder
}

var categoryOrder = []string{
	"auth",
	"user",
	"host",
	"credential",
	"scan",
	"scan_template",
	"compliance",
	"baseline",
	"exception",
	"alert",
	"notification",
	"license",
	"policy",
	"remediation",
	"integration",
	"audit",
	"system",
	"role",
	"admin",
}

// CategoryDescription returns the description for a category id, or "" if unknown.
func CategoryDescription(id string) string {
	return categoryDescriptions[id]
}

var categoryDescriptions = map[string]string{
	"auth":          `Self-service authentication and profile`,
	"user":          `Admin-managed user accounts`,
	"host":          `Host management and discovery`,
	"credential":    `SSH credential storage and resolution`,
	"scan":          `Scan execution`,
	"scan_template": `Scan template lifecycle`,
	"compliance":    `Compliance state and posture queries`,
	"baseline":      `Compliance baseline management`,
	"exception":     `Compliance exception lifecycle`,
	"alert":         `Alert lifecycle and threshold management`,
	"notification":  `Notification channels and dispatch`,
	"license":       `License install, view, history`,
	"policy":        `Policy reload, install, history`,
	"remediation":   `Remediation request, approve, execute, rollback`,
	"integration":   `External plugin and webhook configuration`,
	"audit":         `Audit log query and export`,
	"system":        `System config and health`,
	"role":          `Role and permission administration`,
	"admin":         `High-privilege administrative operations`,
}
