// Code generated by scripts/gen-rbac.go from auth/permissions.yaml.
// DO NOT EDIT. Re-run via: make generate-rbac

package auth

// RoleID is the stable identifier of a built-in or custom role.
type RoleID string

// Built-in role constants. Custom roles created at runtime use ad-hoc
// RoleID values; the registry only ships built-in role definitions.
const (
	// Read-only access across the platform
	RoleViewer RoleID = "viewer"
	// Read-only plus exception authority and audit export
	RoleAuditor RoleID = "auditor"
	// Day-to-day operations - hosts, scans, alerts
	RoleOpsLead RoleID = "ops_lead"
	// Full security operations including dangerous and license-gated actions
	RoleSecurityAdmin RoleID = "security_admin"
	// Full system administration
	RoleAdmin RoleID = "admin"
)

// RoleDefinition is a role and its effective permission set.
type RoleDefinition struct {
	ID          RoleID
	Description string
	Permissions []Permission
	IsBuiltIn   bool
}

// BuiltInRoles maps every built-in RoleID to its definition with
// category wildcards expanded at codegen time. Runtime callers do
// not need to interpret wildcards.
var BuiltInRoles = map[RoleID]RoleDefinition{
	RoleViewer: {
		ID:          RoleViewer,
		Description: `Read-only access across the platform`,
		IsBuiltIn:   true,
		Permissions: []Permission{
			AlertRead,
			AuditRead,
			AuthRead,
			BaselineRead,
			ComplianceRead,
			ExceptionRead,
			HostRead,
			IntegrationRead,
			LicenseRead,
			NotificationRead,
			PolicyRead,
			RemediationRead,
			RoleRead,
			ScanRead,
			ScanTemplateRead,
			SystemRead,
		},
	},
	RoleAuditor: {
		ID:          RoleAuditor,
		Description: `Read-only plus exception authority and audit export`,
		IsBuiltIn:   true,
		Permissions: []Permission{
			AlertRead,
			AuditExport,
			AuditRead,
			AuthRead,
			AuthWrite,
			BaselineRead,
			ComplianceRead,
			ExceptionApprove,
			ExceptionComment,
			ExceptionRead,
			ExceptionRequest,
			HostRead,
			IntegrationRead,
			LicenseRead,
			NotificationRead,
			PolicyRead,
			RemediationRead,
			ScanRead,
			ScanTemplateRead,
			SystemRead,
		},
	},
	RoleOpsLead: {
		ID:          RoleOpsLead,
		Description: `Day-to-day operations - hosts, scans, alerts`,
		IsBuiltIn:   true,
		Permissions: []Permission{
			AlertAcknowledge,
			AlertRead,
			AlertResolve,
			AuditRead,
			AuthRead,
			AuthWrite,
			BaselineRead,
			BaselineWrite,
			ComplianceRead,
			CredentialRead,
			ExceptionComment,
			ExceptionRead,
			ExceptionRequest,
			HostConnectivityCheck,
			HostIntelligenceRefresh,
			HostRead,
			HostWrite,
			IntegrationRead,
			LicenseRead,
			NotificationRead,
			NotificationTest,
			PolicyRead,
			RemediationExecute,
			RemediationRead,
			RemediationRequest,
			RemediationRollback,
			ScanCancel,
			ScanExecute,
			ScanRead,
			ScanTemplateRead,
			ScanTemplateWrite,
			SystemRead,
		},
	},
	RoleSecurityAdmin: {
		ID:          RoleSecurityAdmin,
		Description: `Full security operations including dangerous and license-gated actions`,
		IsBuiltIn:   true,
		Permissions: []Permission{
			AlertAcknowledge,
			AlertRead,
			AlertResolve,
			AlertWrite,
			AuditExport,
			AuditRead,
			AuthRead,
			AuthWrite,
			BaselineDelete,
			BaselineRead,
			BaselineWrite,
			ComplianceRead,
			CredentialDelete,
			CredentialRead,
			CredentialWrite,
			ExceptionApprove,
			ExceptionComment,
			ExceptionRead,
			ExceptionRequest,
			ExceptionRevoke,
			HostConnectivityCheck,
			HostDelete,
			HostIntelligenceRefresh,
			HostRead,
			HostWrite,
			IntegrationExecute,
			IntegrationRead,
			IntegrationWrite,
			LicenseInstall,
			LicenseRead,
			NotificationDelete,
			NotificationRead,
			NotificationTest,
			NotificationWrite,
			PolicyInstall,
			PolicyRead,
			PolicyReload,
			RemediationApprove,
			RemediationExecute,
			RemediationRead,
			RemediationRequest,
			RemediationRollback,
			ScanCancel,
			ScanExecute,
			ScanRead,
			ScanTemplateDelete,
			ScanTemplateRead,
			ScanTemplateWrite,
			SystemAuthPolicyRead,
			SystemAuthPolicyWrite,
			SystemRead,
			TokenDelete,
			TokenRead,
			TokenWrite,
			UserRead,
			UserWrite,
		},
	},
	RoleAdmin: {
		ID:          RoleAdmin,
		Description: `Full system administration`,
		IsBuiltIn:   true,
		Permissions: []Permission{
			AdminRetentionPolicy,
			AdminRoleManage,
			AdminSsoProvider,
			AdminSystemSetting,
			AdminUserManage,
			AlertAcknowledge,
			AlertRead,
			AlertResolve,
			AlertWrite,
			AuditExport,
			AuditRead,
			AuthRead,
			AuthWrite,
			BaselineDelete,
			BaselineRead,
			BaselineWrite,
			ComplianceRead,
			CredentialDelete,
			CredentialRead,
			CredentialWrite,
			ExceptionApprove,
			ExceptionComment,
			ExceptionRead,
			ExceptionRequest,
			ExceptionRevoke,
			HostConnectivityCheck,
			HostDelete,
			HostIntelligenceRefresh,
			HostRead,
			HostWrite,
			IntegrationExecute,
			IntegrationRead,
			IntegrationWrite,
			LicenseInstall,
			LicenseRead,
			LicenseRevoke,
			NotificationDelete,
			NotificationRead,
			NotificationTest,
			NotificationWrite,
			PolicyInstall,
			PolicyRead,
			PolicyReload,
			RemediationApprove,
			RemediationExecute,
			RemediationRead,
			RemediationRequest,
			RemediationRollback,
			RoleAssign,
			RoleRead,
			RoleWrite,
			ScanCancel,
			ScanExecute,
			ScanRead,
			ScanTemplateDelete,
			ScanTemplateRead,
			ScanTemplateWrite,
			SystemAuthPolicyRead,
			SystemAuthPolicyWrite,
			SystemConfigWrite,
			SystemRead,
			TokenDelete,
			TokenRead,
			TokenWrite,
			UserDelete,
			UserRead,
			UserWrite,
		},
	},
}

// BuiltInRoleIDs returns the IDs of the built-in roles in declaration order.
func BuiltInRoleIDs() []RoleID {
	out := make([]RoleID, len(builtInRoleOrder))
	copy(out, builtInRoleOrder)
	return out
}

var builtInRoleOrder = []RoleID{
	RoleViewer,
	RoleAuditor,
	RoleOpsLead,
	RoleSecurityAdmin,
	RoleAdmin,
}
