/**
 * Scan metrics cards showing Target Host, XCCDF Score,
 * Compliance Score, and Risk Score.
 */

import React from 'react';
import { Box, Card, CardContent, Typography, LinearProgress, Tooltip } from '@mui/material';
import Grid from '@mui/material/GridLegacy';
import {
  Computer as ComputerIcon,
  Security as SecurityIcon,
  Assessment as AssessmentIcon,
  BugReport as BugReportIcon,
  InfoOutlined as InfoOutlinedIcon,
} from '@mui/icons-material';
import type { ScanDetails } from './scanTypes';

interface ScanMetricsCardsProps {
  scan: ScanDetails;
}

const ScanMetricsCards: React.FC<ScanMetricsCardsProps> = ({ scan }) => {
  return (
    <Grid container spacing={3} mb={3}>
      <Grid item xs={12} md={6} lg={3}>
        <Card>
          <CardContent>
            <Box display="flex" alignItems="center" gap={1} mb={1}>
              <ComputerIcon color="primary" />
              <Typography variant="subtitle2" color="text.secondary">
                Target Host
              </Typography>
            </Box>
            <Typography variant="h6" fontWeight="bold">
              {scan.host_name}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {scan.hostname}
            </Typography>
          </CardContent>
        </Card>
      </Grid>

      <Grid item xs={12} md={6} lg={3}>
        <Card>
          <CardContent>
            <Box display="flex" alignItems="center" gap={1} mb={1}>
              <SecurityIcon color="primary" />
              <Typography variant="subtitle2" color="text.secondary">
                XCCDF Native Score
              </Typography>
              <Tooltip
                title="Official SCAP score extracted from the XCCDF results file. This is the authoritative score generated by the OpenSCAP scanner during evaluation."
                arrow
                placement="top"
              >
                <InfoOutlinedIcon sx={{ fontSize: 16, color: 'text.secondary', cursor: 'help' }} />
              </Tooltip>
            </Box>
            <Typography variant="h6" fontWeight="bold">
              {scan.results?.xccdf_score !== null && scan.results?.xccdf_score !== undefined
                ? `${scan.results.xccdf_score.toFixed(2)}/${scan.results?.xccdf_score_max || 100}`
                : 'N/A'}
            </Typography>
            <Typography variant="body2" color="text.secondary" noWrap>
              {scan.content_name}
            </Typography>
          </CardContent>
        </Card>
      </Grid>

      <Grid item xs={12} md={6} lg={3}>
        <Card>
          <CardContent>
            <Box display="flex" alignItems="center" gap={1} mb={1}>
              <AssessmentIcon color="primary" />
              <Typography variant="subtitle2" color="text.secondary">
                Compliance Score
              </Typography>
              <Tooltip
                title="Simple pass/fail ratio calculated as (passed rules / total evaluated rules) x 100. This provides a quick overview of overall compliance status."
                arrow
                placement="top"
              >
                <InfoOutlinedIcon sx={{ fontSize: 16, color: 'text.secondary', cursor: 'help' }} />
              </Tooltip>
            </Box>
            <Typography variant="h6" fontWeight="bold">
              {scan.results?.score || 'N/A'}
            </Typography>
            <LinearProgress
              variant="determinate"
              value={parseFloat(scan.results?.score || '0')}
              sx={{ mt: 1 }}
              color={
                parseFloat(scan.results?.score || '0') > 80
                  ? 'success'
                  : parseFloat(scan.results?.score || '0') > 60
                    ? 'warning'
                    : 'error'
              }
            />
          </CardContent>
        </Card>
      </Grid>

      <Grid item xs={12} md={6} lg={3}>
        <Card>
          <CardContent>
            <Box display="flex" alignItems="center" gap={1} mb={1}>
              <BugReportIcon color="primary" />
              <Typography variant="subtitle2" color="text.secondary">
                Risk Score
              </Typography>
              <Tooltip
                title="Severity-weighted risk score based on failed findings. Critical=10pts, High=5pts, Medium=2pts, Low=0.5pts. Aligned with NIST SP 800-30 risk assessment guidance."
                arrow
                placement="top"
              >
                <InfoOutlinedIcon sx={{ fontSize: 16, color: 'text.secondary', cursor: 'help' }} />
              </Tooltip>
            </Box>
            <Typography
              variant="h6"
              fontWeight="bold"
              color={
                scan.results?.risk_level === 'critical'
                  ? 'error.main'
                  : scan.results?.risk_level === 'high'
                    ? 'warning.main'
                    : scan.results?.risk_level === 'medium'
                      ? 'info.main'
                      : 'success.main'
              }
            >
              {scan.results?.risk_score !== null && scan.results?.risk_score !== undefined
                ? scan.results.risk_score.toFixed(1)
                : 'N/A'}
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ textTransform: 'uppercase' }}>
              {scan.results?.risk_level || 'Unknown'} risk
            </Typography>
          </CardContent>
        </Card>
      </Grid>
    </Grid>
  );
};

export default ScanMetricsCards;
